# Generated by saihai-forge (python) — DO NOT EDIT
# Source of truth: saihai/catalog/desktop.saihai.lisp
# Verify: saihai-forge check   (fails on any drift)

ACTIONS = {
    "window-focus": {"id": "window-focus", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-focus-direction": {"id": "window-focus-direction", "cls": "converging", "auth": "l1", "params": [{"name": "direction", "kind": "direction", "required": True}, {"name": "wrap", "kind": "bool", "required": False}]},
    "window-move": {"id": "window-move", "cls": "converging", "auth": "l2", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "x", "kind": "int", "required": True}, {"name": "y", "kind": "int", "required": True}]},
    "window-resize": {"id": "window-resize", "cls": "converging", "auth": "l2", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "width", "kind": "int", "required": True}, {"name": "height", "kind": "int", "required": True}]},
    "window-close": {"id": "window-close", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-set-fullscreen": {"id": "window-set-fullscreen", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "window-set-maximized": {"id": "window-set-maximized", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "window-set-floating": {"id": "window-set-floating", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "window-raise": {"id": "window-raise", "cls": "blind", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-lower": {"id": "window-lower", "cls": "blind", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-to-workspace": {"id": "window-to-workspace", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "workspace", "kind": "selector", "required": True}, {"name": "follow", "kind": "bool", "required": False}]},
    "window-to-output": {"id": "window-to-output", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "output", "kind": "selector", "required": True}]},
    "window-swap": {"id": "window-swap", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "other", "kind": "selector", "required": True}]},
    "window-list": {"id": "window-list", "cls": "read", "auth": "l0", "params": [{"name": "filter", "kind": "str", "required": False}]},
    "window-get": {"id": "window-get", "cls": "read", "auth": "l0", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "workspace-focus": {"id": "workspace-focus", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": True}]},
    "workspace-cycle": {"id": "workspace-cycle", "cls": "converging", "auth": "l1", "params": [{"name": "direction", "kind": "direction", "required": True}, {"name": "wrap", "kind": "bool", "required": False}]},
    "workspace-create": {"id": "workspace-create", "cls": "converging", "auth": "l1", "params": [{"name": "name", "kind": "str", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "workspace-destroy": {"id": "workspace-destroy", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": True}]},
    "workspace-rename": {"id": "workspace-rename", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": True}, {"name": "name", "kind": "str", "required": True}]},
    "workspace-move-to-output": {"id": "workspace-move-to-output", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": True}, {"name": "output", "kind": "selector", "required": True}]},
    "workspace-list": {"id": "workspace-list", "cls": "read", "auth": "l0", "params": []},
    "layout-set": {"id": "layout-set", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": True}, {"name": "layout", "kind": "str", "required": True}]},
    "layout-set-orientation": {"id": "layout-set-orientation", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": True}, {"name": "orientation", "kind": "str", "required": True}]},
    "layout-set-gaps": {"id": "layout-set-gaps", "cls": "converging", "auth": "l1", "params": [{"name": "inner", "kind": "int", "required": True}, {"name": "outer", "kind": "int", "required": True}]},
    "layout-equalize": {"id": "layout-equalize", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": False}]},
    "layout-get": {"id": "layout-get", "cls": "read", "auth": "l0", "params": [{"name": "workspace", "kind": "selector", "required": True}]},
    "output-set-enabled": {"id": "output-set-enabled", "cls": "converging", "auth": "l2", "params": [{"name": "output", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "output-set-mode": {"id": "output-set-mode", "cls": "converging", "auth": "l2", "params": [{"name": "output", "kind": "selector", "required": True}, {"name": "width", "kind": "int", "required": True}, {"name": "height", "kind": "int", "required": True}, {"name": "refresh", "kind": "int", "required": False}]},
    "output-set-scale": {"id": "output-set-scale", "cls": "converging", "auth": "l2", "params": [{"name": "output", "kind": "selector", "required": True}, {"name": "scale", "kind": "int", "required": True}]},
    "output-set-transform": {"id": "output-set-transform", "cls": "converging", "auth": "l2", "params": [{"name": "output", "kind": "selector", "required": True}, {"name": "transform", "kind": "str", "required": True}]},
    "output-set-position": {"id": "output-set-position", "cls": "converging", "auth": "l2", "params": [{"name": "output", "kind": "selector", "required": True}, {"name": "x", "kind": "int", "required": True}, {"name": "y", "kind": "int", "required": True}]},
    "output-list": {"id": "output-list", "cls": "read", "auth": "l0", "params": []},
    "input-set-repeat": {"id": "input-set-repeat", "cls": "converging", "auth": "l1", "params": [{"name": "rate", "kind": "int", "required": True}, {"name": "delay", "kind": "int", "required": True}]},
    "input-set-layout": {"id": "input-set-layout", "cls": "converging", "auth": "l1", "params": [{"name": "layout", "kind": "str", "required": True}, {"name": "variant", "kind": "str", "required": False}]},
    "input-bind": {"id": "input-bind", "cls": "converging", "auth": "l1", "params": [{"name": "chord", "kind": "str", "required": True}, {"name": "action", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "input-unbind": {"id": "input-unbind", "cls": "converging", "auth": "l1", "params": [{"name": "chord", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "input-set-mode": {"id": "input-set-mode", "cls": "converging", "auth": "l1", "params": [{"name": "mode", "kind": "str", "required": True}]},
    "input-send-keys": {"id": "input-send-keys", "cls": "blind", "auth": "l3", "params": [{"name": "keys", "kind": "str", "required": True}, {"name": "target", "kind": "selector", "required": False}]},
    "input-list-bindings": {"id": "input-list-bindings", "cls": "read", "auth": "l0", "params": [{"name": "mode", "kind": "str", "required": False}]},
    "focus-set-policy": {"id": "focus-set-policy", "cls": "converging", "auth": "l1", "params": [{"name": "policy", "kind": "str", "required": True}]},
    "focus-get": {"id": "focus-get", "cls": "read", "auth": "l0", "params": []},
    "session-lock": {"id": "session-lock", "cls": "converging", "auth": "l1", "params": []},
    "session-unlock": {"id": "session-unlock", "cls": "converging", "auth": "l1", "params": []},
    "session-logout": {"id": "session-logout", "cls": "converging", "auth": "l1", "params": []},
    "session-suspend": {"id": "session-suspend", "cls": "blind", "auth": "l2", "params": []},
    "session-reboot": {"id": "session-reboot", "cls": "blind", "auth": "l2", "params": []},
    "session-poweroff": {"id": "session-poweroff", "cls": "blind", "auth": "l2", "params": []},
    "session-switch-vt": {"id": "session-switch-vt", "cls": "converging", "auth": "l2", "params": [{"name": "vt", "kind": "int", "required": True}]},
    "session-get": {"id": "session-get", "cls": "read", "auth": "l0", "params": []},
    "login-authenticate": {"id": "login-authenticate", "cls": "converging", "auth": "l2", "params": [{"name": "user", "kind": "str", "required": True}]},
    "login-start-session": {"id": "login-start-session", "cls": "converging", "auth": "l2", "params": [{"name": "user", "kind": "str", "required": True}, {"name": "session", "kind": "str", "required": False}]},
    "login-end-session": {"id": "login-end-session", "cls": "converging", "auth": "l2", "params": [{"name": "user", "kind": "str", "required": True}]},
    "login-switch-user": {"id": "login-switch-user", "cls": "converging", "auth": "l2", "params": [{"name": "user", "kind": "str", "required": True}]},
    "login-list-sessions": {"id": "login-list-sessions", "cls": "read", "auth": "l0", "params": []},
    "seat-get": {"id": "seat-get", "cls": "read", "auth": "l0", "params": []},
    "launch-spawn": {"id": "launch-spawn", "cls": "converging", "auth": "l1", "params": [{"name": "command", "kind": "str", "required": True}, {"name": "workspace", "kind": "selector", "required": False}]},
    "launch-focus-or-spawn": {"id": "launch-focus-or-spawn", "cls": "converging", "auth": "l1", "params": [{"name": "criteria", "kind": "selector", "required": True}, {"name": "command", "kind": "str", "required": True}]},
    "clipboard-get": {"id": "clipboard-get", "cls": "read", "auth": "l1", "params": [{"name": "selection", "kind": "str", "required": False}]},
    "clipboard-put": {"id": "clipboard-put", "cls": "converging", "auth": "l1", "params": [{"name": "content", "kind": "str", "required": True}, {"name": "selection", "kind": "str", "required": False}]},
    "clipboard-clear": {"id": "clipboard-clear", "cls": "converging", "auth": "l1", "params": [{"name": "selection", "kind": "str", "required": False}]},
    "capture-screenshot": {"id": "capture-screenshot", "cls": "blind", "auth": "l2", "params": [{"name": "target", "kind": "selector", "required": False}, {"name": "path", "kind": "str", "required": False}]},
    "capture-screencast-start": {"id": "capture-screencast-start", "cls": "blind", "auth": "l2", "params": [{"name": "target", "kind": "selector", "required": False}]},
    "capture-screencast-stop": {"id": "capture-screencast-stop", "cls": "blind", "auth": "l2", "params": []},
    "notify-send": {"id": "notify-send", "cls": "blind", "auth": "l0", "params": [{"name": "summary", "kind": "str", "required": True}, {"name": "body", "kind": "str", "required": False}, {"name": "urgency", "kind": "str", "required": False}]},
    "notify-dismiss": {"id": "notify-dismiss", "cls": "blind", "auth": "l0", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "theme-select": {"id": "theme-select", "cls": "converging", "auth": "l1", "params": [{"name": "name", "kind": "str", "required": True}]},
    "theme-reload": {"id": "theme-reload", "cls": "converging", "auth": "l1", "params": []},
    "theme-get": {"id": "theme-get", "cls": "read", "auth": "l0", "params": []},
    "system-reload-config": {"id": "system-reload-config", "cls": "converging", "auth": "l1", "params": []},
    "system-get-state": {"id": "system-get-state", "cls": "read", "auth": "l0", "params": []},
    "system-version": {"id": "system-version", "cls": "read", "auth": "l0", "params": []},
}

def window_focus(target: str):
    """Give a window keyboard focus"""
    return {"action": "window-focus", "args": {"target": target}}

def window_focus_direction(direction: str, wrap: bool | None = None):
    """Move focus spatially"""
    return {"action": "window-focus-direction", "args": {"direction": direction, "wrap": wrap}}

def window_move(target: str, x: int, y: int):
    """Move a window to a position"""
    return {"action": "window-move", "args": {"target": target, "x": x, "y": y}}

def window_resize(target: str, width: int, height: int):
    """Resize a window"""
    return {"action": "window-resize", "args": {"target": target, "width": width, "height": height}}

def window_close(target: str):
    """Ask a window to close"""
    return {"action": "window-close", "args": {"target": target}}

def window_set_fullscreen(target: str, on: bool):
    """Set or clear fullscreen"""
    return {"action": "window-set-fullscreen", "args": {"target": target, "on": on}}

def window_set_maximized(target: str, on: bool):
    """Set or clear maximized"""
    return {"action": "window-set-maximized", "args": {"target": target, "on": on}}

def window_set_floating(target: str, on: bool):
    """Float or tile a window"""
    return {"action": "window-set-floating", "args": {"target": target, "on": on}}

def window_raise(target: str):
    """Raise a window in the stacking order"""
    return {"action": "window-raise", "args": {"target": target}}

def window_lower(target: str):
    """Lower a window in the stacking order"""
    return {"action": "window-lower", "args": {"target": target}}

def window_to_workspace(target: str, workspace: str, follow: bool | None = None):
    """Send a window to a workspace"""
    return {"action": "window-to-workspace", "args": {"target": target, "workspace": workspace, "follow": follow}}

def window_to_output(target: str, output: str):
    """Send a window to another output"""
    return {"action": "window-to-output", "args": {"target": target, "output": output}}

def window_swap(target: str, other: str):
    """Swap two windows in the layout"""
    return {"action": "window-swap", "args": {"target": target, "other": other}}

def window_list(filter: str | None = None):
    """List managed windows"""
    return {"action": "window-list", "args": {"filter": filter}}

def window_get(target: str):
    """Read one window's full state"""
    return {"action": "window-get", "args": {"target": target}}

def workspace_focus(workspace: str):
    """Switch to a workspace"""
    return {"action": "workspace-focus", "args": {"workspace": workspace}}

def workspace_cycle(direction: str, wrap: bool | None = None):
    """Move to the next or previous workspace"""
    return {"action": "workspace-cycle", "args": {"direction": direction, "wrap": wrap}}

def workspace_create(name: str, output: str | None = None):
    """Create a workspace"""
    return {"action": "workspace-create", "args": {"name": name, "output": output}}

def workspace_destroy(workspace: str):
    """Destroy a workspace"""
    return {"action": "workspace-destroy", "args": {"workspace": workspace}}

def workspace_rename(workspace: str, name: str):
    """Rename a workspace"""
    return {"action": "workspace-rename", "args": {"workspace": workspace, "name": name}}

def workspace_move_to_output(workspace: str, output: str):
    """Move a workspace to an output"""
    return {"action": "workspace-move-to-output", "args": {"workspace": workspace, "output": output}}

def workspace_list():
    """List workspaces"""
    return {"action": "workspace-list", "args": {}}

def layout_set(workspace: str, layout: str):
    """Set a workspace's layout"""
    return {"action": "layout-set", "args": {"workspace": workspace, "layout": layout}}

def layout_set_orientation(workspace: str, orientation: str):
    """Set the split orientation"""
    return {"action": "layout-set-orientation", "args": {"workspace": workspace, "orientation": orientation}}

def layout_set_gaps(inner: int, outer: int):
    """Set inner and outer gaps"""
    return {"action": "layout-set-gaps", "args": {"inner": inner, "outer": outer}}

def layout_equalize(workspace: str | None = None):
    """Equalize sibling sizes"""
    return {"action": "layout-equalize", "args": {"workspace": workspace}}

def layout_get(workspace: str):
    """Read a workspace's layout"""
    return {"action": "layout-get", "args": {"workspace": workspace}}

def output_set_enabled(output: str, on: bool):
    """Enable or disable an output"""
    return {"action": "output-set-enabled", "args": {"output": output, "on": on}}

def output_set_mode(output: str, width: int, height: int, refresh: int | None = None):
    """Set an output's resolution and refresh"""
    return {"action": "output-set-mode", "args": {"output": output, "width": width, "height": height, "refresh": refresh}}

def output_set_scale(output: str, scale: int):
    """Set an output's scale factor"""
    return {"action": "output-set-scale", "args": {"output": output, "scale": scale}}

def output_set_transform(output: str, transform: str):
    """Rotate or flip an output"""
    return {"action": "output-set-transform", "args": {"output": output, "transform": transform}}

def output_set_position(output: str, x: int, y: int):
    """Place an output in the layout"""
    return {"action": "output-set-position", "args": {"output": output, "x": x, "y": y}}

def output_list():
    """List outputs and their modes"""
    return {"action": "output-list", "args": {}}

def input_set_repeat(rate: int, delay: int):
    """Set key repeat rate and delay"""
    return {"action": "input-set-repeat", "args": {"rate": rate, "delay": delay}}

def input_set_layout(layout: str, variant: str | None = None):
    """Set the keyboard layout"""
    return {"action": "input-set-layout", "args": {"layout": layout, "variant": variant}}

def input_bind(chord: str, action: str, mode: str | None = None):
    """Bind a key chord to an action"""
    return {"action": "input-bind", "args": {"chord": chord, "action": action, "mode": mode}}

def input_unbind(chord: str, mode: str | None = None):
    """Remove a key binding"""
    return {"action": "input-unbind", "args": {"chord": chord, "mode": mode}}

def input_set_mode(mode: str):
    """Switch the active keymap mode"""
    return {"action": "input-set-mode", "args": {"mode": mode}}

def input_send_keys(keys: str, target: str | None = None):
    """Inject a synthetic key sequence"""
    return {"action": "input-send-keys", "args": {"keys": keys, "target": target}}

def input_list_bindings(mode: str | None = None):
    """List active key bindings"""
    return {"action": "input-list-bindings", "args": {"mode": mode}}

def focus_set_policy(policy: str):
    """Set the focus-follows-mouse policy"""
    return {"action": "focus-set-policy", "args": {"policy": policy}}

def focus_get():
    """Read what currently has focus"""
    return {"action": "focus-get", "args": {}}

def session_lock():
    """Lock the session"""
    return {"action": "session-lock", "args": {}}

def session_unlock():
    """Unlock the session after authentication"""
    return {"action": "session-unlock", "args": {}}

def session_logout():
    """End the session"""
    return {"action": "session-logout", "args": {}}

def session_suspend():
    """Suspend the machine"""
    return {"action": "session-suspend", "args": {}}

def session_reboot():
    """Reboot the machine"""
    return {"action": "session-reboot", "args": {}}

def session_poweroff():
    """Power the machine off"""
    return {"action": "session-poweroff", "args": {}}

def session_switch_vt(vt: int):
    """Switch to another virtual terminal"""
    return {"action": "session-switch-vt", "args": {"vt": vt}}

def session_get():
    """Read session state"""
    return {"action": "session-get", "args": {}}

def login_authenticate(user: str):
    """Authenticate a user against PAM"""
    return {"action": "login-authenticate", "args": {"user": user}}

def login_start_session(user: str, session: str | None = None):
    """Start a session for an authenticated user"""
    return {"action": "login-start-session", "args": {"user": user, "session": session}}

def login_end_session(user: str):
    """End a session and close its PAM handle"""
    return {"action": "login-end-session", "args": {"user": user}}

def login_switch_user(user: str):
    """Switch to another user's session"""
    return {"action": "login-switch-user", "args": {"user": user}}

def login_list_sessions():
    """List active sessions"""
    return {"action": "login-list-sessions", "args": {}}

def seat_get():
    """Read the seat's identity and devices"""
    return {"action": "seat-get", "args": {}}

def launch_spawn(command: str, workspace: str | None = None):
    """Spawn a program"""
    return {"action": "launch-spawn", "args": {"command": command, "workspace": workspace}}

def launch_focus_or_spawn(criteria: str, command: str):
    """Focus a program's window, or spawn it"""
    return {"action": "launch-focus-or-spawn", "args": {"criteria": criteria, "command": command}}

def clipboard_get(selection: str | None = None):
    """Read the clipboard"""
    return {"action": "clipboard-get", "args": {"selection": selection}}

def clipboard_put(content: str, selection: str | None = None):
    """Write the clipboard"""
    return {"action": "clipboard-put", "args": {"content": content, "selection": selection}}

def clipboard_clear(selection: str | None = None):
    """Clear the clipboard"""
    return {"action": "clipboard-clear", "args": {"selection": selection}}

def capture_screenshot(target: str | None = None, path: str | None = None):
    """Capture a screenshot"""
    return {"action": "capture-screenshot", "args": {"target": target, "path": path}}

def capture_screencast_start(target: str | None = None):
    """Start a screencast"""
    return {"action": "capture-screencast-start", "args": {"target": target}}

def capture_screencast_stop():
    """Stop a screencast"""
    return {"action": "capture-screencast-stop", "args": {}}

def notify_send(summary: str, body: str | None = None, urgency: str | None = None):
    """Post a notification"""
    return {"action": "notify-send", "args": {"summary": summary, "body": body, "urgency": urgency}}

def notify_dismiss(target: str):
    """Dismiss a notification"""
    return {"action": "notify-dismiss", "args": {"target": target}}

def theme_select(name: str):
    """Select the active theme"""
    return {"action": "theme-select", "args": {"name": name}}

def theme_reload():
    """Re-read the active theme's artifacts"""
    return {"action": "theme-reload", "args": {}}

def theme_get():
    """Read the active theme"""
    return {"action": "theme-get", "args": {}}

def system_reload_config():
    """Re-read the desktop configuration"""
    return {"action": "system-reload-config", "args": {}}

def system_get_state():
    """Read the whole observable desktop state"""
    return {"action": "system-get-state", "args": {}}

def system_version():
    """Read the desktop's version and backend"""
    return {"action": "system-version", "args": {}}

