// Generated by saihai-forge (go) — DO NOT EDIT
// Source of truth: saihai/catalog/desktop.saihai.lisp
// Verify: saihai-forge check   (fails on any drift)

package saihai

type Param struct {
	Name string
	Kind string
	Required bool
}

type ActionMeta struct {
	ID string
	Class string
	Auth string
	Params []Param
}

var Actions = map[string]ActionMeta{
	"window-focus": {ID: "window-focus", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-focus-direction": {ID: "window-focus-direction", Class: "converging", Auth: "l1", Params: []Param{{Name: "direction", Kind: "direction", Required: true}, {Name: "wrap", Kind: "bool", Required: false}, }},
	"window-move": {ID: "window-move", Class: "converging", Auth: "l2", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "position", Kind: "str", Required: true}, }},
	"window-move-direction": {ID: "window-move-direction", Class: "converging", Auth: "l1", Params: []Param{{Name: "direction", Kind: "direction", Required: true}, }},
	"window-resize": {ID: "window-resize", Class: "converging", Auth: "l2", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "size", Kind: "str", Required: true}, }},
	"window-resize-delta": {ID: "window-resize-delta", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "axis", Kind: "str", Required: true}, {Name: "amount", Kind: "int", Required: true}, }},
	"window-close": {ID: "window-close", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-set-fullscreen": {ID: "window-set-fullscreen", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"window-set-maximized": {ID: "window-set-maximized", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"window-set-minimized": {ID: "window-set-minimized", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"window-set-floating": {ID: "window-set-floating", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"window-swap": {ID: "window-swap", Class: "converging", Auth: "l1", Params: []Param{{Name: "a", Kind: "selector", Required: true}, {Name: "b", Kind: "str", Required: true}, }},
	"window-raise": {ID: "window-raise", Class: "blind", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-lower": {ID: "window-lower", Class: "blind", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-center": {ID: "window-center", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "scope", Kind: "str", Required: false}, }},
	"window-full-width": {ID: "window-full-width", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-equalize": {ID: "window-equalize", Class: "converging", Auth: "l1", Params: []Param{{Name: "scope", Kind: "str", Required: false}, }},
	"window-set-managed": {ID: "window-set-managed", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "managed", Kind: "bool", Required: true}, }},
	"window-set-stacked": {ID: "window-set-stacked", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"window-set-always-on-top": {ID: "window-set-always-on-top", Class: "blind", Auth: "l3", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"window-to-output": {ID: "window-to-output", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"window-to-workspace": {ID: "window-to-workspace", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "workspace", Kind: "selector", Required: false}, {Name: "follow", Kind: "bool", Required: false}, }},
	"window-consume-or-expel": {ID: "window-consume-or-expel", Class: "converging", Auth: "l1", Params: []Param{{Name: "direction", Kind: "direction", Required: true}, }},
	"window-list": {ID: "window-list", Class: "read", Auth: "l1", Params: []Param{{Name: "filter", Kind: "str", Required: false}, }},
	"window-get": {ID: "window-get", Class: "read", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-pick": {ID: "window-pick", Class: "read", Auth: "l1", Params: []Param{{Name: "prompt", Kind: "str", Required: true}, }},
	"window-to-scratchpad": {ID: "window-to-scratchpad", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "name", Kind: "str", Required: false}, }},
	"scratchpad-show": {ID: "scratchpad-show", Class: "converging", Auth: "l1", Params: []Param{{Name: "name", Kind: "str", Required: false}, }},
	"scratchpad-hide": {ID: "scratchpad-hide", Class: "converging", Auth: "l1", Params: []Param{{Name: "name", Kind: "str", Required: false}, }},
	"scratchpad-cycle": {ID: "scratchpad-cycle", Class: "converging", Auth: "l1", Params: []Param{{Name: "direction", Kind: "direction", Required: true}, }},
	"scratchpad-list": {ID: "scratchpad-list", Class: "read", Auth: "l1", Params: []Param{}},
	"workspace-focus": {ID: "workspace-focus", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: false}, }},
	"workspace-cycle": {ID: "workspace-cycle", Class: "converging", Auth: "l1", Params: []Param{{Name: "direction", Kind: "direction", Required: true}, {Name: "wrap", Kind: "bool", Required: false}, {Name: "scope", Kind: "str", Required: false}, }},
	"workspace-create": {ID: "workspace-create", Class: "converging", Auth: "l1", Params: []Param{{Name: "name", Kind: "str", Required: false}, {Name: "output", Kind: "selector", Required: false}, }},
	"workspace-destroy": {ID: "workspace-destroy", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: false}, {Name: "on_nonempty", Kind: "str", Required: false}, }},
	"workspace-rename": {ID: "workspace-rename", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: false}, {Name: "name", Kind: "str", Required: false}, }},
	"workspace-move-to-output": {ID: "workspace-move-to-output", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: false}, {Name: "output", Kind: "selector", Required: false}, }},
	"workspace-reorder": {ID: "workspace-reorder", Class: "converging", Auth: "l1", Params: []Param{{Name: "direction", Kind: "direction", Required: true}, {Name: "workspace", Kind: "selector", Required: false}, }},
	"workspace-set-urgent": {ID: "workspace-set-urgent", Class: "converging", Auth: "l1", Params: []Param{{Name: "urgent", Kind: "str", Required: true}, {Name: "workspace", Kind: "selector", Required: false}, }},
	"workspace-list": {ID: "workspace-list", Class: "read", Auth: "l1", Params: []Param{}},
	"layout-set": {ID: "layout-set", Class: "converging", Auth: "l1", Params: []Param{{Name: "layout", Kind: "str", Required: true}, {Name: "accordion", Kind: "str", Required: true}, {Name: "floating", Kind: "str", Required: true}, {Name: "auto", Kind: "str", Required: true}, {Name: "workspace", Kind: "selector", Required: false}, }},
	"layout-set-orientation": {ID: "layout-set-orientation", Class: "converging", Auth: "l1", Params: []Param{{Name: "orientation", Kind: "str", Required: true}, {Name: "workspace", Kind: "selector", Required: false}, }},
	"layout-flatten-tree": {ID: "layout-flatten-tree", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: false}, }},
	"layout-set-gaps": {ID: "layout-set-gaps", Class: "converging", Auth: "l1", Params: []Param{{Name: "inner_h", Kind: "str", Required: true}, {Name: "inner_v", Kind: "str", Required: true}, {Name: "outer_l", Kind: "str", Required: true}, {Name: "outer_r", Kind: "str", Required: true}, {Name: "outer_t", Kind: "str", Required: true}, {Name: "outer_b", Kind: "int", Required: true}, }},
	"layout-set-default-root": {ID: "layout-set-default-root", Class: "converging", Auth: "l1", Params: []Param{{Name: "layout", Kind: "str", Required: true}, {Name: "orientation", Kind: "str", Required: true}, }},
	"layout-get": {ID: "layout-get", Class: "read", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: false}, }},
	"output-set-enabled": {ID: "output-set-enabled", Class: "converging", Auth: "l2", Params: []Param{{Name: "enabled", Kind: "bool", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"output-set-mode": {ID: "output-set-mode", Class: "converging", Auth: "l2", Params: []Param{{Name: "output", Kind: "selector", Required: false}, {Name: "mode", Kind: "str", Required: false}, }},
	"output-set-scale": {ID: "output-set-scale", Class: "converging", Auth: "l2", Params: []Param{{Name: "scale", Kind: "int", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"output-set-transform": {ID: "output-set-transform", Class: "converging", Auth: "l2", Params: []Param{{Name: "transform", Kind: "str", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"output-set-position": {ID: "output-set-position", Class: "converging", Auth: "l2", Params: []Param{{Name: "position", Kind: "str", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"output-set-adaptive-sync": {ID: "output-set-adaptive-sync", Class: "converging", Auth: "l2", Params: []Param{{Name: "output", Kind: "selector", Required: false}, {Name: "mode", Kind: "str", Required: false}, }},
	"output-set-power": {ID: "output-set-power", Class: "converging", Auth: "l2", Params: []Param{{Name: "power", Kind: "str", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"output-set-gamma": {ID: "output-set-gamma", Class: "blind", Auth: "l2", Params: []Param{{Name: "correction", Kind: "str", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"output-apply-transaction": {ID: "output-apply-transaction", Class: "converging", Auth: "l2", Params: []Param{{Name: "changes", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"output-list": {ID: "output-list", Class: "read", Auth: "l0", Params: []Param{}},
	"input-set-keyboard-repeat": {ID: "input-set-keyboard-repeat", Class: "blind", Auth: "l1", Params: []Param{{Name: "rate_hz", Kind: "str", Required: true}, {Name: "delay_ms", Kind: "str", Required: true}, }},
	"input-set-keyboard-layout": {ID: "input-set-keyboard-layout", Class: "converging", Auth: "l1", Params: []Param{{Name: "layouts", Kind: "str", Required: true}, {Name: "options", Kind: "str", Required: true}, {Name: "model", Kind: "str", Required: true}, {Name: "variant", Kind: "str", Required: false}, }},
	"input-switch-keyboard-layout": {ID: "input-switch-keyboard-layout", Class: "converging", Auth: "l1", Params: []Param{{Name: "selector", Kind: "selector", Required: true}, }},
	"input-set-pointer-accel": {ID: "input-set-pointer-accel", Class: "blind", Auth: "l1", Params: []Param{{Name: "device", Kind: "selector", Required: true}, {Name: "profile", Kind: "str", Required: true}, {Name: "speed", Kind: "str", Required: true}, }},
	"input-set-natural-scroll": {ID: "input-set-natural-scroll", Class: "blind", Auth: "l1", Params: []Param{{Name: "device", Kind: "str", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"input-set-tap-to-click": {ID: "input-set-tap-to-click", Class: "blind", Auth: "l1", Params: []Param{{Name: "device", Kind: "str", Required: true}, {Name: "on", Kind: "bool", Required: true}, {Name: "drag_lock", Kind: "str", Required: true}, }},
	"input-set-cursor": {ID: "input-set-cursor", Class: "blind", Auth: "l1", Params: []Param{{Name: "theme", Kind: "str", Required: true}, {Name: "size", Kind: "str", Required: true}, }},
	"input-list-devices": {ID: "input-list-devices", Class: "read", Auth: "l1", Params: []Param{}},
	"input-get-state": {ID: "input-get-state", Class: "read", Auth: "l1", Params: []Param{}},
	"input-bind": {ID: "input-bind", Class: "converging", Auth: "l1", Params: []Param{{Name: "chord", Kind: "str", Required: true}, {Name: "action", Kind: "str", Required: true}, {Name: "condition", Kind: "str", Required: true}, {Name: "rank", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"input-unbind": {ID: "input-unbind", Class: "converging", Auth: "l1", Params: []Param{{Name: "chord", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"input-set-mode": {ID: "input-set-mode", Class: "converging", Auth: "l1", Params: []Param{{Name: "mode", Kind: "str", Required: false}, }},
	"input-remap": {ID: "input-remap", Class: "converging", Auth: "l2", Params: []Param{{Name: "source", Kind: "str", Required: true}, {Name: "to", Kind: "str", Required: true}, {Name: "condition", Kind: "str", Required: true}, }},
	"input-unremap": {ID: "input-unremap", Class: "converging", Auth: "l2", Params: []Param{{Name: "source", Kind: "str", Required: true}, }},
	"input-bind-sequence": {ID: "input-bind-sequence", Class: "converging", Auth: "l1", Params: []Param{{Name: "chords", Kind: "str", Required: true}, {Name: "action", Kind: "str", Required: true}, {Name: "timeout_ms", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"input-chord-cancel": {ID: "input-chord-cancel", Class: "converging", Auth: "l1", Params: []Param{}},
	"input-set-leader-timeout": {ID: "input-set-leader-timeout", Class: "converging", Auth: "l1", Params: []Param{{Name: "timeout_ms", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"input-grab-keyboard": {ID: "input-grab-keyboard", Class: "converging", Auth: "l1", Params: []Param{{Name: "exclusive", Kind: "str", Required: true}, {Name: "scope", Kind: "str", Required: false}, }},
	"input-release-keyboard": {ID: "input-release-keyboard", Class: "converging", Auth: "l1", Params: []Param{{Name: "scope", Kind: "str", Required: false}, }},
	"bindings-list": {ID: "bindings-list", Class: "read", Auth: "l0", Params: []Param{{Name: "mode", Kind: "str", Required: false}, }},
	"bindings-check-conflicts": {ID: "bindings-check-conflicts", Class: "read", Auth: "l0", Params: []Param{{Name: "scope", Kind: "str", Required: false}, }},
	"input-inject-key": {ID: "input-inject-key", Class: "blind", Auth: "l3", Params: []Param{{Name: "key", Kind: "str", Required: true}, {Name: "state", Kind: "str", Required: true}, {Name: "modifiers", Kind: "str", Required: true}, }},
	"input-inject-chord": {ID: "input-inject-chord", Class: "blind", Auth: "l3", Params: []Param{{Name: "chord", Kind: "str", Required: true}, }},
	"input-inject-text": {ID: "input-inject-text", Class: "blind", Auth: "l3", Params: []Param{{Name: "text", Kind: "str", Required: true}, {Name: "method", Kind: "str", Required: true}, }},
	"input-inject-pointer": {ID: "input-inject-pointer", Class: "blind", Auth: "l3", Params: []Param{{Name: "motion", Kind: "str", Required: true}, {Name: "button", Kind: "str", Required: true}, {Name: "axis", Kind: "str", Required: true}, }},
	"gesture-bind": {ID: "gesture-bind", Class: "converging", Auth: "l1", Params: []Param{{Name: "gesture", Kind: "str", Required: true}, {Name: "action", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"gesture-unbind": {ID: "gesture-unbind", Class: "converging", Auth: "l1", Params: []Param{{Name: "gesture", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"gesture-set-suppression": {ID: "gesture-set-suppression", Class: "converging", Auth: "l1", Params: []Param{{Name: "kind", Kind: "str", Required: true}, {Name: "five_finger_pinch", Kind: "str", Required: true}, {Name: "five_finger_spread", Kind: "str", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"gesture-list": {ID: "gesture-list", Class: "read", Auth: "l0", Params: []Param{}},
	"focus-set-follows-mouse": {ID: "focus-set-follows-mouse", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"focus-set-mouse-follows-focus": {ID: "focus-set-mouse-follows-focus", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"focus-set-auto-center": {ID: "focus-set-auto-center", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"focus-set-skip-reshuffle": {ID: "focus-set-skip-reshuffle", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"focus-set-manage-toggle-enabled": {ID: "focus-set-manage-toggle-enabled", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"edge-snap-set-left": {ID: "edge-snap-set-left", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"edge-snap-set-right": {ID: "edge-snap-set-right", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"edge-snap-set-preview": {ID: "edge-snap-set-preview", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"edge-snap-set-sticky-dwell": {ID: "edge-snap-set-sticky-dwell", Class: "converging", Auth: "l1", Params: []Param{{Name: "ms", Kind: "str", Required: true}, }},
	"focus-policy-get": {ID: "focus-policy-get", Class: "read", Auth: "l1", Params: []Param{}},
	"pointer-warp-to": {ID: "pointer-warp-to", Class: "blind", Auth: "l1", Params: []Param{{Name: "anchor", Kind: "str", Required: true}, {Name: "monitor_center", Kind: "str", Required: true}, {Name: "window_center", Kind: "str", Required: true}, }},
	"rule-add": {ID: "rule-add", Class: "converging", Auth: "l1", Params: []Param{{Name: "criteria", Kind: "selector", Required: true}, {Name: "trigger", Kind: "str", Required: true}, {Name: "effects", Kind: "str", Required: true}, {Name: "assertiveness", Kind: "str", Required: true}, }},
	"rule-remove": {ID: "rule-remove", Class: "converging", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, }},
	"rule-list": {ID: "rule-list", Class: "read", Auth: "l0", Params: []Param{}},
	"hook-set": {ID: "hook-set", Class: "converging", Auth: "l1", Params: []Param{{Name: "trigger", Kind: "str", Required: true}, {Name: "argv", Kind: "str", Required: true}, }},
	"hook-unset": {ID: "hook-unset", Class: "converging", Auth: "l1", Params: []Param{{Name: "trigger", Kind: "str", Required: true}, }},
	"hook-list": {ID: "hook-list", Class: "read", Auth: "l0", Params: []Param{}},
	"decoration-set-border": {ID: "decoration-set-border", Class: "converging", Auth: "l1", Params: []Param{{Name: "active", Kind: "str", Required: true}, {Name: "inactive", Kind: "str", Required: true}, {Name: "width", Kind: "int", Required: true}, }},
	"decoration-get": {ID: "decoration-get", Class: "read", Auth: "l1", Params: []Param{}},
	"session-lock": {ID: "session-lock", Class: "converging", Auth: "l1", Params: []Param{{Name: "locker", Kind: "str", Required: true}, {Name: "grace_ms", Kind: "str", Required: true}, }},
	"session-unlock": {ID: "session-unlock", Class: "converging", Auth: "l1", Params: []Param{{Name: "proof", Kind: "str", Required: true}, }},
	"session-logout": {ID: "session-logout", Class: "converging", Auth: "l2", Params: []Param{{Name: "session", Kind: "str", Required: true}, {Name: "teardown", Kind: "str", Required: true}, }},
	"session-suspend": {ID: "session-suspend", Class: "converging", Auth: "l2", Params: []Param{{Name: "force", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"session-reboot": {ID: "session-reboot", Class: "blind", Auth: "l3", Params: []Param{{Name: "delay", Kind: "int", Required: true}, {Name: "confirm", Kind: "str", Required: true}, }},
	"session-poweroff": {ID: "session-poweroff", Class: "blind", Auth: "l3", Params: []Param{{Name: "delay", Kind: "int", Required: true}, {Name: "confirm", Kind: "str", Required: true}, }},
	"session-switch-user": {ID: "session-switch-user", Class: "converging", Auth: "l2", Params: []Param{{Name: "to", Kind: "str", Required: true}, }},
	"session-switch-vt": {ID: "session-switch-vt", Class: "converging", Auth: "l2", Params: []Param{{Name: "vt", Kind: "int", Required: true}, {Name: "witness", Kind: "str", Required: true}, }},
	"session-set-idle-inhibit": {ID: "session-set-idle-inhibit", Class: "converging", Auth: "l0", Params: []Param{{Name: "on", Kind: "bool", Required: true}, {Name: "reason", Kind: "str", Required: false}, {Name: "scope", Kind: "str", Required: false}, }},
	"session-set-idle-policy": {ID: "session-set-idle-policy", Class: "blind", Auth: "l1", Params: []Param{{Name: "rungs", Kind: "str", Required: true}, {Name: "action", Kind: "str", Required: true}, }},
	"session-observe-idle": {ID: "session-observe-idle", Class: "read", Auth: "l0", Params: []Param{{Name: "seat", Kind: "str", Required: true}, {Name: "timeout", Kind: "int", Required: false}, }},
	"session-list": {ID: "session-list", Class: "read", Auth: "l0", Params: []Param{}},
	"session-get-state": {ID: "session-get-state", Class: "read", Auth: "l0", Params: []Param{{Name: "session", Kind: "str", Required: true}, }},
	"login-enumerate-principals": {ID: "login-enumerate-principals", Class: "read", Auth: "l2", Params: []Param{{Name: "seat_answer_vec_publicprofile", Kind: "str", Required: true}, }},
	"login-resolve-principal": {ID: "login-resolve-principal", Class: "read", Auth: "l2", Params: []Param{{Name: "name_answer_principal", Kind: "str", Required: true}, }},
	"login-read-public-profile": {ID: "login-read-public-profile", Class: "read", Auth: "l2", Params: []Param{{Name: "principal_answer_publicprofile", Kind: "str", Required: true}, }},
	"login-auth-begin": {ID: "login-auth-begin", Class: "converging", Auth: "l2", Params: []Param{{Name: "service", Kind: "str", Required: true}, {Name: "principal", Kind: "str", Required: true}, {Name: "tty", Kind: "str", Required: true}, }},
	"login-auth-next": {ID: "login-auth-next", Class: "converging", Auth: "l2", Params: []Param{{Name: "handle_pamstep", Kind: "str", Required: true}, }},
	"login-auth-answer": {ID: "login-auth-answer", Class: "converging", Auth: "l2", Params: []Param{{Name: "handle", Kind: "str", Required: true}, {Name: "response", Kind: "str", Required: true}, }},
	"login-auth-account-check": {ID: "login-auth-account-check", Class: "converging", Auth: "l2", Params: []Param{{Name: "handle_acctverdict", Kind: "str", Required: true}, }},
	"login-auth-change-token": {ID: "login-auth-change-token", Class: "converging", Auth: "l2", Params: []Param{{Name: "handle", Kind: "str", Required: true}, }},
	"login-set-credentials": {ID: "login-set-credentials", Class: "blind", Auth: "l2", Params: []Param{{Name: "handle", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"login-put-env": {ID: "login-put-env", Class: "converging", Auth: "l2", Params: []Param{{Name: "handle", Kind: "str", Required: true}, {Name: "key", Kind: "str", Required: true}, {Name: "value", Kind: "str", Required: true}, }},
	"login-get-env": {ID: "login-get-env", Class: "read", Auth: "l2", Params: []Param{{Name: "handle", Kind: "str", Required: true}, }},
	"login-open-session": {ID: "login-open-session", Class: "converging", Auth: "l2", Params: []Param{{Name: "handle", Kind: "str", Required: true}, }},
	"login-close-session": {ID: "login-close-session", Class: "converging", Auth: "l2", Params: []Param{{Name: "handle", Kind: "str", Required: true}, }},
	"login-auth-end": {ID: "login-auth-end", Class: "blind", Auth: "l2", Params: []Param{{Name: "handle", Kind: "str", Required: true}, {Name: "status", Kind: "str", Required: true}, }},
	"login-mint-capability": {ID: "login-mint-capability", Class: "converging", Auth: "l2", Params: []Param{{Name: "proof", Kind: "str", Required: true}, {Name: "seat", Kind: "str", Required: true}, {Name: "handle_seatcapability_authenticated", Kind: "str", Required: true}, }},
	"login-start-session": {ID: "login-start-session", Class: "converging", Auth: "l2", Params: []Param{{Name: "cap", Kind: "str", Required: true}, {Name: "session", Kind: "selector", Required: true}, }},
	"login-autologin": {ID: "login-autologin", Class: "converging", Auth: "l2", Params: []Param{{Name: "user", Kind: "str", Required: true}, {Name: "session", Kind: "str", Required: true}, {Name: "runfile", Kind: "str", Required: true}, {Name: "budget", Kind: "str", Required: true}, {Name: "on_exhausted", Kind: "str", Required: true}, }},
	"login-fork-session": {ID: "login-fork-session", Class: "converging", Auth: "l2", Params: []Param{{Name: "argv", Kind: "str", Required: true}, {Name: "env", Kind: "str", Required: true}, {Name: "uid", Kind: "str", Required: true}, {Name: "gid", Kind: "str", Required: true}, {Name: "loginuid", Kind: "str", Required: true}, }},
	"login-signal-session": {ID: "login-signal-session", Class: "converging", Auth: "l2", Params: []Param{{Name: "pid", Kind: "str", Required: true}, {Name: "signal", Kind: "str", Required: true}, }},
	"login-reap-session": {ID: "login-reap-session", Class: "read", Auth: "l2", Params: []Param{{Name: "pid_exitstatus", Kind: "str", Required: true}, }},
	"login-handoff": {ID: "login-handoff", Class: "converging", Auth: "l2", Params: []Param{{Name: "facts", Kind: "str", Required: true}, {Name: "value", Kind: "str", Required: true}, {Name: "epoch", Kind: "str", Required: true}, {Name: "volatility", Kind: "str", Required: true}, {Name: "scope", Kind: "str", Required: false}, }},
	"seat-open": {ID: "seat-open", Class: "converging", Auth: "l2", Params: []Param{{Name: "seat", Kind: "str", Required: true}, }},
	"seat-take-control": {ID: "seat-take-control", Class: "converging", Auth: "l2", Params: []Param{{Name: "seat_uncontrolled_controlled", Kind: "str", Required: true}, }},
	"seat-open-device": {ID: "seat-open-device", Class: "converging", Auth: "l2", Params: []Param{{Name: "controlled", Kind: "str", Required: true}, {Name: "path_devicefd", Kind: "str", Required: true}, }},
	"seat-close-device": {ID: "seat-close-device", Class: "converging", Auth: "l2", Params: []Param{{Name: "controlled", Kind: "str", Required: true}, {Name: "fd", Kind: "str", Required: true}, }},
	"seat-poll": {ID: "seat-poll", Class: "read", Auth: "l2", Params: []Param{{Name: "controlled", Kind: "str", Required: true}, {Name: "deadline_seattransition", Kind: "str", Required: true}, }},
	"seat-ack-disable": {ID: "seat-ack-disable", Class: "converging", Auth: "l2", Params: []Param{{Name: "disabling_disabled", Kind: "str", Required: true}, }},
	"seat-reacquire": {ID: "seat-reacquire", Class: "converging", Auth: "l2", Params: []Param{{Name: "disabled_controlled", Kind: "str", Required: true}, }},
	"vt-query-free": {ID: "vt-query-free", Class: "read", Auth: "l2", Params: []Param{{Name: "seat0witness_vtnumber", Kind: "str", Required: true}, }},
	"vt-set-kd-mode": {ID: "vt-set-kd-mode", Class: "converging", Auth: "l2", Params: []Param{{Name: "witness", Kind: "str", Required: true}, {Name: "vt", Kind: "int", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"vt-set-kb-mode": {ID: "vt-set-kb-mode", Class: "converging", Auth: "l2", Params: []Param{{Name: "witness", Kind: "str", Required: true}, {Name: "vt", Kind: "int", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"launch-spawn": {ID: "launch-spawn", Class: "blind", Auth: "l0", Params: []Param{{Name: "argv", Kind: "str", Required: true}, {Name: "env", Kind: "str", Required: true}, {Name: "cwd", Kind: "str", Required: true}, }},
	"launch-activate": {ID: "launch-activate", Class: "blind", Auth: "l0", Params: []Param{{Name: "app_id", Kind: "str", Required: true}, {Name: "token", Kind: "str", Required: true}, }},
	"launch-desktop-entry": {ID: "launch-desktop-entry", Class: "converging", Auth: "l0", Params: []Param{{Name: "entry", Kind: "str", Required: true}, {Name: "action", Kind: "str", Required: true}, {Name: "args", Kind: "str", Required: true}, }},
	"launch-open-url": {ID: "launch-open-url", Class: "blind", Auth: "l0", Params: []Param{{Name: "url", Kind: "str", Required: true}, }},
	"launch-open-path": {ID: "launch-open-path", Class: "blind", Auth: "l0", Params: []Param{{Name: "using", Kind: "str", Required: true}, {Name: "path", Kind: "str", Required: false}, }},
	"launch-focus-or-spawn": {ID: "launch-focus-or-spawn", Class: "converging", Auth: "l1", Params: []Param{{Name: "criteria", Kind: "selector", Required: true}, {Name: "argv", Kind: "str", Required: true}, {Name: "timeout_ms", Kind: "str", Required: true}, }},
	"launcher-toggle": {ID: "launcher-toggle", Class: "converging", Auth: "l0", Params: []Param{}},
	"launcher-show": {ID: "launcher-show", Class: "converging", Auth: "l0", Params: []Param{}},
	"launcher-hide": {ID: "launcher-hide", Class: "converging", Auth: "l0", Params: []Param{}},
	"launcher-set-query": {ID: "launcher-set-query", Class: "converging", Auth: "l0", Params: []Param{{Name: "query", Kind: "str", Required: true}, }},
	"launcher-get-state": {ID: "launcher-get-state", Class: "read", Auth: "l0", Params: []Param{}},
	"launcher-run-command": {ID: "launcher-run-command", Class: "blind", Auth: "l1", Params: []Param{{Name: "argv", Kind: "str", Required: true}, }},
	"clipboard-get": {ID: "clipboard-get", Class: "read", Auth: "l2", Params: []Param{{Name: "mime_answer_bytes", Kind: "str", Required: true}, {Name: "selection", Kind: "str", Required: false}, }},
	"clipboard-put": {ID: "clipboard-put", Class: "converging", Auth: "l2", Params: []Param{{Name: "mime", Kind: "str", Required: true}, {Name: "data", Kind: "str", Required: true}, {Name: "sensitive", Kind: "bool", Required: true}, {Name: "selection", Kind: "str", Required: false}, }},
	"clipboard-clear": {ID: "clipboard-clear", Class: "converging", Auth: "l2", Params: []Param{{Name: "selection", Kind: "str", Required: false}, }},
	"clipboard-history-list": {ID: "clipboard-history-list", Class: "read", Auth: "l1", Params: []Param{{Name: "limit", Kind: "str", Required: true}, }},
	"clipboard-history-clear": {ID: "clipboard-history-clear", Class: "converging", Auth: "l1", Params: []Param{}},
	"screenshot-capture": {ID: "screenshot-capture", Class: "converging", Auth: "l2", Params: []Param{{Name: "source", Kind: "str", Required: true}, {Name: "sink", Kind: "str", Required: true}, {Name: "include_cursor", Kind: "str", Required: true}, }},
	"screenshot-pick-region": {ID: "screenshot-pick-region", Class: "read", Auth: "l1", Params: []Param{{Name: "prompt", Kind: "str", Required: true}, }},
	"color-pick": {ID: "color-pick", Class: "read", Auth: "l1", Params: []Param{}},
	"screencast-start": {ID: "screencast-start", Class: "converging", Auth: "l2", Params: []Param{{Name: "source", Kind: "str", Required: true}, {Name: "sink", Kind: "str", Required: true}, {Name: "fps", Kind: "str", Required: true}, {Name: "include_cursor_castid", Kind: "str", Required: true}, }},
	"screencast-stop": {ID: "screencast-stop", Class: "converging", Auth: "l2", Params: []Param{{Name: "cast", Kind: "str", Required: true}, }},
	"screencast-list": {ID: "screencast-list", Class: "read", Auth: "l1", Params: []Param{}},
	"notify-send": {ID: "notify-send", Class: "converging", Auth: "l0", Params: []Param{{Name: "summary", Kind: "str", Required: true}, {Name: "app_id", Kind: "str", Required: true}, {Name: "timeout_ms", Kind: "str", Required: true}, {Name: "actions", Kind: "str", Required: true}, {Name: "icon_notificationid", Kind: "str", Required: true}, {Name: "body", Kind: "str", Required: false}, {Name: "urgency", Kind: "str", Required: false}, }},
	"notify-invoke-action": {ID: "notify-invoke-action", Class: "converging", Auth: "l0", Params: []Param{{Name: "id", Kind: "str", Required: true}, {Name: "action_id", Kind: "str", Required: true}, }},
	"notify-dismiss": {ID: "notify-dismiss", Class: "converging", Auth: "l0", Params: []Param{{Name: "id", Kind: "str", Required: true}, }},
	"notify-dismiss-all": {ID: "notify-dismiss-all", Class: "converging", Auth: "l0", Params: []Param{{Name: "filter", Kind: "str", Required: false}, }},
	"notify-mark-read": {ID: "notify-mark-read", Class: "converging", Auth: "l0", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"notify-set-dnd": {ID: "notify-set-dnd", Class: "converging", Auth: "l0", Params: []Param{{Name: "on", Kind: "bool", Required: true}, {Name: "until", Kind: "str", Required: true}, }},
	"notify-list": {ID: "notify-list", Class: "read", Auth: "l0", Params: []Param{{Name: "include_history", Kind: "str", Required: true}, {Name: "filter", Kind: "str", Required: false}, }},
	"notify-history-clear": {ID: "notify-history-clear", Class: "converging", Auth: "l0", Params: []Param{}},
	"notify-history-delete-one": {ID: "notify-history-delete-one", Class: "converging", Auth: "l0", Params: []Param{{Name: "entry_id", Kind: "str", Required: true}, }},
	"notify-toggle-expand": {ID: "notify-toggle-expand", Class: "converging", Auth: "l0", Params: []Param{{Name: "id", Kind: "str", Required: true}, }},
	"notify-toggle-view": {ID: "notify-toggle-view", Class: "converging", Auth: "l0", Params: []Param{}},
	"notify-search": {ID: "notify-search", Class: "converging", Auth: "l0", Params: []Param{{Name: "query", Kind: "str", Required: true}, }},
	"notify-filter-set": {ID: "notify-filter-set", Class: "converging", Auth: "l0", Params: []Param{{Name: "by", Kind: "str", Required: true}, {Name: "value", Kind: "str", Required: true}, {Name: "urgency", Kind: "str", Required: false}, }},
	"layer-spawn": {ID: "layer-spawn", Class: "converging", Auth: "l1", Params: []Param{{Name: "client", Kind: "str", Required: true}, {Name: "layer", Kind: "str", Required: true}, {Name: "anchor", Kind: "str", Required: true}, {Name: "exclusive_zone", Kind: "str", Required: true}, {Name: "keyboard", Kind: "str", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"layer-kill": {ID: "layer-kill", Class: "converging", Auth: "l1", Params: []Param{{Name: "client", Kind: "str", Required: true}, {Name: "teardown", Kind: "str", Required: true}, }},
	"layer-list": {ID: "layer-list", Class: "read", Auth: "l1", Params: []Param{}},
	"pane-session-new": {ID: "pane-session-new", Class: "converging", Auth: "l1", Params: []Param{{Name: "name_panesessionid", Kind: "str", Required: true}, }},
	"pane-session-kill": {ID: "pane-session-kill", Class: "converging", Auth: "l1", Params: []Param{{Name: "session", Kind: "str", Required: true}, }},
	"pane-session-list": {ID: "pane-session-list", Class: "read", Auth: "l0", Params: []Param{}},
	"pane-session-detail": {ID: "pane-session-detail", Class: "read", Auth: "l0", Params: []Param{{Name: "session", Kind: "str", Required: true}, }},
	"pane-list": {ID: "pane-list", Class: "read", Auth: "l0", Params: []Param{{Name: "session", Kind: "str", Required: true}, }},
	"pane-snapshot": {ID: "pane-snapshot", Class: "read", Auth: "l0", Params: []Param{{Name: "pane", Kind: "str", Required: true}, }},
	"pane-send-keys": {ID: "pane-send-keys", Class: "blind", Auth: "l1", Params: []Param{{Name: "pane", Kind: "str", Required: true}, {Name: "keys", Kind: "str", Required: true}, }},
	"pane-set-input-policy": {ID: "pane-set-input-policy", Class: "converging", Auth: "l1", Params: []Param{{Name: "pane", Kind: "str", Required: true}, {Name: "policy", Kind: "str", Required: true}, }},
	"pane-subscriber-count": {ID: "pane-subscriber-count", Class: "read", Auth: "l0", Params: []Param{{Name: "pane", Kind: "str", Required: true}, }},
	"pane-record-start": {ID: "pane-record-start", Class: "converging", Auth: "l1", Params: []Param{{Name: "pane", Kind: "str", Required: true}, }},
	"pane-record-stop": {ID: "pane-record-stop", Class: "converging", Auth: "l1", Params: []Param{{Name: "pane", Kind: "str", Required: true}, }},
	"pane-record-export": {ID: "pane-record-export", Class: "converging", Auth: "l1", Params: []Param{{Name: "pane", Kind: "str", Required: true}, {Name: "path", Kind: "str", Required: false}, }},
	"pane-record-status": {ID: "pane-record-status", Class: "read", Auth: "l0", Params: []Param{{Name: "pane", Kind: "str", Required: true}, }},
	"pane-blocks-list": {ID: "pane-blocks-list", Class: "read", Auth: "l0", Params: []Param{{Name: "pane", Kind: "str", Required: true}, }},
	"pane-block-at": {ID: "pane-block-at", Class: "read", Auth: "l0", Params: []Param{{Name: "pane", Kind: "str", Required: true}, {Name: "index", Kind: "int", Required: false}, }},
	"pane-blocks-status": {ID: "pane-blocks-status", Class: "read", Auth: "l0", Params: []Param{{Name: "pane", Kind: "str", Required: true}, }},
	"pane-stats": {ID: "pane-stats", Class: "read", Auth: "l0", Params: []Param{{Name: "pane", Kind: "str", Required: true}, }},
	"pane-top": {ID: "pane-top", Class: "read", Auth: "l0", Params: []Param{{Name: "limit", Kind: "str", Required: true}, }},
	"pane-daemon-status": {ID: "pane-daemon-status", Class: "read", Auth: "l0", Params: []Param{}},
	"pane-system-resources": {ID: "pane-system-resources", Class: "read", Auth: "l0", Params: []Param{}},
	"pane-socket-info": {ID: "pane-socket-info", Class: "read", Auth: "l0", Params: []Param{}},
	"pane-config-get": {ID: "pane-config-get", Class: "read", Auth: "l0", Params: []Param{}},
	"pane-config-set": {ID: "pane-config-set", Class: "converging", Auth: "l1", Params: []Param{{Name: "yaml", Kind: "str", Required: true}, }},
	"pane-reload-config": {ID: "pane-reload-config", Class: "converging", Auth: "l1", Params: []Param{}},
	"browser-open": {ID: "browser-open", Class: "converging", Auth: "l1", Params: []Param{{Name: "url_browserid", Kind: "str", Required: true}, }},
	"browser-close": {ID: "browser-close", Class: "converging", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, }},
	"browser-focus": {ID: "browser-focus", Class: "converging", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, }},
	"browser-list": {ID: "browser-list", Class: "read", Auth: "l0", Params: []Param{}},
	"browser-move": {ID: "browser-move", Class: "converging", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, {Name: "position", Kind: "str", Required: true}, }},
	"browser-resize": {ID: "browser-resize", Class: "converging", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, {Name: "size", Kind: "str", Required: true}, }},
	"browser-navigate": {ID: "browser-navigate", Class: "converging", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, {Name: "url", Kind: "str", Required: true}, }},
	"browser-snap": {ID: "browser-snap", Class: "converging", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, {Name: "zone", Kind: "str", Required: true}, }},
	"browser-snapshot": {ID: "browser-snapshot", Class: "converging", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, }},
	"browser-snapshot-get": {ID: "browser-snapshot-get", Class: "read", Auth: "l0", Params: []Param{{Name: "id", Kind: "str", Required: true}, }},
	"browser-set-dom": {ID: "browser-set-dom", Class: "blind", Auth: "l1", Params: []Param{{Name: "id", Kind: "str", Required: true}, {Name: "dom", Kind: "str", Required: true}, }},
	"theme-select": {ID: "theme-select", Class: "converging", Auth: "l0", Params: []Param{{Name: "theme", Kind: "str", Required: true}, }},
	"theme-set-appearance": {ID: "theme-set-appearance", Class: "converging", Auth: "l0", Params: []Param{{Name: "appearance", Kind: "str", Required: true}, {Name: "dark", Kind: "str", Required: true}, {Name: "auto", Kind: "str", Required: true}, }},
	"theme-set-font-scale": {ID: "theme-set-font-scale", Class: "converging", Auth: "l0", Params: []Param{{Name: "scale", Kind: "int", Required: true}, }},
	"theme-reload": {ID: "theme-reload", Class: "converging", Auth: "l0", Params: []Param{}},
	"theme-get": {ID: "theme-get", Class: "read", Auth: "l0", Params: []Param{{Name: "theme_per_leaf_provenance", Kind: "str", Required: true}, }},
	"screen-transition-run": {ID: "screen-transition-run", Class: "blind", Auth: "l1", Params: []Param{{Name: "delay_ms", Kind: "str", Required: true}, }},
	"audio-set-volume": {ID: "audio-set-volume", Class: "converging", Auth: "l0", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "sink", Kind: "str", Required: true}, }},
	"audio-set-mute": {ID: "audio-set-mute", Class: "converging", Auth: "l0", Params: []Param{{Name: "on", Kind: "bool", Required: true}, {Name: "sink", Kind: "str", Required: true}, }},
	"audio-set-default-sink": {ID: "audio-set-default-sink", Class: "converging", Auth: "l0", Params: []Param{{Name: "sink", Kind: "str", Required: true}, }},
	"audio-list-sinks": {ID: "audio-list-sinks", Class: "read", Auth: "l0", Params: []Param{}},
	"screensaver-start": {ID: "screensaver-start", Class: "converging", Auth: "l0", Params: []Param{}},
	"trash-empty": {ID: "trash-empty", Class: "converging", Auth: "l3", Params: []Param{{Name: "confirm", Kind: "str", Required: true}, }},
	"volume-eject-all": {ID: "volume-eject-all", Class: "converging", Auth: "l1", Params: []Param{}},
	"overview-set": {ID: "overview-set", Class: "converging", Auth: "l1", Params: []Param{{Name: "on", Kind: "bool", Required: true}, }},
	"config-reload": {ID: "config-reload", Class: "converging", Auth: "l1", Params: []Param{{Name: "path", Kind: "str", Required: false}, }},
	"config-get": {ID: "config-get", Class: "read", Auth: "l0", Params: []Param{{Name: "key", Kind: "str", Required: true}, {Name: "include_provenance", Kind: "str", Required: true}, }},
	"config-set": {ID: "config-set", Class: "converging", Auth: "l1", Params: []Param{{Name: "key", Kind: "str", Required: true}, {Name: "value", Kind: "str", Required: true}, {Name: "apply", Kind: "str", Required: true}, {Name: "live", Kind: "str", Required: true}, }},
	"state-query": {ID: "state-query", Class: "read", Auth: "l1", Params: []Param{{Name: "domain", Kind: "str", Required: true}, }},
	"events-subscribe": {ID: "events-subscribe", Class: "read", Auth: "l1", Params: []Param{{Name: "since", Kind: "str", Required: true}, {Name: "filter", Kind: "str", Required: false}, }},
	"compositor-quit": {ID: "compositor-quit", Class: "blind", Auth: "l3", Params: []Param{{Name: "confirm", Kind: "str", Required: true}, {Name: "teardown", Kind: "str", Required: true}, }},
	"desktop-plan": {ID: "desktop-plan", Class: "read", Auth: "l1", Params: []Param{{Name: "spec", Kind: "str", Required: true}, }},
	"desktop-apply": {ID: "desktop-apply", Class: "converging", Auth: "l1", Params: []Param{{Name: "spec", Kind: "str", Required: true}, {Name: "policy", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"desktop-tick": {ID: "desktop-tick", Class: "converging", Auth: "l1", Params: []Param{{Name: "tickoutcome", Kind: "str", Required: true}, }},
	"desktop-attest": {ID: "desktop-attest", Class: "read", Auth: "l0", Params: []Param{{Name: "receipt_desktoppayload", Kind: "str", Required: true}, }},
	"desktop-health": {ID: "desktop-health", Class: "read", Auth: "l0", Params: []Param{}},
	"desktop-version": {ID: "desktop-version", Class: "read", Auth: "l0", Params: []Param{}},
}

type Call struct {
	Action string
	Args map[string]any
}

// WindowFocus — Window focus
func WindowFocus(target string) Call {
	return Call{Action: "window-focus", Args: map[string]any{
		"target": target,
	}}
}

// WindowFocusDirection — Window focus direction
func WindowFocusDirection(direction string, wrap bool) Call {
	return Call{Action: "window-focus-direction", Args: map[string]any{
		"direction": direction,
		"wrap": wrap,
	}}
}

// WindowMove — Window move
func WindowMove(target string, position string) Call {
	return Call{Action: "window-move", Args: map[string]any{
		"target": target,
		"position": position,
	}}
}

// WindowMoveDirection — Window move direction
func WindowMoveDirection(direction string) Call {
	return Call{Action: "window-move-direction", Args: map[string]any{
		"direction": direction,
	}}
}

// WindowResize — Window resize
func WindowResize(target string, size string) Call {
	return Call{Action: "window-resize", Args: map[string]any{
		"target": target,
		"size": size,
	}}
}

// WindowResizeDelta — Window resize delta
func WindowResizeDelta(target string, axis string, amount int) Call {
	return Call{Action: "window-resize-delta", Args: map[string]any{
		"target": target,
		"axis": axis,
		"amount": amount,
	}}
}

// WindowClose — Window close
func WindowClose(target string) Call {
	return Call{Action: "window-close", Args: map[string]any{
		"target": target,
	}}
}

// WindowSetFullscreen — Window set fullscreen
func WindowSetFullscreen(target string, on bool, output string) Call {
	return Call{Action: "window-set-fullscreen", Args: map[string]any{
		"target": target,
		"on": on,
		"output": output,
	}}
}

// WindowSetMaximized — Window set maximized
func WindowSetMaximized(target string, on bool) Call {
	return Call{Action: "window-set-maximized", Args: map[string]any{
		"target": target,
		"on": on,
	}}
}

// WindowSetMinimized — Window set minimized
func WindowSetMinimized(target string, on bool) Call {
	return Call{Action: "window-set-minimized", Args: map[string]any{
		"target": target,
		"on": on,
	}}
}

// WindowSetFloating — Window set floating
func WindowSetFloating(target string, on bool) Call {
	return Call{Action: "window-set-floating", Args: map[string]any{
		"target": target,
		"on": on,
	}}
}

// WindowSwap — Window swap
func WindowSwap(a string, b string) Call {
	return Call{Action: "window-swap", Args: map[string]any{
		"a": a,
		"b": b,
	}}
}

// WindowRaise — Window raise
func WindowRaise(target string) Call {
	return Call{Action: "window-raise", Args: map[string]any{
		"target": target,
	}}
}

// WindowLower — Window lower
func WindowLower(target string) Call {
	return Call{Action: "window-lower", Args: map[string]any{
		"target": target,
	}}
}

// WindowCenter — Window center
func WindowCenter(target string, scope string) Call {
	return Call{Action: "window-center", Args: map[string]any{
		"target": target,
		"scope": scope,
	}}
}

// WindowFullWidth — Window full width
func WindowFullWidth(target string) Call {
	return Call{Action: "window-full-width", Args: map[string]any{
		"target": target,
	}}
}

// WindowEqualize — Window equalize
func WindowEqualize(scope string) Call {
	return Call{Action: "window-equalize", Args: map[string]any{
		"scope": scope,
	}}
}

// WindowSetManaged — Window set managed
func WindowSetManaged(target string, managed bool) Call {
	return Call{Action: "window-set-managed", Args: map[string]any{
		"target": target,
		"managed": managed,
	}}
}

// WindowSetStacked — Window set stacked
func WindowSetStacked(target string, on bool) Call {
	return Call{Action: "window-set-stacked", Args: map[string]any{
		"target": target,
		"on": on,
	}}
}

// WindowSetAlwaysOnTop — Window set always on top
func WindowSetAlwaysOnTop(target string, on bool) Call {
	return Call{Action: "window-set-always-on-top", Args: map[string]any{
		"target": target,
		"on": on,
	}}
}

// WindowToOutput — Window to output
func WindowToOutput(target string, output string) Call {
	return Call{Action: "window-to-output", Args: map[string]any{
		"target": target,
		"output": output,
	}}
}

// WindowToWorkspace — Window to workspace
func WindowToWorkspace(target string, workspace string, follow bool) Call {
	return Call{Action: "window-to-workspace", Args: map[string]any{
		"target": target,
		"workspace": workspace,
		"follow": follow,
	}}
}

// WindowConsumeOrExpel — Window consume or expel
func WindowConsumeOrExpel(direction string) Call {
	return Call{Action: "window-consume-or-expel", Args: map[string]any{
		"direction": direction,
	}}
}

// WindowList — Window list
func WindowList(filter string) Call {
	return Call{Action: "window-list", Args: map[string]any{
		"filter": filter,
	}}
}

// WindowGet — Window get
func WindowGet(target string) Call {
	return Call{Action: "window-get", Args: map[string]any{
		"target": target,
	}}
}

// WindowPick — Window pick
func WindowPick(prompt string) Call {
	return Call{Action: "window-pick", Args: map[string]any{
		"prompt": prompt,
	}}
}

// WindowToScratchpad — Window to scratchpad
func WindowToScratchpad(target string, name string) Call {
	return Call{Action: "window-to-scratchpad", Args: map[string]any{
		"target": target,
		"name": name,
	}}
}

// ScratchpadShow — Scratchpad show
func ScratchpadShow(name string) Call {
	return Call{Action: "scratchpad-show", Args: map[string]any{
		"name": name,
	}}
}

// ScratchpadHide — Scratchpad hide
func ScratchpadHide(name string) Call {
	return Call{Action: "scratchpad-hide", Args: map[string]any{
		"name": name,
	}}
}

// ScratchpadCycle — Scratchpad cycle
func ScratchpadCycle(direction string) Call {
	return Call{Action: "scratchpad-cycle", Args: map[string]any{
		"direction": direction,
	}}
}

// ScratchpadList — Scratchpad list
func ScratchpadList() Call {
	return Call{Action: "scratchpad-list", Args: map[string]any{
	}}
}

// WorkspaceFocus — Workspace focus
func WorkspaceFocus(workspace string) Call {
	return Call{Action: "workspace-focus", Args: map[string]any{
		"workspace": workspace,
	}}
}

// WorkspaceCycle — Workspace cycle
func WorkspaceCycle(direction string, wrap bool, scope string) Call {
	return Call{Action: "workspace-cycle", Args: map[string]any{
		"direction": direction,
		"wrap": wrap,
		"scope": scope,
	}}
}

// WorkspaceCreate — Workspace create
func WorkspaceCreate(name string, output string) Call {
	return Call{Action: "workspace-create", Args: map[string]any{
		"name": name,
		"output": output,
	}}
}

// WorkspaceDestroy — Workspace destroy
func WorkspaceDestroy(workspace string, onNonempty string) Call {
	return Call{Action: "workspace-destroy", Args: map[string]any{
		"workspace": workspace,
		"on_nonempty": onNonempty,
	}}
}

// WorkspaceRename — Workspace rename
func WorkspaceRename(workspace string, name string) Call {
	return Call{Action: "workspace-rename", Args: map[string]any{
		"workspace": workspace,
		"name": name,
	}}
}

// WorkspaceMoveToOutput — Workspace move to output
func WorkspaceMoveToOutput(workspace string, output string) Call {
	return Call{Action: "workspace-move-to-output", Args: map[string]any{
		"workspace": workspace,
		"output": output,
	}}
}

// WorkspaceReorder — Workspace reorder
func WorkspaceReorder(direction string, workspace string) Call {
	return Call{Action: "workspace-reorder", Args: map[string]any{
		"direction": direction,
		"workspace": workspace,
	}}
}

// WorkspaceSetUrgent — Workspace set urgent
func WorkspaceSetUrgent(urgent string, workspace string) Call {
	return Call{Action: "workspace-set-urgent", Args: map[string]any{
		"urgent": urgent,
		"workspace": workspace,
	}}
}

// WorkspaceList — Workspace list
func WorkspaceList() Call {
	return Call{Action: "workspace-list", Args: map[string]any{
	}}
}

// LayoutSet — Layout set
func LayoutSet(layout string, accordion string, floating string, auto string, workspace string) Call {
	return Call{Action: "layout-set", Args: map[string]any{
		"layout": layout,
		"accordion": accordion,
		"floating": floating,
		"auto": auto,
		"workspace": workspace,
	}}
}

// LayoutSetOrientation — Layout set orientation
func LayoutSetOrientation(orientation string, workspace string) Call {
	return Call{Action: "layout-set-orientation", Args: map[string]any{
		"orientation": orientation,
		"workspace": workspace,
	}}
}

// LayoutFlattenTree — Layout flatten tree
func LayoutFlattenTree(workspace string) Call {
	return Call{Action: "layout-flatten-tree", Args: map[string]any{
		"workspace": workspace,
	}}
}

// LayoutSetGaps — Layout set gaps
func LayoutSetGaps(innerH string, innerV string, outerL string, outerR string, outerT string, outerB int) Call {
	return Call{Action: "layout-set-gaps", Args: map[string]any{
		"inner_h": innerH,
		"inner_v": innerV,
		"outer_l": outerL,
		"outer_r": outerR,
		"outer_t": outerT,
		"outer_b": outerB,
	}}
}

// LayoutSetDefaultRoot — Layout set default root
func LayoutSetDefaultRoot(layout string, orientation string) Call {
	return Call{Action: "layout-set-default-root", Args: map[string]any{
		"layout": layout,
		"orientation": orientation,
	}}
}

// LayoutGet — Layout get
func LayoutGet(workspace string) Call {
	return Call{Action: "layout-get", Args: map[string]any{
		"workspace": workspace,
	}}
}

// OutputSetEnabled — Output set enabled
func OutputSetEnabled(enabled bool, output string) Call {
	return Call{Action: "output-set-enabled", Args: map[string]any{
		"enabled": enabled,
		"output": output,
	}}
}

// OutputSetMode — Output set mode
func OutputSetMode(output string, mode string) Call {
	return Call{Action: "output-set-mode", Args: map[string]any{
		"output": output,
		"mode": mode,
	}}
}

// OutputSetScale — Output set scale
func OutputSetScale(scale int, output string) Call {
	return Call{Action: "output-set-scale", Args: map[string]any{
		"scale": scale,
		"output": output,
	}}
}

// OutputSetTransform — Output set transform
func OutputSetTransform(transform string, output string) Call {
	return Call{Action: "output-set-transform", Args: map[string]any{
		"transform": transform,
		"output": output,
	}}
}

// OutputSetPosition — Output set position
func OutputSetPosition(position string, output string) Call {
	return Call{Action: "output-set-position", Args: map[string]any{
		"position": position,
		"output": output,
	}}
}

// OutputSetAdaptiveSync — Output set adaptive sync
func OutputSetAdaptiveSync(output string, mode string) Call {
	return Call{Action: "output-set-adaptive-sync", Args: map[string]any{
		"output": output,
		"mode": mode,
	}}
}

// OutputSetPower — Output set power
func OutputSetPower(power string, output string) Call {
	return Call{Action: "output-set-power", Args: map[string]any{
		"power": power,
		"output": output,
	}}
}

// OutputSetGamma — Output set gamma
func OutputSetGamma(correction string, output string) Call {
	return Call{Action: "output-set-gamma", Args: map[string]any{
		"correction": correction,
		"output": output,
	}}
}

// OutputApplyTransaction — Output apply transaction
func OutputApplyTransaction(changes string, mode string) Call {
	return Call{Action: "output-apply-transaction", Args: map[string]any{
		"changes": changes,
		"mode": mode,
	}}
}

// OutputList — Output list
func OutputList() Call {
	return Call{Action: "output-list", Args: map[string]any{
	}}
}

// InputSetKeyboardRepeat — Input set keyboard repeat
func InputSetKeyboardRepeat(rateHz string, delayMs string) Call {
	return Call{Action: "input-set-keyboard-repeat", Args: map[string]any{
		"rate_hz": rateHz,
		"delay_ms": delayMs,
	}}
}

// InputSetKeyboardLayout — Input set keyboard layout
func InputSetKeyboardLayout(layouts string, options string, model string, variant string) Call {
	return Call{Action: "input-set-keyboard-layout", Args: map[string]any{
		"layouts": layouts,
		"options": options,
		"model": model,
		"variant": variant,
	}}
}

// InputSwitchKeyboardLayout — Input switch keyboard layout
func InputSwitchKeyboardLayout(selector string) Call {
	return Call{Action: "input-switch-keyboard-layout", Args: map[string]any{
		"selector": selector,
	}}
}

// InputSetPointerAccel — Input set pointer accel
func InputSetPointerAccel(device string, profile string, speed string) Call {
	return Call{Action: "input-set-pointer-accel", Args: map[string]any{
		"device": device,
		"profile": profile,
		"speed": speed,
	}}
}

// InputSetNaturalScroll — Input set natural scroll
func InputSetNaturalScroll(device string, on bool) Call {
	return Call{Action: "input-set-natural-scroll", Args: map[string]any{
		"device": device,
		"on": on,
	}}
}

// InputSetTapToClick — Input set tap to click
func InputSetTapToClick(device string, on bool, dragLock string) Call {
	return Call{Action: "input-set-tap-to-click", Args: map[string]any{
		"device": device,
		"on": on,
		"drag_lock": dragLock,
	}}
}

// InputSetCursor — Input set cursor
func InputSetCursor(theme string, size string) Call {
	return Call{Action: "input-set-cursor", Args: map[string]any{
		"theme": theme,
		"size": size,
	}}
}

// InputListDevices — Input list devices
func InputListDevices() Call {
	return Call{Action: "input-list-devices", Args: map[string]any{
	}}
}

// InputGetState — Input get state
func InputGetState() Call {
	return Call{Action: "input-get-state", Args: map[string]any{
	}}
}

// InputBind — Input bind
func InputBind(chord string, action string, condition string, rank string, mode string) Call {
	return Call{Action: "input-bind", Args: map[string]any{
		"chord": chord,
		"action": action,
		"condition": condition,
		"rank": rank,
		"mode": mode,
	}}
}

// InputUnbind — Input unbind
func InputUnbind(chord string, mode string) Call {
	return Call{Action: "input-unbind", Args: map[string]any{
		"chord": chord,
		"mode": mode,
	}}
}

// InputSetMode — Input set mode
func InputSetMode(mode string) Call {
	return Call{Action: "input-set-mode", Args: map[string]any{
		"mode": mode,
	}}
}

// InputRemap — Input remap
func InputRemap(source string, to string, condition string) Call {
	return Call{Action: "input-remap", Args: map[string]any{
		"source": source,
		"to": to,
		"condition": condition,
	}}
}

// InputUnremap — Input unremap
func InputUnremap(source string) Call {
	return Call{Action: "input-unremap", Args: map[string]any{
		"source": source,
	}}
}

// InputBindSequence — Input bind sequence
func InputBindSequence(chords string, action string, timeoutMs string, mode string) Call {
	return Call{Action: "input-bind-sequence", Args: map[string]any{
		"chords": chords,
		"action": action,
		"timeout_ms": timeoutMs,
		"mode": mode,
	}}
}

// InputChordCancel — Input chord cancel
func InputChordCancel() Call {
	return Call{Action: "input-chord-cancel", Args: map[string]any{
	}}
}

// InputSetLeaderTimeout — Input set leader timeout
func InputSetLeaderTimeout(timeoutMs string, mode string) Call {
	return Call{Action: "input-set-leader-timeout", Args: map[string]any{
		"timeout_ms": timeoutMs,
		"mode": mode,
	}}
}

// InputGrabKeyboard — Input grab keyboard
func InputGrabKeyboard(exclusive string, scope string) Call {
	return Call{Action: "input-grab-keyboard", Args: map[string]any{
		"exclusive": exclusive,
		"scope": scope,
	}}
}

// InputReleaseKeyboard — Input release keyboard
func InputReleaseKeyboard(scope string) Call {
	return Call{Action: "input-release-keyboard", Args: map[string]any{
		"scope": scope,
	}}
}

// BindingsList — Bindings list
func BindingsList(mode string) Call {
	return Call{Action: "bindings-list", Args: map[string]any{
		"mode": mode,
	}}
}

// BindingsCheckConflicts — Bindings check conflicts
func BindingsCheckConflicts(scope string) Call {
	return Call{Action: "bindings-check-conflicts", Args: map[string]any{
		"scope": scope,
	}}
}

// InputInjectKey — Input inject key
func InputInjectKey(key string, state string, modifiers string) Call {
	return Call{Action: "input-inject-key", Args: map[string]any{
		"key": key,
		"state": state,
		"modifiers": modifiers,
	}}
}

// InputInjectChord — Input inject chord
func InputInjectChord(chord string) Call {
	return Call{Action: "input-inject-chord", Args: map[string]any{
		"chord": chord,
	}}
}

// InputInjectText — Input inject text
func InputInjectText(text string, method string) Call {
	return Call{Action: "input-inject-text", Args: map[string]any{
		"text": text,
		"method": method,
	}}
}

// InputInjectPointer — Input inject pointer
func InputInjectPointer(motion string, button string, axis string) Call {
	return Call{Action: "input-inject-pointer", Args: map[string]any{
		"motion": motion,
		"button": button,
		"axis": axis,
	}}
}

// GestureBind — Gesture bind
func GestureBind(gesture string, action string, mode string) Call {
	return Call{Action: "gesture-bind", Args: map[string]any{
		"gesture": gesture,
		"action": action,
		"mode": mode,
	}}
}

// GestureUnbind — Gesture unbind
func GestureUnbind(gesture string, mode string) Call {
	return Call{Action: "gesture-unbind", Args: map[string]any{
		"gesture": gesture,
		"mode": mode,
	}}
}

// GestureSetSuppression — Gesture set suppression
func GestureSetSuppression(kind string, fiveFingerPinch string, fiveFingerSpread string, on bool) Call {
	return Call{Action: "gesture-set-suppression", Args: map[string]any{
		"kind": kind,
		"five_finger_pinch": fiveFingerPinch,
		"five_finger_spread": fiveFingerSpread,
		"on": on,
	}}
}

// GestureList — Gesture list
func GestureList() Call {
	return Call{Action: "gesture-list", Args: map[string]any{
	}}
}

// FocusSetFollowsMouse — Focus set follows mouse
func FocusSetFollowsMouse(on bool) Call {
	return Call{Action: "focus-set-follows-mouse", Args: map[string]any{
		"on": on,
	}}
}

// FocusSetMouseFollowsFocus — Focus set mouse follows focus
func FocusSetMouseFollowsFocus(on bool) Call {
	return Call{Action: "focus-set-mouse-follows-focus", Args: map[string]any{
		"on": on,
	}}
}

// FocusSetAutoCenter — Focus set auto center
func FocusSetAutoCenter(on bool) Call {
	return Call{Action: "focus-set-auto-center", Args: map[string]any{
		"on": on,
	}}
}

// FocusSetSkipReshuffle — Focus set skip reshuffle
func FocusSetSkipReshuffle(on bool) Call {
	return Call{Action: "focus-set-skip-reshuffle", Args: map[string]any{
		"on": on,
	}}
}

// FocusSetManageToggleEnabled — Focus set manage toggle enabled
func FocusSetManageToggleEnabled(on bool) Call {
	return Call{Action: "focus-set-manage-toggle-enabled", Args: map[string]any{
		"on": on,
	}}
}

// EdgeSnapSetLeft — Edge snap set left
func EdgeSnapSetLeft(on bool) Call {
	return Call{Action: "edge-snap-set-left", Args: map[string]any{
		"on": on,
	}}
}

// EdgeSnapSetRight — Edge snap set right
func EdgeSnapSetRight(on bool) Call {
	return Call{Action: "edge-snap-set-right", Args: map[string]any{
		"on": on,
	}}
}

// EdgeSnapSetPreview — Edge snap set preview
func EdgeSnapSetPreview(on bool) Call {
	return Call{Action: "edge-snap-set-preview", Args: map[string]any{
		"on": on,
	}}
}

// EdgeSnapSetStickyDwell — Edge snap set sticky dwell
func EdgeSnapSetStickyDwell(ms string) Call {
	return Call{Action: "edge-snap-set-sticky-dwell", Args: map[string]any{
		"ms": ms,
	}}
}

// FocusPolicyGet — Focus policy get
func FocusPolicyGet() Call {
	return Call{Action: "focus-policy-get", Args: map[string]any{
	}}
}

// PointerWarpTo — Pointer warp to
func PointerWarpTo(anchor string, monitorCenter string, windowCenter string) Call {
	return Call{Action: "pointer-warp-to", Args: map[string]any{
		"anchor": anchor,
		"monitor_center": monitorCenter,
		"window_center": windowCenter,
	}}
}

// RuleAdd — Rule add
func RuleAdd(criteria string, trigger string, effects string, assertiveness string) Call {
	return Call{Action: "rule-add", Args: map[string]any{
		"criteria": criteria,
		"trigger": trigger,
		"effects": effects,
		"assertiveness": assertiveness,
	}}
}

// RuleRemove — Rule remove
func RuleRemove(id string) Call {
	return Call{Action: "rule-remove", Args: map[string]any{
		"id": id,
	}}
}

// RuleList — Rule list
func RuleList() Call {
	return Call{Action: "rule-list", Args: map[string]any{
	}}
}

// HookSet — Hook set
func HookSet(trigger string, argv string) Call {
	return Call{Action: "hook-set", Args: map[string]any{
		"trigger": trigger,
		"argv": argv,
	}}
}

// HookUnset — Hook unset
func HookUnset(trigger string) Call {
	return Call{Action: "hook-unset", Args: map[string]any{
		"trigger": trigger,
	}}
}

// HookList — Hook list
func HookList() Call {
	return Call{Action: "hook-list", Args: map[string]any{
	}}
}

// DecorationSetBorder — Decoration set border
func DecorationSetBorder(active string, inactive string, width int) Call {
	return Call{Action: "decoration-set-border", Args: map[string]any{
		"active": active,
		"inactive": inactive,
		"width": width,
	}}
}

// DecorationGet — Decoration get
func DecorationGet() Call {
	return Call{Action: "decoration-get", Args: map[string]any{
	}}
}

// SessionLock — Session lock
func SessionLock(locker string, graceMs string) Call {
	return Call{Action: "session-lock", Args: map[string]any{
		"locker": locker,
		"grace_ms": graceMs,
	}}
}

// SessionUnlock — Session unlock
func SessionUnlock(proof string) Call {
	return Call{Action: "session-unlock", Args: map[string]any{
		"proof": proof,
	}}
}

// SessionLogout — Session logout
func SessionLogout(session string, teardown string) Call {
	return Call{Action: "session-logout", Args: map[string]any{
		"session": session,
		"teardown": teardown,
	}}
}

// SessionSuspend — Session suspend
func SessionSuspend(force string, mode string) Call {
	return Call{Action: "session-suspend", Args: map[string]any{
		"force": force,
		"mode": mode,
	}}
}

// SessionReboot — Session reboot
func SessionReboot(delay int, confirm string) Call {
	return Call{Action: "session-reboot", Args: map[string]any{
		"delay": delay,
		"confirm": confirm,
	}}
}

// SessionPoweroff — Session poweroff
func SessionPoweroff(delay int, confirm string) Call {
	return Call{Action: "session-poweroff", Args: map[string]any{
		"delay": delay,
		"confirm": confirm,
	}}
}

// SessionSwitchUser — Session switch user
func SessionSwitchUser(to string) Call {
	return Call{Action: "session-switch-user", Args: map[string]any{
		"to": to,
	}}
}

// SessionSwitchVt — Session switch vt
func SessionSwitchVt(vt int, witness string) Call {
	return Call{Action: "session-switch-vt", Args: map[string]any{
		"vt": vt,
		"witness": witness,
	}}
}

// SessionSetIdleInhibit — Session set idle inhibit
func SessionSetIdleInhibit(on bool, reason string, scope string) Call {
	return Call{Action: "session-set-idle-inhibit", Args: map[string]any{
		"on": on,
		"reason": reason,
		"scope": scope,
	}}
}

// SessionSetIdlePolicy — Session set idle policy
func SessionSetIdlePolicy(rungs string, action string) Call {
	return Call{Action: "session-set-idle-policy", Args: map[string]any{
		"rungs": rungs,
		"action": action,
	}}
}

// SessionObserveIdle — Session observe idle
func SessionObserveIdle(seat string, timeout int) Call {
	return Call{Action: "session-observe-idle", Args: map[string]any{
		"seat": seat,
		"timeout": timeout,
	}}
}

// SessionList — Session list
func SessionList() Call {
	return Call{Action: "session-list", Args: map[string]any{
	}}
}

// SessionGetState — Session get state
func SessionGetState(session string) Call {
	return Call{Action: "session-get-state", Args: map[string]any{
		"session": session,
	}}
}

// LoginEnumeratePrincipals — Login enumerate principals
func LoginEnumeratePrincipals(seatAnswerVecPublicprofile string) Call {
	return Call{Action: "login-enumerate-principals", Args: map[string]any{
		"seat_answer_vec_publicprofile": seatAnswerVecPublicprofile,
	}}
}

// LoginResolvePrincipal — Login resolve principal
func LoginResolvePrincipal(nameAnswerPrincipal string) Call {
	return Call{Action: "login-resolve-principal", Args: map[string]any{
		"name_answer_principal": nameAnswerPrincipal,
	}}
}

// LoginReadPublicProfile — Login read public profile
func LoginReadPublicProfile(principalAnswerPublicprofile string) Call {
	return Call{Action: "login-read-public-profile", Args: map[string]any{
		"principal_answer_publicprofile": principalAnswerPublicprofile,
	}}
}

// LoginAuthBegin — Login auth begin
func LoginAuthBegin(service string, principal string, tty string) Call {
	return Call{Action: "login-auth-begin", Args: map[string]any{
		"service": service,
		"principal": principal,
		"tty": tty,
	}}
}

// LoginAuthNext — Login auth next
func LoginAuthNext(handlePamstep string) Call {
	return Call{Action: "login-auth-next", Args: map[string]any{
		"handle_pamstep": handlePamstep,
	}}
}

// LoginAuthAnswer — Login auth answer
func LoginAuthAnswer(handle string, response string) Call {
	return Call{Action: "login-auth-answer", Args: map[string]any{
		"handle": handle,
		"response": response,
	}}
}

// LoginAuthAccountCheck — Login auth account check
func LoginAuthAccountCheck(handleAcctverdict string) Call {
	return Call{Action: "login-auth-account-check", Args: map[string]any{
		"handle_acctverdict": handleAcctverdict,
	}}
}

// LoginAuthChangeToken — Login auth change token
func LoginAuthChangeToken(handle string) Call {
	return Call{Action: "login-auth-change-token", Args: map[string]any{
		"handle": handle,
	}}
}

// LoginSetCredentials — Login set credentials
func LoginSetCredentials(handle string, mode string) Call {
	return Call{Action: "login-set-credentials", Args: map[string]any{
		"handle": handle,
		"mode": mode,
	}}
}

// LoginPutEnv — Login put env
func LoginPutEnv(handle string, key string, value string) Call {
	return Call{Action: "login-put-env", Args: map[string]any{
		"handle": handle,
		"key": key,
		"value": value,
	}}
}

// LoginGetEnv — Login get env
func LoginGetEnv(handle string) Call {
	return Call{Action: "login-get-env", Args: map[string]any{
		"handle": handle,
	}}
}

// LoginOpenSession — Login open session
func LoginOpenSession(handle string) Call {
	return Call{Action: "login-open-session", Args: map[string]any{
		"handle": handle,
	}}
}

// LoginCloseSession — Login close session
func LoginCloseSession(handle string) Call {
	return Call{Action: "login-close-session", Args: map[string]any{
		"handle": handle,
	}}
}

// LoginAuthEnd — Login auth end
func LoginAuthEnd(handle string, status string) Call {
	return Call{Action: "login-auth-end", Args: map[string]any{
		"handle": handle,
		"status": status,
	}}
}

// LoginMintCapability — Login mint capability
func LoginMintCapability(proof string, seat string, handleSeatcapabilityAuthenticated string) Call {
	return Call{Action: "login-mint-capability", Args: map[string]any{
		"proof": proof,
		"seat": seat,
		"handle_seatcapability_authenticated": handleSeatcapabilityAuthenticated,
	}}
}

// LoginStartSession — Login start session
func LoginStartSession(cap string, session string) Call {
	return Call{Action: "login-start-session", Args: map[string]any{
		"cap": cap,
		"session": session,
	}}
}

// LoginAutologin — Login autologin
func LoginAutologin(user string, session string, runfile string, budget string, onExhausted string) Call {
	return Call{Action: "login-autologin", Args: map[string]any{
		"user": user,
		"session": session,
		"runfile": runfile,
		"budget": budget,
		"on_exhausted": onExhausted,
	}}
}

// LoginForkSession — Login fork session
func LoginForkSession(argv string, env string, uid string, gid string, loginuid string) Call {
	return Call{Action: "login-fork-session", Args: map[string]any{
		"argv": argv,
		"env": env,
		"uid": uid,
		"gid": gid,
		"loginuid": loginuid,
	}}
}

// LoginSignalSession — Login signal session
func LoginSignalSession(pid string, signal string) Call {
	return Call{Action: "login-signal-session", Args: map[string]any{
		"pid": pid,
		"signal": signal,
	}}
}

// LoginReapSession — Login reap session
func LoginReapSession(pidExitstatus string) Call {
	return Call{Action: "login-reap-session", Args: map[string]any{
		"pid_exitstatus": pidExitstatus,
	}}
}

// LoginHandoff — Login handoff
func LoginHandoff(facts string, value string, epoch string, volatility string, scope string) Call {
	return Call{Action: "login-handoff", Args: map[string]any{
		"facts": facts,
		"value": value,
		"epoch": epoch,
		"volatility": volatility,
		"scope": scope,
	}}
}

// SeatOpen — Seat open
func SeatOpen(seat string) Call {
	return Call{Action: "seat-open", Args: map[string]any{
		"seat": seat,
	}}
}

// SeatTakeControl — Seat take control
func SeatTakeControl(seatUncontrolledControlled string) Call {
	return Call{Action: "seat-take-control", Args: map[string]any{
		"seat_uncontrolled_controlled": seatUncontrolledControlled,
	}}
}

// SeatOpenDevice — Seat open device
func SeatOpenDevice(controlled string, pathDevicefd string) Call {
	return Call{Action: "seat-open-device", Args: map[string]any{
		"controlled": controlled,
		"path_devicefd": pathDevicefd,
	}}
}

// SeatCloseDevice — Seat close device
func SeatCloseDevice(controlled string, fd string) Call {
	return Call{Action: "seat-close-device", Args: map[string]any{
		"controlled": controlled,
		"fd": fd,
	}}
}

// SeatPoll — Seat poll
func SeatPoll(controlled string, deadlineSeattransition string) Call {
	return Call{Action: "seat-poll", Args: map[string]any{
		"controlled": controlled,
		"deadline_seattransition": deadlineSeattransition,
	}}
}

// SeatAckDisable — Seat ack disable
func SeatAckDisable(disablingDisabled string) Call {
	return Call{Action: "seat-ack-disable", Args: map[string]any{
		"disabling_disabled": disablingDisabled,
	}}
}

// SeatReacquire — Seat reacquire
func SeatReacquire(disabledControlled string) Call {
	return Call{Action: "seat-reacquire", Args: map[string]any{
		"disabled_controlled": disabledControlled,
	}}
}

// VtQueryFree — Vt query free
func VtQueryFree(seat0witnessVtnumber string) Call {
	return Call{Action: "vt-query-free", Args: map[string]any{
		"seat0witness_vtnumber": seat0witnessVtnumber,
	}}
}

// VtSetKdMode — Vt set kd mode
func VtSetKdMode(witness string, vt int, mode string) Call {
	return Call{Action: "vt-set-kd-mode", Args: map[string]any{
		"witness": witness,
		"vt": vt,
		"mode": mode,
	}}
}

// VtSetKbMode — Vt set kb mode
func VtSetKbMode(witness string, vt int, mode string) Call {
	return Call{Action: "vt-set-kb-mode", Args: map[string]any{
		"witness": witness,
		"vt": vt,
		"mode": mode,
	}}
}

// LaunchSpawn — Launch spawn
func LaunchSpawn(argv string, env string, cwd string) Call {
	return Call{Action: "launch-spawn", Args: map[string]any{
		"argv": argv,
		"env": env,
		"cwd": cwd,
	}}
}

// LaunchActivate — Launch activate
func LaunchActivate(appId string, token string) Call {
	return Call{Action: "launch-activate", Args: map[string]any{
		"app_id": appId,
		"token": token,
	}}
}

// LaunchDesktopEntry — Launch desktop entry
func LaunchDesktopEntry(entry string, action string, args string) Call {
	return Call{Action: "launch-desktop-entry", Args: map[string]any{
		"entry": entry,
		"action": action,
		"args": args,
	}}
}

// LaunchOpenUrl — Launch open url
func LaunchOpenUrl(url string) Call {
	return Call{Action: "launch-open-url", Args: map[string]any{
		"url": url,
	}}
}

// LaunchOpenPath — Launch open path
func LaunchOpenPath(using string, path string) Call {
	return Call{Action: "launch-open-path", Args: map[string]any{
		"using": using,
		"path": path,
	}}
}

// LaunchFocusOrSpawn — Launch focus or spawn
func LaunchFocusOrSpawn(criteria string, argv string, timeoutMs string) Call {
	return Call{Action: "launch-focus-or-spawn", Args: map[string]any{
		"criteria": criteria,
		"argv": argv,
		"timeout_ms": timeoutMs,
	}}
}

// LauncherToggle — Launcher toggle
func LauncherToggle() Call {
	return Call{Action: "launcher-toggle", Args: map[string]any{
	}}
}

// LauncherShow — Launcher show
func LauncherShow() Call {
	return Call{Action: "launcher-show", Args: map[string]any{
	}}
}

// LauncherHide — Launcher hide
func LauncherHide() Call {
	return Call{Action: "launcher-hide", Args: map[string]any{
	}}
}

// LauncherSetQuery — Launcher set query
func LauncherSetQuery(query string) Call {
	return Call{Action: "launcher-set-query", Args: map[string]any{
		"query": query,
	}}
}

// LauncherGetState — Launcher get state
func LauncherGetState() Call {
	return Call{Action: "launcher-get-state", Args: map[string]any{
	}}
}

// LauncherRunCommand — Launcher run command
func LauncherRunCommand(argv string) Call {
	return Call{Action: "launcher-run-command", Args: map[string]any{
		"argv": argv,
	}}
}

// ClipboardGet — Clipboard get
func ClipboardGet(mimeAnswerBytes string, selection string) Call {
	return Call{Action: "clipboard-get", Args: map[string]any{
		"mime_answer_bytes": mimeAnswerBytes,
		"selection": selection,
	}}
}

// ClipboardPut — Clipboard put
func ClipboardPut(mime string, data string, sensitive bool, selection string) Call {
	return Call{Action: "clipboard-put", Args: map[string]any{
		"mime": mime,
		"data": data,
		"sensitive": sensitive,
		"selection": selection,
	}}
}

// ClipboardClear — Clipboard clear
func ClipboardClear(selection string) Call {
	return Call{Action: "clipboard-clear", Args: map[string]any{
		"selection": selection,
	}}
}

// ClipboardHistoryList — Clipboard history list
func ClipboardHistoryList(limit string) Call {
	return Call{Action: "clipboard-history-list", Args: map[string]any{
		"limit": limit,
	}}
}

// ClipboardHistoryClear — Clipboard history clear
func ClipboardHistoryClear() Call {
	return Call{Action: "clipboard-history-clear", Args: map[string]any{
	}}
}

// ScreenshotCapture — Screenshot capture
func ScreenshotCapture(source string, sink string, includeCursor string) Call {
	return Call{Action: "screenshot-capture", Args: map[string]any{
		"source": source,
		"sink": sink,
		"include_cursor": includeCursor,
	}}
}

// ScreenshotPickRegion — Screenshot pick region
func ScreenshotPickRegion(prompt string) Call {
	return Call{Action: "screenshot-pick-region", Args: map[string]any{
		"prompt": prompt,
	}}
}

// ColorPick — Color pick
func ColorPick() Call {
	return Call{Action: "color-pick", Args: map[string]any{
	}}
}

// ScreencastStart — Screencast start
func ScreencastStart(source string, sink string, fps string, includeCursorCastid string) Call {
	return Call{Action: "screencast-start", Args: map[string]any{
		"source": source,
		"sink": sink,
		"fps": fps,
		"include_cursor_castid": includeCursorCastid,
	}}
}

// ScreencastStop — Screencast stop
func ScreencastStop(cast string) Call {
	return Call{Action: "screencast-stop", Args: map[string]any{
		"cast": cast,
	}}
}

// ScreencastList — Screencast list
func ScreencastList() Call {
	return Call{Action: "screencast-list", Args: map[string]any{
	}}
}

// NotifySend — Notify send
func NotifySend(summary string, appId string, timeoutMs string, actions string, iconNotificationid string, body string, urgency string) Call {
	return Call{Action: "notify-send", Args: map[string]any{
		"summary": summary,
		"app_id": appId,
		"timeout_ms": timeoutMs,
		"actions": actions,
		"icon_notificationid": iconNotificationid,
		"body": body,
		"urgency": urgency,
	}}
}

// NotifyInvokeAction — Notify invoke action
func NotifyInvokeAction(id string, actionId string) Call {
	return Call{Action: "notify-invoke-action", Args: map[string]any{
		"id": id,
		"action_id": actionId,
	}}
}

// NotifyDismiss — Notify dismiss
func NotifyDismiss(id string) Call {
	return Call{Action: "notify-dismiss", Args: map[string]any{
		"id": id,
	}}
}

// NotifyDismissAll — Notify dismiss all
func NotifyDismissAll(filter string) Call {
	return Call{Action: "notify-dismiss-all", Args: map[string]any{
		"filter": filter,
	}}
}

// NotifyMarkRead — Notify mark read
func NotifyMarkRead(target string) Call {
	return Call{Action: "notify-mark-read", Args: map[string]any{
		"target": target,
	}}
}

// NotifySetDnd — Notify set dnd
func NotifySetDnd(on bool, until string) Call {
	return Call{Action: "notify-set-dnd", Args: map[string]any{
		"on": on,
		"until": until,
	}}
}

// NotifyList — Notify list
func NotifyList(includeHistory string, filter string) Call {
	return Call{Action: "notify-list", Args: map[string]any{
		"include_history": includeHistory,
		"filter": filter,
	}}
}

// NotifyHistoryClear — Notify history clear
func NotifyHistoryClear() Call {
	return Call{Action: "notify-history-clear", Args: map[string]any{
	}}
}

// NotifyHistoryDeleteOne — Notify history delete one
func NotifyHistoryDeleteOne(entryId string) Call {
	return Call{Action: "notify-history-delete-one", Args: map[string]any{
		"entry_id": entryId,
	}}
}

// NotifyToggleExpand — Notify toggle expand
func NotifyToggleExpand(id string) Call {
	return Call{Action: "notify-toggle-expand", Args: map[string]any{
		"id": id,
	}}
}

// NotifyToggleView — Notify toggle view
func NotifyToggleView() Call {
	return Call{Action: "notify-toggle-view", Args: map[string]any{
	}}
}

// NotifySearch — Notify search
func NotifySearch(query string) Call {
	return Call{Action: "notify-search", Args: map[string]any{
		"query": query,
	}}
}

// NotifyFilterSet — Notify filter set
func NotifyFilterSet(by string, value string, urgency string) Call {
	return Call{Action: "notify-filter-set", Args: map[string]any{
		"by": by,
		"value": value,
		"urgency": urgency,
	}}
}

// LayerSpawn — Layer spawn
func LayerSpawn(client string, layer string, anchor string, exclusiveZone string, keyboard string, output string) Call {
	return Call{Action: "layer-spawn", Args: map[string]any{
		"client": client,
		"layer": layer,
		"anchor": anchor,
		"exclusive_zone": exclusiveZone,
		"keyboard": keyboard,
		"output": output,
	}}
}

// LayerKill — Layer kill
func LayerKill(client string, teardown string) Call {
	return Call{Action: "layer-kill", Args: map[string]any{
		"client": client,
		"teardown": teardown,
	}}
}

// LayerList — Layer list
func LayerList() Call {
	return Call{Action: "layer-list", Args: map[string]any{
	}}
}

// PaneSessionNew — Pane session new
func PaneSessionNew(namePanesessionid string) Call {
	return Call{Action: "pane-session-new", Args: map[string]any{
		"name_panesessionid": namePanesessionid,
	}}
}

// PaneSessionKill — Pane session kill
func PaneSessionKill(session string) Call {
	return Call{Action: "pane-session-kill", Args: map[string]any{
		"session": session,
	}}
}

// PaneSessionList — Pane session list
func PaneSessionList() Call {
	return Call{Action: "pane-session-list", Args: map[string]any{
	}}
}

// PaneSessionDetail — Pane session detail
func PaneSessionDetail(session string) Call {
	return Call{Action: "pane-session-detail", Args: map[string]any{
		"session": session,
	}}
}

// PaneList — Pane list
func PaneList(session string) Call {
	return Call{Action: "pane-list", Args: map[string]any{
		"session": session,
	}}
}

// PaneSnapshot — Pane snapshot
func PaneSnapshot(pane string) Call {
	return Call{Action: "pane-snapshot", Args: map[string]any{
		"pane": pane,
	}}
}

// PaneSendKeys — Pane send keys
func PaneSendKeys(pane string, keys string) Call {
	return Call{Action: "pane-send-keys", Args: map[string]any{
		"pane": pane,
		"keys": keys,
	}}
}

// PaneSetInputPolicy — Pane set input policy
func PaneSetInputPolicy(pane string, policy string) Call {
	return Call{Action: "pane-set-input-policy", Args: map[string]any{
		"pane": pane,
		"policy": policy,
	}}
}

// PaneSubscriberCount — Pane subscriber count
func PaneSubscriberCount(pane string) Call {
	return Call{Action: "pane-subscriber-count", Args: map[string]any{
		"pane": pane,
	}}
}

// PaneRecordStart — Pane record start
func PaneRecordStart(pane string) Call {
	return Call{Action: "pane-record-start", Args: map[string]any{
		"pane": pane,
	}}
}

// PaneRecordStop — Pane record stop
func PaneRecordStop(pane string) Call {
	return Call{Action: "pane-record-stop", Args: map[string]any{
		"pane": pane,
	}}
}

// PaneRecordExport — Pane record export
func PaneRecordExport(pane string, path string) Call {
	return Call{Action: "pane-record-export", Args: map[string]any{
		"pane": pane,
		"path": path,
	}}
}

// PaneRecordStatus — Pane record status
func PaneRecordStatus(pane string) Call {
	return Call{Action: "pane-record-status", Args: map[string]any{
		"pane": pane,
	}}
}

// PaneBlocksList — Pane blocks list
func PaneBlocksList(pane string) Call {
	return Call{Action: "pane-blocks-list", Args: map[string]any{
		"pane": pane,
	}}
}

// PaneBlockAt — Pane block at
func PaneBlockAt(pane string, index int) Call {
	return Call{Action: "pane-block-at", Args: map[string]any{
		"pane": pane,
		"index": index,
	}}
}

// PaneBlocksStatus — Pane blocks status
func PaneBlocksStatus(pane string) Call {
	return Call{Action: "pane-blocks-status", Args: map[string]any{
		"pane": pane,
	}}
}

// PaneStats — Pane stats
func PaneStats(pane string) Call {
	return Call{Action: "pane-stats", Args: map[string]any{
		"pane": pane,
	}}
}

// PaneTop — Pane top
func PaneTop(limit string) Call {
	return Call{Action: "pane-top", Args: map[string]any{
		"limit": limit,
	}}
}

// PaneDaemonStatus — Pane daemon status
func PaneDaemonStatus() Call {
	return Call{Action: "pane-daemon-status", Args: map[string]any{
	}}
}

// PaneSystemResources — Pane system resources
func PaneSystemResources() Call {
	return Call{Action: "pane-system-resources", Args: map[string]any{
	}}
}

// PaneSocketInfo — Pane socket info
func PaneSocketInfo() Call {
	return Call{Action: "pane-socket-info", Args: map[string]any{
	}}
}

// PaneConfigGet — Pane config get
func PaneConfigGet() Call {
	return Call{Action: "pane-config-get", Args: map[string]any{
	}}
}

// PaneConfigSet — Pane config set
func PaneConfigSet(yaml string) Call {
	return Call{Action: "pane-config-set", Args: map[string]any{
		"yaml": yaml,
	}}
}

// PaneReloadConfig — Pane reload config
func PaneReloadConfig() Call {
	return Call{Action: "pane-reload-config", Args: map[string]any{
	}}
}

// BrowserOpen — Browser open
func BrowserOpen(urlBrowserid string) Call {
	return Call{Action: "browser-open", Args: map[string]any{
		"url_browserid": urlBrowserid,
	}}
}

// BrowserClose — Browser close
func BrowserClose(id string) Call {
	return Call{Action: "browser-close", Args: map[string]any{
		"id": id,
	}}
}

// BrowserFocus — Browser focus
func BrowserFocus(id string) Call {
	return Call{Action: "browser-focus", Args: map[string]any{
		"id": id,
	}}
}

// BrowserList — Browser list
func BrowserList() Call {
	return Call{Action: "browser-list", Args: map[string]any{
	}}
}

// BrowserMove — Browser move
func BrowserMove(id string, position string) Call {
	return Call{Action: "browser-move", Args: map[string]any{
		"id": id,
		"position": position,
	}}
}

// BrowserResize — Browser resize
func BrowserResize(id string, size string) Call {
	return Call{Action: "browser-resize", Args: map[string]any{
		"id": id,
		"size": size,
	}}
}

// BrowserNavigate — Browser navigate
func BrowserNavigate(id string, url string) Call {
	return Call{Action: "browser-navigate", Args: map[string]any{
		"id": id,
		"url": url,
	}}
}

// BrowserSnap — Browser snap
func BrowserSnap(id string, zone string) Call {
	return Call{Action: "browser-snap", Args: map[string]any{
		"id": id,
		"zone": zone,
	}}
}

// BrowserSnapshot — Browser snapshot
func BrowserSnapshot(id string) Call {
	return Call{Action: "browser-snapshot", Args: map[string]any{
		"id": id,
	}}
}

// BrowserSnapshotGet — Browser snapshot get
func BrowserSnapshotGet(id string) Call {
	return Call{Action: "browser-snapshot-get", Args: map[string]any{
		"id": id,
	}}
}

// BrowserSetDom — Browser set dom
func BrowserSetDom(id string, dom string) Call {
	return Call{Action: "browser-set-dom", Args: map[string]any{
		"id": id,
		"dom": dom,
	}}
}

// ThemeSelect — Theme select
func ThemeSelect(theme string) Call {
	return Call{Action: "theme-select", Args: map[string]any{
		"theme": theme,
	}}
}

// ThemeSetAppearance — Theme set appearance
func ThemeSetAppearance(appearance string, dark string, auto string) Call {
	return Call{Action: "theme-set-appearance", Args: map[string]any{
		"appearance": appearance,
		"dark": dark,
		"auto": auto,
	}}
}

// ThemeSetFontScale — Theme set font scale
func ThemeSetFontScale(scale int) Call {
	return Call{Action: "theme-set-font-scale", Args: map[string]any{
		"scale": scale,
	}}
}

// ThemeReload — Theme reload
func ThemeReload() Call {
	return Call{Action: "theme-reload", Args: map[string]any{
	}}
}

// ThemeGet — Theme get
func ThemeGet(themePerLeafProvenance string) Call {
	return Call{Action: "theme-get", Args: map[string]any{
		"theme_per_leaf_provenance": themePerLeafProvenance,
	}}
}

// ScreenTransitionRun — Screen transition run
func ScreenTransitionRun(delayMs string) Call {
	return Call{Action: "screen-transition-run", Args: map[string]any{
		"delay_ms": delayMs,
	}}
}

// AudioSetVolume — Audio set volume
func AudioSetVolume(target string, sink string) Call {
	return Call{Action: "audio-set-volume", Args: map[string]any{
		"target": target,
		"sink": sink,
	}}
}

// AudioSetMute — Audio set mute
func AudioSetMute(on bool, sink string) Call {
	return Call{Action: "audio-set-mute", Args: map[string]any{
		"on": on,
		"sink": sink,
	}}
}

// AudioSetDefaultSink — Audio set default sink
func AudioSetDefaultSink(sink string) Call {
	return Call{Action: "audio-set-default-sink", Args: map[string]any{
		"sink": sink,
	}}
}

// AudioListSinks — Audio list sinks
func AudioListSinks() Call {
	return Call{Action: "audio-list-sinks", Args: map[string]any{
	}}
}

// ScreensaverStart — Screensaver start
func ScreensaverStart() Call {
	return Call{Action: "screensaver-start", Args: map[string]any{
	}}
}

// TrashEmpty — Trash empty
func TrashEmpty(confirm string) Call {
	return Call{Action: "trash-empty", Args: map[string]any{
		"confirm": confirm,
	}}
}

// VolumeEjectAll — Volume eject all
func VolumeEjectAll() Call {
	return Call{Action: "volume-eject-all", Args: map[string]any{
	}}
}

// OverviewSet — Overview set
func OverviewSet(on bool) Call {
	return Call{Action: "overview-set", Args: map[string]any{
		"on": on,
	}}
}

// ConfigReload — Config reload
func ConfigReload(path string) Call {
	return Call{Action: "config-reload", Args: map[string]any{
		"path": path,
	}}
}

// ConfigGet — Config get
func ConfigGet(key string, includeProvenance string) Call {
	return Call{Action: "config-get", Args: map[string]any{
		"key": key,
		"include_provenance": includeProvenance,
	}}
}

// ConfigSet — Config set
func ConfigSet(key string, value string, apply string, live string) Call {
	return Call{Action: "config-set", Args: map[string]any{
		"key": key,
		"value": value,
		"apply": apply,
		"live": live,
	}}
}

// StateQuery — State query
func StateQuery(domain string) Call {
	return Call{Action: "state-query", Args: map[string]any{
		"domain": domain,
	}}
}

// EventsSubscribe — Events subscribe
func EventsSubscribe(since string, filter string) Call {
	return Call{Action: "events-subscribe", Args: map[string]any{
		"since": since,
		"filter": filter,
	}}
}

// CompositorQuit — Compositor quit
func CompositorQuit(confirm string, teardown string) Call {
	return Call{Action: "compositor-quit", Args: map[string]any{
		"confirm": confirm,
		"teardown": teardown,
	}}
}

// DesktopPlan — Desktop plan
func DesktopPlan(spec string) Call {
	return Call{Action: "desktop-plan", Args: map[string]any{
		"spec": spec,
	}}
}

// DesktopApply — Desktop apply
func DesktopApply(spec string, policy string, mode string) Call {
	return Call{Action: "desktop-apply", Args: map[string]any{
		"spec": spec,
		"policy": policy,
		"mode": mode,
	}}
}

// DesktopTick — Desktop tick
func DesktopTick(tickoutcome string) Call {
	return Call{Action: "desktop-tick", Args: map[string]any{
		"tickoutcome": tickoutcome,
	}}
}

// DesktopAttest — Desktop attest
func DesktopAttest(receiptDesktoppayload string) Call {
	return Call{Action: "desktop-attest", Args: map[string]any{
		"receipt_desktoppayload": receiptDesktoppayload,
	}}
}

// DesktopHealth — Desktop health
func DesktopHealth() Call {
	return Call{Action: "desktop-health", Args: map[string]any{
	}}
}

// DesktopVersion — Desktop version
func DesktopVersion() Call {
	return Call{Action: "desktop-version", Args: map[string]any{
	}}
}

