// Generated by saihai-forge (go) — DO NOT EDIT
// Source of truth: saihai/catalog/desktop.saihai.lisp
// Verify: saihai-forge check   (fails on any drift)

package saihai

type Param struct {
	Name string
	Kind string
	Required bool
}

type ActionMeta struct {
	ID string
	Class string
	Auth string
	Params []Param
}

var Actions = map[string]ActionMeta{
	"window-focus": {ID: "window-focus", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-focus-direction": {ID: "window-focus-direction", Class: "converging", Auth: "l1", Params: []Param{{Name: "direction", Kind: "direction", Required: true}, {Name: "wrap", Kind: "bool", Required: false}, }},
	"window-move": {ID: "window-move", Class: "converging", Auth: "l2", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "x", Kind: "int", Required: true}, {Name: "y", Kind: "int", Required: true}, }},
	"window-resize": {ID: "window-resize", Class: "converging", Auth: "l2", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "width", Kind: "int", Required: true}, {Name: "height", Kind: "int", Required: true}, }},
	"window-close": {ID: "window-close", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-set-fullscreen": {ID: "window-set-fullscreen", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"window-set-maximized": {ID: "window-set-maximized", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"window-set-floating": {ID: "window-set-floating", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"window-raise": {ID: "window-raise", Class: "blind", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-lower": {ID: "window-lower", Class: "blind", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"window-to-workspace": {ID: "window-to-workspace", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "workspace", Kind: "selector", Required: true}, {Name: "follow", Kind: "bool", Required: false}, }},
	"window-to-output": {ID: "window-to-output", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "output", Kind: "selector", Required: true}, }},
	"window-swap": {ID: "window-swap", Class: "converging", Auth: "l1", Params: []Param{{Name: "target", Kind: "selector", Required: true}, {Name: "other", Kind: "selector", Required: true}, }},
	"window-list": {ID: "window-list", Class: "read", Auth: "l0", Params: []Param{{Name: "filter", Kind: "str", Required: false}, }},
	"window-get": {ID: "window-get", Class: "read", Auth: "l0", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"workspace-focus": {ID: "workspace-focus", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: true}, }},
	"workspace-cycle": {ID: "workspace-cycle", Class: "converging", Auth: "l1", Params: []Param{{Name: "direction", Kind: "direction", Required: true}, {Name: "wrap", Kind: "bool", Required: false}, }},
	"workspace-create": {ID: "workspace-create", Class: "converging", Auth: "l1", Params: []Param{{Name: "name", Kind: "str", Required: true}, {Name: "output", Kind: "selector", Required: false}, }},
	"workspace-destroy": {ID: "workspace-destroy", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: true}, }},
	"workspace-rename": {ID: "workspace-rename", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: true}, {Name: "name", Kind: "str", Required: true}, }},
	"workspace-move-to-output": {ID: "workspace-move-to-output", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: true}, {Name: "output", Kind: "selector", Required: true}, }},
	"workspace-list": {ID: "workspace-list", Class: "read", Auth: "l0", Params: []Param{}},
	"layout-set": {ID: "layout-set", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: true}, {Name: "layout", Kind: "str", Required: true}, }},
	"layout-set-orientation": {ID: "layout-set-orientation", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: true}, {Name: "orientation", Kind: "str", Required: true}, }},
	"layout-set-gaps": {ID: "layout-set-gaps", Class: "converging", Auth: "l1", Params: []Param{{Name: "inner", Kind: "int", Required: true}, {Name: "outer", Kind: "int", Required: true}, }},
	"layout-equalize": {ID: "layout-equalize", Class: "converging", Auth: "l1", Params: []Param{{Name: "workspace", Kind: "selector", Required: false}, }},
	"layout-get": {ID: "layout-get", Class: "read", Auth: "l0", Params: []Param{{Name: "workspace", Kind: "selector", Required: true}, }},
	"output-set-enabled": {ID: "output-set-enabled", Class: "converging", Auth: "l2", Params: []Param{{Name: "output", Kind: "selector", Required: true}, {Name: "on", Kind: "bool", Required: true}, }},
	"output-set-mode": {ID: "output-set-mode", Class: "converging", Auth: "l2", Params: []Param{{Name: "output", Kind: "selector", Required: true}, {Name: "width", Kind: "int", Required: true}, {Name: "height", Kind: "int", Required: true}, {Name: "refresh", Kind: "int", Required: false}, }},
	"output-set-scale": {ID: "output-set-scale", Class: "converging", Auth: "l2", Params: []Param{{Name: "output", Kind: "selector", Required: true}, {Name: "scale", Kind: "int", Required: true}, }},
	"output-set-transform": {ID: "output-set-transform", Class: "converging", Auth: "l2", Params: []Param{{Name: "output", Kind: "selector", Required: true}, {Name: "transform", Kind: "str", Required: true}, }},
	"output-set-position": {ID: "output-set-position", Class: "converging", Auth: "l2", Params: []Param{{Name: "output", Kind: "selector", Required: true}, {Name: "x", Kind: "int", Required: true}, {Name: "y", Kind: "int", Required: true}, }},
	"output-list": {ID: "output-list", Class: "read", Auth: "l0", Params: []Param{}},
	"input-set-repeat": {ID: "input-set-repeat", Class: "converging", Auth: "l1", Params: []Param{{Name: "rate", Kind: "int", Required: true}, {Name: "delay", Kind: "int", Required: true}, }},
	"input-set-layout": {ID: "input-set-layout", Class: "converging", Auth: "l1", Params: []Param{{Name: "layout", Kind: "str", Required: true}, {Name: "variant", Kind: "str", Required: false}, }},
	"input-bind": {ID: "input-bind", Class: "converging", Auth: "l1", Params: []Param{{Name: "chord", Kind: "str", Required: true}, {Name: "action", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"input-unbind": {ID: "input-unbind", Class: "converging", Auth: "l1", Params: []Param{{Name: "chord", Kind: "str", Required: true}, {Name: "mode", Kind: "str", Required: false}, }},
	"input-set-mode": {ID: "input-set-mode", Class: "converging", Auth: "l1", Params: []Param{{Name: "mode", Kind: "str", Required: true}, }},
	"input-send-keys": {ID: "input-send-keys", Class: "blind", Auth: "l3", Params: []Param{{Name: "keys", Kind: "str", Required: true}, {Name: "target", Kind: "selector", Required: false}, }},
	"input-list-bindings": {ID: "input-list-bindings", Class: "read", Auth: "l0", Params: []Param{{Name: "mode", Kind: "str", Required: false}, }},
	"focus-set-policy": {ID: "focus-set-policy", Class: "converging", Auth: "l1", Params: []Param{{Name: "policy", Kind: "str", Required: true}, }},
	"focus-get": {ID: "focus-get", Class: "read", Auth: "l0", Params: []Param{}},
	"session-lock": {ID: "session-lock", Class: "converging", Auth: "l1", Params: []Param{}},
	"session-unlock": {ID: "session-unlock", Class: "converging", Auth: "l1", Params: []Param{}},
	"session-logout": {ID: "session-logout", Class: "converging", Auth: "l1", Params: []Param{}},
	"session-suspend": {ID: "session-suspend", Class: "blind", Auth: "l2", Params: []Param{}},
	"session-reboot": {ID: "session-reboot", Class: "blind", Auth: "l2", Params: []Param{}},
	"session-poweroff": {ID: "session-poweroff", Class: "blind", Auth: "l2", Params: []Param{}},
	"session-switch-vt": {ID: "session-switch-vt", Class: "converging", Auth: "l2", Params: []Param{{Name: "vt", Kind: "int", Required: true}, }},
	"session-get": {ID: "session-get", Class: "read", Auth: "l0", Params: []Param{}},
	"login-authenticate": {ID: "login-authenticate", Class: "converging", Auth: "l2", Params: []Param{{Name: "user", Kind: "str", Required: true}, }},
	"login-start-session": {ID: "login-start-session", Class: "converging", Auth: "l2", Params: []Param{{Name: "user", Kind: "str", Required: true}, {Name: "session", Kind: "str", Required: false}, }},
	"login-end-session": {ID: "login-end-session", Class: "converging", Auth: "l2", Params: []Param{{Name: "user", Kind: "str", Required: true}, }},
	"login-switch-user": {ID: "login-switch-user", Class: "converging", Auth: "l2", Params: []Param{{Name: "user", Kind: "str", Required: true}, }},
	"login-list-sessions": {ID: "login-list-sessions", Class: "read", Auth: "l0", Params: []Param{}},
	"seat-get": {ID: "seat-get", Class: "read", Auth: "l0", Params: []Param{}},
	"launch-spawn": {ID: "launch-spawn", Class: "converging", Auth: "l1", Params: []Param{{Name: "command", Kind: "str", Required: true}, {Name: "workspace", Kind: "selector", Required: false}, }},
	"launch-focus-or-spawn": {ID: "launch-focus-or-spawn", Class: "converging", Auth: "l1", Params: []Param{{Name: "criteria", Kind: "selector", Required: true}, {Name: "command", Kind: "str", Required: true}, }},
	"clipboard-get": {ID: "clipboard-get", Class: "read", Auth: "l1", Params: []Param{{Name: "selection", Kind: "str", Required: false}, }},
	"clipboard-put": {ID: "clipboard-put", Class: "converging", Auth: "l1", Params: []Param{{Name: "content", Kind: "str", Required: true}, {Name: "selection", Kind: "str", Required: false}, }},
	"clipboard-clear": {ID: "clipboard-clear", Class: "converging", Auth: "l1", Params: []Param{{Name: "selection", Kind: "str", Required: false}, }},
	"capture-screenshot": {ID: "capture-screenshot", Class: "blind", Auth: "l2", Params: []Param{{Name: "target", Kind: "selector", Required: false}, {Name: "path", Kind: "str", Required: false}, }},
	"capture-screencast-start": {ID: "capture-screencast-start", Class: "blind", Auth: "l2", Params: []Param{{Name: "target", Kind: "selector", Required: false}, }},
	"capture-screencast-stop": {ID: "capture-screencast-stop", Class: "blind", Auth: "l2", Params: []Param{}},
	"notify-send": {ID: "notify-send", Class: "blind", Auth: "l0", Params: []Param{{Name: "summary", Kind: "str", Required: true}, {Name: "body", Kind: "str", Required: false}, {Name: "urgency", Kind: "str", Required: false}, }},
	"notify-dismiss": {ID: "notify-dismiss", Class: "blind", Auth: "l0", Params: []Param{{Name: "target", Kind: "selector", Required: true}, }},
	"theme-select": {ID: "theme-select", Class: "converging", Auth: "l1", Params: []Param{{Name: "name", Kind: "str", Required: true}, }},
	"theme-reload": {ID: "theme-reload", Class: "converging", Auth: "l1", Params: []Param{}},
	"theme-get": {ID: "theme-get", Class: "read", Auth: "l0", Params: []Param{}},
	"system-reload-config": {ID: "system-reload-config", Class: "converging", Auth: "l1", Params: []Param{}},
	"system-get-state": {ID: "system-get-state", Class: "read", Auth: "l0", Params: []Param{}},
	"system-version": {ID: "system-version", Class: "read", Auth: "l0", Params: []Param{}},
}

type Call struct {
	Action string
	Args map[string]any
}

// WindowFocus — Give a window keyboard focus
func WindowFocus(target string) Call {
	return Call{Action: "window-focus", Args: map[string]any{
		"target": target,
	}}
}

// WindowFocusDirection — Move focus spatially
func WindowFocusDirection(direction string, wrap bool) Call {
	return Call{Action: "window-focus-direction", Args: map[string]any{
		"direction": direction,
		"wrap": wrap,
	}}
}

// WindowMove — Move a window to a position
func WindowMove(target string, x int, y int) Call {
	return Call{Action: "window-move", Args: map[string]any{
		"target": target,
		"x": x,
		"y": y,
	}}
}

// WindowResize — Resize a window
func WindowResize(target string, width int, height int) Call {
	return Call{Action: "window-resize", Args: map[string]any{
		"target": target,
		"width": width,
		"height": height,
	}}
}

// WindowClose — Ask a window to close
func WindowClose(target string) Call {
	return Call{Action: "window-close", Args: map[string]any{
		"target": target,
	}}
}

// WindowSetFullscreen — Set or clear fullscreen
func WindowSetFullscreen(target string, on bool) Call {
	return Call{Action: "window-set-fullscreen", Args: map[string]any{
		"target": target,
		"on": on,
	}}
}

// WindowSetMaximized — Set or clear maximized
func WindowSetMaximized(target string, on bool) Call {
	return Call{Action: "window-set-maximized", Args: map[string]any{
		"target": target,
		"on": on,
	}}
}

// WindowSetFloating — Float or tile a window
func WindowSetFloating(target string, on bool) Call {
	return Call{Action: "window-set-floating", Args: map[string]any{
		"target": target,
		"on": on,
	}}
}

// WindowRaise — Raise a window in the stacking order
func WindowRaise(target string) Call {
	return Call{Action: "window-raise", Args: map[string]any{
		"target": target,
	}}
}

// WindowLower — Lower a window in the stacking order
func WindowLower(target string) Call {
	return Call{Action: "window-lower", Args: map[string]any{
		"target": target,
	}}
}

// WindowToWorkspace — Send a window to a workspace
func WindowToWorkspace(target string, workspace string, follow bool) Call {
	return Call{Action: "window-to-workspace", Args: map[string]any{
		"target": target,
		"workspace": workspace,
		"follow": follow,
	}}
}

// WindowToOutput — Send a window to another output
func WindowToOutput(target string, output string) Call {
	return Call{Action: "window-to-output", Args: map[string]any{
		"target": target,
		"output": output,
	}}
}

// WindowSwap — Swap two windows in the layout
func WindowSwap(target string, other string) Call {
	return Call{Action: "window-swap", Args: map[string]any{
		"target": target,
		"other": other,
	}}
}

// WindowList — List managed windows
func WindowList(filter string) Call {
	return Call{Action: "window-list", Args: map[string]any{
		"filter": filter,
	}}
}

// WindowGet — Read one window's full state
func WindowGet(target string) Call {
	return Call{Action: "window-get", Args: map[string]any{
		"target": target,
	}}
}

// WorkspaceFocus — Switch to a workspace
func WorkspaceFocus(workspace string) Call {
	return Call{Action: "workspace-focus", Args: map[string]any{
		"workspace": workspace,
	}}
}

// WorkspaceCycle — Move to the next or previous workspace
func WorkspaceCycle(direction string, wrap bool) Call {
	return Call{Action: "workspace-cycle", Args: map[string]any{
		"direction": direction,
		"wrap": wrap,
	}}
}

// WorkspaceCreate — Create a workspace
func WorkspaceCreate(name string, output string) Call {
	return Call{Action: "workspace-create", Args: map[string]any{
		"name": name,
		"output": output,
	}}
}

// WorkspaceDestroy — Destroy a workspace
func WorkspaceDestroy(workspace string) Call {
	return Call{Action: "workspace-destroy", Args: map[string]any{
		"workspace": workspace,
	}}
}

// WorkspaceRename — Rename a workspace
func WorkspaceRename(workspace string, name string) Call {
	return Call{Action: "workspace-rename", Args: map[string]any{
		"workspace": workspace,
		"name": name,
	}}
}

// WorkspaceMoveToOutput — Move a workspace to an output
func WorkspaceMoveToOutput(workspace string, output string) Call {
	return Call{Action: "workspace-move-to-output", Args: map[string]any{
		"workspace": workspace,
		"output": output,
	}}
}

// WorkspaceList — List workspaces
func WorkspaceList() Call {
	return Call{Action: "workspace-list", Args: map[string]any{
	}}
}

// LayoutSet — Set a workspace's layout
func LayoutSet(workspace string, layout string) Call {
	return Call{Action: "layout-set", Args: map[string]any{
		"workspace": workspace,
		"layout": layout,
	}}
}

// LayoutSetOrientation — Set the split orientation
func LayoutSetOrientation(workspace string, orientation string) Call {
	return Call{Action: "layout-set-orientation", Args: map[string]any{
		"workspace": workspace,
		"orientation": orientation,
	}}
}

// LayoutSetGaps — Set inner and outer gaps
func LayoutSetGaps(inner int, outer int) Call {
	return Call{Action: "layout-set-gaps", Args: map[string]any{
		"inner": inner,
		"outer": outer,
	}}
}

// LayoutEqualize — Equalize sibling sizes
func LayoutEqualize(workspace string) Call {
	return Call{Action: "layout-equalize", Args: map[string]any{
		"workspace": workspace,
	}}
}

// LayoutGet — Read a workspace's layout
func LayoutGet(workspace string) Call {
	return Call{Action: "layout-get", Args: map[string]any{
		"workspace": workspace,
	}}
}

// OutputSetEnabled — Enable or disable an output
func OutputSetEnabled(output string, on bool) Call {
	return Call{Action: "output-set-enabled", Args: map[string]any{
		"output": output,
		"on": on,
	}}
}

// OutputSetMode — Set an output's resolution and refresh
func OutputSetMode(output string, width int, height int, refresh int) Call {
	return Call{Action: "output-set-mode", Args: map[string]any{
		"output": output,
		"width": width,
		"height": height,
		"refresh": refresh,
	}}
}

// OutputSetScale — Set an output's scale factor
func OutputSetScale(output string, scale int) Call {
	return Call{Action: "output-set-scale", Args: map[string]any{
		"output": output,
		"scale": scale,
	}}
}

// OutputSetTransform — Rotate or flip an output
func OutputSetTransform(output string, transform string) Call {
	return Call{Action: "output-set-transform", Args: map[string]any{
		"output": output,
		"transform": transform,
	}}
}

// OutputSetPosition — Place an output in the layout
func OutputSetPosition(output string, x int, y int) Call {
	return Call{Action: "output-set-position", Args: map[string]any{
		"output": output,
		"x": x,
		"y": y,
	}}
}

// OutputList — List outputs and their modes
func OutputList() Call {
	return Call{Action: "output-list", Args: map[string]any{
	}}
}

// InputSetRepeat — Set key repeat rate and delay
func InputSetRepeat(rate int, delay int) Call {
	return Call{Action: "input-set-repeat", Args: map[string]any{
		"rate": rate,
		"delay": delay,
	}}
}

// InputSetLayout — Set the keyboard layout
func InputSetLayout(layout string, variant string) Call {
	return Call{Action: "input-set-layout", Args: map[string]any{
		"layout": layout,
		"variant": variant,
	}}
}

// InputBind — Bind a key chord to an action
func InputBind(chord string, action string, mode string) Call {
	return Call{Action: "input-bind", Args: map[string]any{
		"chord": chord,
		"action": action,
		"mode": mode,
	}}
}

// InputUnbind — Remove a key binding
func InputUnbind(chord string, mode string) Call {
	return Call{Action: "input-unbind", Args: map[string]any{
		"chord": chord,
		"mode": mode,
	}}
}

// InputSetMode — Switch the active keymap mode
func InputSetMode(mode string) Call {
	return Call{Action: "input-set-mode", Args: map[string]any{
		"mode": mode,
	}}
}

// InputSendKeys — Inject a synthetic key sequence
func InputSendKeys(keys string, target string) Call {
	return Call{Action: "input-send-keys", Args: map[string]any{
		"keys": keys,
		"target": target,
	}}
}

// InputListBindings — List active key bindings
func InputListBindings(mode string) Call {
	return Call{Action: "input-list-bindings", Args: map[string]any{
		"mode": mode,
	}}
}

// FocusSetPolicy — Set the focus-follows-mouse policy
func FocusSetPolicy(policy string) Call {
	return Call{Action: "focus-set-policy", Args: map[string]any{
		"policy": policy,
	}}
}

// FocusGet — Read what currently has focus
func FocusGet() Call {
	return Call{Action: "focus-get", Args: map[string]any{
	}}
}

// SessionLock — Lock the session
func SessionLock() Call {
	return Call{Action: "session-lock", Args: map[string]any{
	}}
}

// SessionUnlock — Unlock the session after authentication
func SessionUnlock() Call {
	return Call{Action: "session-unlock", Args: map[string]any{
	}}
}

// SessionLogout — End the session
func SessionLogout() Call {
	return Call{Action: "session-logout", Args: map[string]any{
	}}
}

// SessionSuspend — Suspend the machine
func SessionSuspend() Call {
	return Call{Action: "session-suspend", Args: map[string]any{
	}}
}

// SessionReboot — Reboot the machine
func SessionReboot() Call {
	return Call{Action: "session-reboot", Args: map[string]any{
	}}
}

// SessionPoweroff — Power the machine off
func SessionPoweroff() Call {
	return Call{Action: "session-poweroff", Args: map[string]any{
	}}
}

// SessionSwitchVt — Switch to another virtual terminal
func SessionSwitchVt(vt int) Call {
	return Call{Action: "session-switch-vt", Args: map[string]any{
		"vt": vt,
	}}
}

// SessionGet — Read session state
func SessionGet() Call {
	return Call{Action: "session-get", Args: map[string]any{
	}}
}

// LoginAuthenticate — Authenticate a user against PAM
func LoginAuthenticate(user string) Call {
	return Call{Action: "login-authenticate", Args: map[string]any{
		"user": user,
	}}
}

// LoginStartSession — Start a session for an authenticated user
func LoginStartSession(user string, session string) Call {
	return Call{Action: "login-start-session", Args: map[string]any{
		"user": user,
		"session": session,
	}}
}

// LoginEndSession — End a session and close its PAM handle
func LoginEndSession(user string) Call {
	return Call{Action: "login-end-session", Args: map[string]any{
		"user": user,
	}}
}

// LoginSwitchUser — Switch to another user's session
func LoginSwitchUser(user string) Call {
	return Call{Action: "login-switch-user", Args: map[string]any{
		"user": user,
	}}
}

// LoginListSessions — List active sessions
func LoginListSessions() Call {
	return Call{Action: "login-list-sessions", Args: map[string]any{
	}}
}

// SeatGet — Read the seat's identity and devices
func SeatGet() Call {
	return Call{Action: "seat-get", Args: map[string]any{
	}}
}

// LaunchSpawn — Spawn a program
func LaunchSpawn(command string, workspace string) Call {
	return Call{Action: "launch-spawn", Args: map[string]any{
		"command": command,
		"workspace": workspace,
	}}
}

// LaunchFocusOrSpawn — Focus a program's window, or spawn it
func LaunchFocusOrSpawn(criteria string, command string) Call {
	return Call{Action: "launch-focus-or-spawn", Args: map[string]any{
		"criteria": criteria,
		"command": command,
	}}
}

// ClipboardGet — Read the clipboard
func ClipboardGet(selection string) Call {
	return Call{Action: "clipboard-get", Args: map[string]any{
		"selection": selection,
	}}
}

// ClipboardPut — Write the clipboard
func ClipboardPut(content string, selection string) Call {
	return Call{Action: "clipboard-put", Args: map[string]any{
		"content": content,
		"selection": selection,
	}}
}

// ClipboardClear — Clear the clipboard
func ClipboardClear(selection string) Call {
	return Call{Action: "clipboard-clear", Args: map[string]any{
		"selection": selection,
	}}
}

// CaptureScreenshot — Capture a screenshot
func CaptureScreenshot(target string, path string) Call {
	return Call{Action: "capture-screenshot", Args: map[string]any{
		"target": target,
		"path": path,
	}}
}

// CaptureScreencastStart — Start a screencast
func CaptureScreencastStart(target string) Call {
	return Call{Action: "capture-screencast-start", Args: map[string]any{
		"target": target,
	}}
}

// CaptureScreencastStop — Stop a screencast
func CaptureScreencastStop() Call {
	return Call{Action: "capture-screencast-stop", Args: map[string]any{
	}}
}

// NotifySend — Post a notification
func NotifySend(summary string, body string, urgency string) Call {
	return Call{Action: "notify-send", Args: map[string]any{
		"summary": summary,
		"body": body,
		"urgency": urgency,
	}}
}

// NotifyDismiss — Dismiss a notification
func NotifyDismiss(target string) Call {
	return Call{Action: "notify-dismiss", Args: map[string]any{
		"target": target,
	}}
}

// ThemeSelect — Select the active theme
func ThemeSelect(name string) Call {
	return Call{Action: "theme-select", Args: map[string]any{
		"name": name,
	}}
}

// ThemeReload — Re-read the active theme's artifacts
func ThemeReload() Call {
	return Call{Action: "theme-reload", Args: map[string]any{
	}}
}

// ThemeGet — Read the active theme
func ThemeGet() Call {
	return Call{Action: "theme-get", Args: map[string]any{
	}}
}

// SystemReloadConfig — Re-read the desktop configuration
func SystemReloadConfig() Call {
	return Call{Action: "system-reload-config", Args: map[string]any{
	}}
}

// SystemGetState — Read the whole observable desktop state
func SystemGetState() Call {
	return Call{Action: "system-get-state", Args: map[string]any{
	}}
}

// SystemVersion — Read the desktop's version and backend
func SystemVersion() Call {
	return Call{Action: "system-version", Args: map[string]any{
	}}
}

