// Generated by saihai-forge (go conformance) — DO NOT EDIT
//
// Compares this package against corpus.json, emitted from the Rust
// reference. Different code paths, so an emitter bug is detectable.

package saihai

import (
	"encoding/json"
	"os"
	"testing"
)

type corpusParam struct {
	Name string `json:"name"`
	Kind string `json:"kind"`
	Required bool `json:"required"`
}

type corpusAction struct {
	ID string `json:"id"`
	Kind string `json:"kind"`
	Class string `json:"class"`
	Auth string `json:"auth"`
	Params []corpusParam `json:"params"`
	Observed int `json:"observed"`
}

type corpusFile struct {
	Actions []corpusAction `json:"actions"`
	Count int `json:"count"`
}

func TestConformance(t *testing.T) {
	b, err := os.ReadFile("corpus.json")
	if err != nil {
		t.Fatalf("corpus.json: %v", err)
	}
	var c corpusFile
	if err := json.Unmarshal(b, &c); err != nil {
		t.Fatalf("corpus.json: %v", err)
	}
	if c.Count == 0 {
		t.Fatal("corpus is empty")
	}
	if len(Actions) != c.Count {
		t.Errorf("client has %d actions, corpus has %d", len(Actions), c.Count)
	}
	for _, a := range c.Actions {
		m, ok := Actions[a.ID]
		if !ok {
			t.Errorf("%s: missing from client", a.ID)
			continue
		}
		if m.Class != a.Class {
			t.Errorf("%s class = %s, want %s", a.ID, m.Class, a.Class)
		}
		if m.Auth != a.Auth {
			t.Errorf("%s auth = %s, want %s", a.ID, m.Auth, a.Auth)
		}
		if len(m.Params) != len(a.Params) {
			t.Errorf("%s has %d params, want %d", a.ID, len(m.Params), len(a.Params))
			continue
		}
		for i, p := range a.Params {
			if m.Params[i].Name != p.Name || m.Params[i].Required != p.Required {
				t.Errorf("%s param %d = %+v, want %+v", a.ID, i, m.Params[i], p)
			}
		}
		blind := a.Class == "blind"
		if blind != (a.Kind == "mutate" && a.Observed == 0) {
			t.Errorf("%s: blind/observed disagree", a.ID)
		}
	}
}
