//! `saihai-forge` — generates every surface from the action catalog.
//!
//! The catalog is the source. From it come the Rust `Verb` enum, the SDK for
//! each target language, the conformance corpus, and each language's generated
//! test. Nothing downstream may invent a verb.
//!
//! ## What makes the generated tests non-tautological
//!
//! A generator that emits both the client and the test checking it writes a
//! test that passes by construction. The way out, proven in `pente`, is a
//! **shared conformance corpus**: one JSON document serialised from the Rust
//! reference, which each language's test loads and compares its own generated
//! surface against. Corpus and client travel through different code paths, so a
//! per-language emitter bug is detectable.
//!
//! ## The coverage claim, stated honestly
//!
//! Rust is the reference — it produces the corpus — so a Rust conformance suite
//! would compare an encoder with its own output and could not fail. Only the
//! three non-Rust columns are genuine cross-implementation checks, and
//! [`Coverage`] keeps that distinction as a type rather than a caveat in prose.

pub mod reconcile;

use std::fmt::Write as _;

use saihai_spec::{Catalog, Class, Kind, ParamKind};

/// A language the desktop API is published to.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Lang {
    TypeScript,
    Python,
    Go,
}

impl Lang {
    pub const ALL: [Self; 3] = [Self::TypeScript, Self::Python, Self::Go];

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::TypeScript => "typescript",
            Self::Python => "python",
            Self::Go => "go",
        }
    }

    #[must_use]
    pub const fn client_file(self) -> &'static str {
        match self {
            Self::TypeScript => "client.ts",
            Self::Python => "client.py",
            Self::Go => "client.go",
        }
    }

    #[must_use]
    pub const fn test_file(self) -> &'static str {
        match self {
            Self::TypeScript => "conformance.test.ts",
            Self::Python => "test_conformance.py",
            Self::Go => "conformance_test.go",
        }
    }

    /// The SDK: one typed method per action, plus the metadata a caller needs
    /// to respect authority and observability without consulting a document.
    #[must_use]
    pub fn render_client(self, cat: &Catalog) -> String {
        match self {
            Self::TypeScript => ts_client(cat),
            Self::Python => py_client(cat),
            Self::Go => go_client(cat),
        }
    }

    #[must_use]
    pub fn render_test(self) -> String {
        match self {
            Self::TypeScript => ts_test(),
            Self::Python => py_test(),
            Self::Go => go_test(),
        }
    }

    #[must_use]
    pub fn scaffold(self) -> Vec<(&'static str, String)> {
        match self {
            Self::Go => vec![(
                "go.mod",
                "// Generated by saihai-forge — DO NOT EDIT\n\
                 module github.com/pleme-io/saihai/sdk/go\n\n\
                 go 1.21\n"
                    .to_string(),
            )],
            Self::TypeScript => vec![
                (
                    "package.json",
                    "{\n  \"name\": \"@pleme-io/saihai\",\n  \"version\": \"0.1.0\",\n  \
                     \"description\": \"Generated by saihai-forge — DO NOT EDIT\",\n  \
                     \"type\": \"module\",\n  \"scripts\": { \"test\": \"vitest run\" },\n  \
                     \"devDependencies\": { \"vitest\": \"^2\", \"typescript\": \"^5\" }\n}\n"
                        .to_string(),
                ),
                (
                    "tsconfig.json",
                    "{\n  \"compilerOptions\": {\n    \"target\": \"ES2022\",\n    \
                     \"module\": \"ESNext\",\n    \"moduleResolution\": \"bundler\",\n    \
                     \"strict\": true,\n    \"noEmit\": true,\n    \
                     \"resolveJsonModule\": true\n  },\n  \"include\": [\"*.ts\"]\n}\n"
                        .to_string(),
                ),
            ],
            Self::Python => vec![(
                "conftest.py",
                "# Generated by saihai-forge — DO NOT EDIT\n\
                 import pathlib\n\
                 import sys\n\n\
                 sys.path.insert(0, str(pathlib.Path(__file__).parent))\n"
                    .to_string(),
            )],
        }
    }
}

fn class_str(c: Class) -> &'static str {
    match c {
        Class::Read => "read",
        Class::Converging => "converging",
        Class::Blind => "blind",
    }
}

fn param_kind_str(k: ParamKind) -> &'static str {
    match k {
        ParamKind::Bool => "bool",
        ParamKind::Int => "int",
        ParamKind::Str => "str",
        ParamKind::Selector => "selector",
        ParamKind::Direction => "direction",
    }
}

fn ts_type(k: ParamKind) -> &'static str {
    match k {
        ParamKind::Bool => "boolean",
        ParamKind::Int => "number",
        _ => "string",
    }
}

fn py_type(k: ParamKind) -> &'static str {
    match k {
        ParamKind::Bool => "bool",
        ParamKind::Int => "int",
        _ => "str",
    }
}

fn go_type(k: ParamKind) -> &'static str {
    match k {
        ParamKind::Bool => "bool",
        ParamKind::Int => "int",
        _ => "string",
    }
}

// ── The corpus ─────────────────────────────────────────────────────────────

/// The canonical conformance corpus — every action, with the facts a client
/// must reproduce: class, authority rung, and parameter shape.
///
/// Serialised through a typed writer rather than a JSON library so the
/// escaping and ordering of the one artifact every language is judged against
/// live in one reviewable place. Inputs are validated identifiers and glosses;
/// the gloss is the only free text, and it is escaped.
#[must_use]
pub fn corpus(cat: &Catalog) -> String {
    let mut out = String::new();
    out.push_str("{\n  \"actions\": [\n");
    for (i, a) in cat.actions.iter().enumerate() {
        let sep = if i + 1 == cat.actions.len() { "" } else { "," };
        let _ = write!(
            out,
            "    {{\n      \"id\": \"{}\",\n      \"gloss\": \"{}\",\n      \
             \"category\": \"{:?}\",\n      \"kind\": \"{}\",\n      \
             \"class\": \"{}\",\n      \"auth\": \"{}\",\n      \"params\": [",
            a.id.as_str(),
            escape_json(&a.gloss),
            a.category,
            if a.kind == Kind::Observe { "observe" } else { "mutate" },
            class_str(a.class()),
            a.rung().as_str()
        );
        for (j, p) in a.params.iter().enumerate() {
            let psep = if j == 0 { "\n" } else { ",\n" };
            let _ = write!(
                out,
                "{psep}        {{ \"name\": \"{}\", \"kind\": \"{}\", \"required\": {} }}",
                p.name.as_str(),
                param_kind_str(p.kind),
                p.required
            );
        }
        out.push_str(if a.params.is_empty() { "]" } else { "\n      ]" });
        let _ = write!(out, ",\n      \"observed\": {}\n    }}{sep}\n", a.observed.len());
    }
    out.push_str("  ],\n");
    let _ = write!(out, "  \"count\": {}\n}}\n", cat.actions.len());
    out
}

fn escape_json(s: &str) -> String {
    s.chars()
        .flat_map(|c| match c {
            '"' => "\\\"".chars().collect::<Vec<_>>(),
            '\\' => "\\\\".chars().collect(),
            '\n' => "\\n".chars().collect(),
            other => vec![other],
        })
        .collect()
}

// ── Clients ────────────────────────────────────────────────────────────────

fn banner(lang: &str, comment: &str) -> String {
    format!(
        "{comment} Generated by saihai-forge ({lang}) — DO NOT EDIT\n\
         {comment} Source of truth: saihai/catalog/desktop.saihai.lisp\n\
         {comment} Verify: saihai-forge check   (fails on any drift)\n\n"
    )
}

fn ts_client(cat: &Catalog) -> String {
    let mut s = banner("typescript", "//");
    s.push_str(
        "export type Class = \"read\" | \"converging\" | \"blind\";\n\
         export type Rung = \"l0\" | \"l1\" | \"l2\" | \"l3\";\n\n\
         export interface ActionMeta {\n  \
           readonly id: string;\n  readonly cls: Class;\n  readonly auth: Rung;\n  \
           readonly params: readonly { name: string; kind: string; required: boolean }[];\n}\n\n\
         /** Every action, with the facts a caller must respect. */\n\
         export const ACTIONS: Record<string, ActionMeta> = {\n",
    );
    for a in &cat.actions {
        let _ = write!(
            s,
            "  \"{}\": {{ id: \"{}\", cls: \"{}\", auth: \"{}\", params: [",
            a.id.as_str(),
            a.id.as_str(),
            class_str(a.class()),
            a.rung().as_str()
        );
        for (j, p) in a.params.iter().enumerate() {
            let sep = if j == 0 { "" } else { ", " };
            let _ = write!(
                s,
                "{sep}{{ name: \"{}\", kind: \"{}\", required: {} }}",
                p.name.as_str(),
                param_kind_str(p.kind),
                p.required
            );
        }
        s.push_str("] },\n");
    }
    s.push_str("};\n\n");
    // One typed method per action.
    for a in &cat.actions {
        let args: Vec<String> = a
            .params
            .iter()
            .map(|p| {
                format!(
                    "{}{}: {}",
                    p.name.to_camel(),
                    if p.required { "" } else { "?" },
                    ts_type(p.kind)
                )
            })
            .collect();
        let _ = writeln!(s, "/** {} */", a.gloss);
        let _ = writeln!(
            s,
            "export function {}({}): {{ action: string; args: Record<string, unknown> }} {{",
            a.id.to_camel_method(),
            args.join(", ")
        );
        let pairs: Vec<String> = a
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name.as_str(), p.name.to_camel()))
            .collect();
        let _ = writeln!(
            s,
            "  return {{ action: \"{}\", args: {{ {} }} }};\n}}\n",
            a.id.as_str(),
            pairs.join(", ")
        );
    }
    s
}

fn py_client(cat: &Catalog) -> String {
    let mut s = banner("python", "#");
    s.push_str("ACTIONS = {\n");
    for a in &cat.actions {
        let _ = write!(
            s,
            "    \"{}\": {{\"id\": \"{}\", \"cls\": \"{}\", \"auth\": \"{}\", \"params\": [",
            a.id.as_str(),
            a.id.as_str(),
            class_str(a.class()),
            a.rung().as_str()
        );
        for (j, p) in a.params.iter().enumerate() {
            let sep = if j == 0 { "" } else { ", " };
            let _ = write!(
                s,
                "{sep}{{\"name\": \"{}\", \"kind\": \"{}\", \"required\": {}}}",
                p.name.as_str(),
                param_kind_str(p.kind),
                if p.required { "True" } else { "False" }
            );
        }
        s.push_str("]},\n");
    }
    s.push_str("}\n\n");
    for a in &cat.actions {
        let args: Vec<String> = a
            .params
            .iter()
            .map(|p| {
                if p.required {
                    format!("{}: {}", p.name.as_str(), py_type(p.kind))
                } else {
                    format!("{}: {} | None = None", p.name.as_str(), py_type(p.kind))
                }
            })
            .collect();
        let _ = writeln!(s, "def {}({}):", a.id.to_snake(), args.join(", "));
        let _ = writeln!(s, "    \"\"\"{}\"\"\"", a.gloss);
        let pairs: Vec<String> = a
            .params
            .iter()
            .map(|p| format!("\"{}\": {}", p.name.as_str(), p.name.as_str()))
            .collect();
        let _ = writeln!(
            s,
            "    return {{\"action\": \"{}\", \"args\": {{{}}}}}\n",
            a.id.as_str(),
            pairs.join(", ")
        );
    }
    s
}

fn go_client(cat: &Catalog) -> String {
    let mut s = banner("go", "//");
    s.push_str("package saihai\n\ntype Param struct {\n\tName string\n\tKind string\n\tRequired bool\n}\n\n");
    s.push_str("type ActionMeta struct {\n\tID string\n\tClass string\n\tAuth string\n\tParams []Param\n}\n\n");
    s.push_str("var Actions = map[string]ActionMeta{\n");
    for a in &cat.actions {
        let _ = write!(
            s,
            "\t\"{}\": {{ID: \"{}\", Class: \"{}\", Auth: \"{}\", Params: []Param{{",
            a.id.as_str(),
            a.id.as_str(),
            class_str(a.class()),
            a.rung().as_str()
        );
        for p in &a.params {
            let _ = write!(
                s,
                "{{Name: \"{}\", Kind: \"{}\", Required: {}}}, ",
                p.name.as_str(),
                param_kind_str(p.kind),
                p.required
            );
        }
        s.push_str("}},\n");
    }
    s.push_str("}\n\ntype Call struct {\n\tAction string\n\tArgs map[string]any\n}\n\n");
    for a in &cat.actions {
        let args: Vec<String> = a
            .params
            .iter()
            .map(|p| format!("{} {}", p.name.to_camel(), go_type(p.kind)))
            .collect();
        let _ = writeln!(s, "// {} — {}", a.id.to_pascal(), a.gloss);
        let _ = writeln!(s, "func {}({}) Call {{", a.id.to_pascal(), args.join(", "));
        let _ = writeln!(s, "\treturn Call{{Action: \"{}\", Args: map[string]any{{", a.id.as_str());
        for p in &a.params {
            let _ = writeln!(s, "\t\t\"{}\": {},", p.name.as_str(), p.name.to_camel());
        }
        s.push_str("\t}}\n}\n\n");
    }
    s
}

// ── Conformance tests ──────────────────────────────────────────────────────

fn ts_test() -> String {
    "// Generated by saihai-forge (typescript conformance) — DO NOT EDIT\n\
     //\n\
     // Compares this client against corpus.json, emitted from the Rust\n\
     // reference. Different code paths, so an emitter bug is detectable.\n\n\
     import { describe, it, expect } from \"vitest\";\n\
     import corpus from \"./corpus.json\";\n\
     import { ACTIONS } from \"./client\";\n\n\
     describe(\"saihai conformance\", () => {\n\
     \x20 it(\"exposes exactly the catalog's actions\", () => {\n\
     \x20   expect(Object.keys(ACTIONS).length).toBe(corpus.count);\n\
     \x20 });\n\
     \x20 for (const a of corpus.actions as any[]) {\n\
     \x20   it(`${a.id} matches the corpus`, () => {\n\
     \x20     const m = ACTIONS[a.id];\n\
     \x20     expect(m).toBeDefined();\n\
     \x20     expect(m.cls).toBe(a.class);\n\
     \x20     expect(m.auth).toBe(a.auth);\n\
     \x20     expect(m.params.length).toBe(a.params.length);\n\
     \x20     a.params.forEach((p: any, i: number) => {\n\
     \x20       expect(m.params[i].name).toBe(p.name);\n\
     \x20       expect(m.params[i].required).toBe(p.required);\n\
     \x20     });\n\
     \x20   });\n\
     \x20   it(`${a.id} is blind iff it observes nothing`, () => {\n\
     \x20     const blind = a.class === \"blind\";\n\
     \x20     expect(blind).toBe(a.kind === \"mutate\" && a.observed === 0);\n\
     \x20   });\n\
     \x20 }\n\
     });\n"
        .to_string()
}

fn py_test() -> String {
    "# Generated by saihai-forge (python conformance) — DO NOT EDIT\n\
     #\n\
     # Compares this client against corpus.json, emitted from the Rust\n\
     # reference. Different code paths, so an emitter bug is detectable.\n\n\
     import json\n\
     import pathlib\n\
     import pytest\n\
     from client import ACTIONS\n\n\
     CORPUS = json.loads((pathlib.Path(__file__).parent / \"corpus.json\").read_text())\n\n\n\
     def test_exposes_exactly_the_catalogs_actions():\n\
     \x20   assert len(ACTIONS) == CORPUS[\"count\"]\n\n\n\
     @pytest.mark.parametrize(\"a\", CORPUS[\"actions\"], ids=lambda a: a[\"id\"])\n\
     def test_action_matches_corpus(a):\n\
     \x20   m = ACTIONS[a[\"id\"]]\n\
     \x20   assert m[\"cls\"] == a[\"class\"]\n\
     \x20   assert m[\"auth\"] == a[\"auth\"]\n\
     \x20   assert len(m[\"params\"]) == len(a[\"params\"])\n\
     \x20   for got, want in zip(m[\"params\"], a[\"params\"]):\n\
     \x20       assert got[\"name\"] == want[\"name\"]\n\
     \x20       assert got[\"required\"] == want[\"required\"]\n\n\n\
     @pytest.mark.parametrize(\"a\", CORPUS[\"actions\"], ids=lambda a: a[\"id\"])\n\
     def test_blind_iff_observes_nothing(a):\n\
     \x20   assert (a[\"class\"] == \"blind\") == (a[\"kind\"] == \"mutate\" and a[\"observed\"] == 0)\n"
        .to_string()
}

fn go_test() -> String {
    "// Generated by saihai-forge (go conformance) — DO NOT EDIT\n\
     //\n\
     // Compares this package against corpus.json, emitted from the Rust\n\
     // reference. Different code paths, so an emitter bug is detectable.\n\n\
     package saihai\n\n\
     import (\n\t\"encoding/json\"\n\t\"os\"\n\t\"testing\"\n)\n\n\
     type corpusParam struct {\n\tName string `json:\"name\"`\n\tKind string `json:\"kind\"`\n\tRequired bool `json:\"required\"`\n}\n\n\
     type corpusAction struct {\n\tID string `json:\"id\"`\n\tKind string `json:\"kind\"`\n\tClass string `json:\"class\"`\n\tAuth string `json:\"auth\"`\n\tParams []corpusParam `json:\"params\"`\n\tObserved int `json:\"observed\"`\n}\n\n\
     type corpusFile struct {\n\tActions []corpusAction `json:\"actions\"`\n\tCount int `json:\"count\"`\n}\n\n\
     func TestConformance(t *testing.T) {\n\
     \tb, err := os.ReadFile(\"corpus.json\")\n\
     \tif err != nil {\n\t\tt.Fatalf(\"corpus.json: %v\", err)\n\t}\n\
     \tvar c corpusFile\n\
     \tif err := json.Unmarshal(b, &c); err != nil {\n\t\tt.Fatalf(\"corpus.json: %v\", err)\n\t}\n\
     \tif c.Count == 0 {\n\t\tt.Fatal(\"corpus is empty\")\n\t}\n\
     \tif len(Actions) != c.Count {\n\t\tt.Errorf(\"client has %d actions, corpus has %d\", len(Actions), c.Count)\n\t}\n\
     \tfor _, a := range c.Actions {\n\
     \t\tm, ok := Actions[a.ID]\n\
     \t\tif !ok {\n\t\t\tt.Errorf(\"%s: missing from client\", a.ID)\n\t\t\tcontinue\n\t\t}\n\
     \t\tif m.Class != a.Class {\n\t\t\tt.Errorf(\"%s class = %s, want %s\", a.ID, m.Class, a.Class)\n\t\t}\n\
     \t\tif m.Auth != a.Auth {\n\t\t\tt.Errorf(\"%s auth = %s, want %s\", a.ID, m.Auth, a.Auth)\n\t\t}\n\
     \t\tif len(m.Params) != len(a.Params) {\n\t\t\tt.Errorf(\"%s has %d params, want %d\", a.ID, len(m.Params), len(a.Params))\n\t\t\tcontinue\n\t\t}\n\
     \t\tfor i, p := range a.Params {\n\
     \t\t\tif m.Params[i].Name != p.Name || m.Params[i].Required != p.Required {\n\
     \t\t\t\tt.Errorf(\"%s param %d = %+v, want %+v\", a.ID, i, m.Params[i], p)\n\t\t\t}\n\t\t}\n\
     \t\tblind := a.Class == \"blind\"\n\
     \t\tif blind != (a.Kind == \"mutate\" && a.Observed == 0) {\n\
     \t\t\tt.Errorf(\"%s: blind/observed disagree\", a.ID)\n\t\t}\n\t}\n}\n"
        .to_string()
}

// ── Coverage honesty ───────────────────────────────────────────────────────

/// How coverage may honestly be described.
///
/// Rust produces the corpus, so a Rust conformance column compares an encoder
/// with its own output and cannot fail on an emitter bug. Keeping that as a
/// type rather than a note means a report cannot quietly merge the two counts.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Coverage {
    pub cross_implementation: Vec<&'static str>,
    pub self_referential: Vec<&'static str>,
    pub actions: usize,
}

impl Coverage {
    #[must_use]
    pub fn measure(cat: &Catalog) -> Self {
        Self {
            cross_implementation: Lang::ALL.iter().map(|l| l.name()).collect(),
            self_referential: vec!["rust"],
            actions: cat.actions.len(),
        }
    }

    #[must_use]
    pub fn report(&self) -> String {
        let mut s = String::new();
        let _ = writeln!(
            s,
            "cross-implementation columns: {}  ({})  — {} actions each",
            self.cross_implementation.len(),
            self.cross_implementation.join(", "),
            self.actions
        );
        let _ = writeln!(
            s,
            "self-referential column:      {}  ({})  — regression value only, NOT counted",
            self.self_referential.len(),
            self.self_referential.join(", ")
        );
        s
    }
}

/// Every artifact the catalog produces, as `(relative path, contents)`.
///
/// The single enumeration, so `build` and `check` cannot disagree about what
/// exists.
#[must_use]
pub fn matrix(cat: &Catalog) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for lang in Lang::ALL {
        let dir = format!("sdk/{}", lang.name());
        out.push((format!("{dir}/{}", lang.client_file()), lang.render_client(cat)));
        out.push((format!("{dir}/{}", lang.test_file()), lang.render_test()));
        out.push((format!("{dir}/corpus.json"), corpus(cat)));
        for (name, body) in lang.scaffold() {
            out.push((format!("{dir}/{name}"), body));
        }
    }
    out
}

trait MethodName {
    fn to_camel_method(&self) -> String;
}

impl MethodName for saihai_spec::ActionId {
    fn to_camel_method(&self) -> String {
        let p = self.to_pascal();
        let mut c = p.chars();
        c.next()
            .map_or_else(String::new, |f| f.to_lowercase().collect::<String>() + c.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const CATALOG: &str = include_str!("../../catalog/desktop.saihai.lisp");

    fn cat() -> Catalog {
        Catalog::from_source(CATALOG).expect("catalog compiles")
    }

    #[test]
    fn every_language_emits_every_action() {
        let c = cat();
        for lang in Lang::ALL {
            let client = lang.render_client(&c);
            for a in &c.actions {
                assert!(
                    client.contains(a.id.as_str()),
                    "{lang:?} is missing {}",
                    a.id.as_str()
                );
            }
        }
    }

    #[test]
    fn the_corpus_is_well_formed_and_carries_its_denominator() {
        let c = cat();
        let j = corpus(&c);
        assert!(j.contains(&format!("\"count\": {}", c.actions.len())));
        let braces = j.matches('{').count() as i64 - j.matches('}').count() as i64;
        let brackets = j.matches('[').count() as i64 - j.matches(']').count() as i64;
        assert_eq!(braces, 0, "unbalanced braces");
        assert_eq!(brackets, 0, "unbalanced brackets");
    }

    /// ★ Every class appears in the corpus, so the generated tests exercise the
    /// distinction rather than trivially passing on a uniform catalog.
    #[test]
    fn the_corpus_exercises_all_three_classes() {
        let c = cat();
        let j = corpus(&c);
        for cl in ["read", "converging", "blind"] {
            assert!(j.contains(&format!("\"class\": \"{cl}\"")), "no {cl} action");
        }
    }

    #[test]
    fn rust_is_never_counted_as_a_cross_implementation_column() {
        let cov = Coverage::measure(&cat());
        assert!(!cov.cross_implementation.contains(&"rust"));
        assert!(cov.self_referential.contains(&"rust"));
        assert!(cov.report().contains("NOT counted"));
    }

    #[test]
    fn the_matrix_is_complete_and_uniquely_named() {
        let m = matrix(&cat());
        let names: std::collections::HashSet<_> = m.iter().map(|(n, _)| n.clone()).collect();
        assert_eq!(names.len(), m.len(), "duplicate artifact path");
        for lang in Lang::ALL {
            assert!(names.contains(&format!("sdk/{}/corpus.json", lang.name())));
        }
    }

    #[test]
    fn rendering_is_deterministic() {
        let c = cat();
        for lang in Lang::ALL {
            assert_eq!(lang.render_client(&c), lang.render_client(&c));
        }
        assert_eq!(corpus(&c), corpus(&c));
    }
}
