# Generated by saihai-forge (python) — DO NOT EDIT
# Source of truth: saihai/catalog/desktop.saihai.lisp
# Verify: saihai-forge check   (fails on any drift)

ACTIONS = {
    "window-focus": {"id": "window-focus", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-focus-direction": {"id": "window-focus-direction", "cls": "converging", "auth": "l1", "params": [{"name": "direction", "kind": "direction", "required": True}, {"name": "wrap", "kind": "bool", "required": False}]},
    "window-move": {"id": "window-move", "cls": "converging", "auth": "l2", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "position", "kind": "str", "required": True}]},
    "window-move-direction": {"id": "window-move-direction", "cls": "converging", "auth": "l1", "params": [{"name": "direction", "kind": "direction", "required": True}]},
    "window-resize": {"id": "window-resize", "cls": "converging", "auth": "l2", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "size", "kind": "str", "required": True}]},
    "window-resize-delta": {"id": "window-resize-delta", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "axis", "kind": "str", "required": True}, {"name": "amount", "kind": "int", "required": True}]},
    "window-close": {"id": "window-close", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-set-fullscreen": {"id": "window-set-fullscreen", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "window-set-maximized": {"id": "window-set-maximized", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "window-set-minimized": {"id": "window-set-minimized", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "window-set-floating": {"id": "window-set-floating", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "window-swap": {"id": "window-swap", "cls": "converging", "auth": "l1", "params": [{"name": "a", "kind": "selector", "required": True}, {"name": "b", "kind": "str", "required": True}]},
    "window-raise": {"id": "window-raise", "cls": "blind", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-lower": {"id": "window-lower", "cls": "blind", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-center": {"id": "window-center", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "scope", "kind": "str", "required": False}]},
    "window-full-width": {"id": "window-full-width", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-equalize": {"id": "window-equalize", "cls": "converging", "auth": "l1", "params": [{"name": "scope", "kind": "str", "required": False}]},
    "window-set-managed": {"id": "window-set-managed", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "managed", "kind": "bool", "required": True}]},
    "window-set-stacked": {"id": "window-set-stacked", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "window-set-always-on-top": {"id": "window-set-always-on-top", "cls": "blind", "auth": "l3", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "window-to-output": {"id": "window-to-output", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "window-to-workspace": {"id": "window-to-workspace", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "workspace", "kind": "selector", "required": False}, {"name": "follow", "kind": "bool", "required": False}]},
    "window-consume-or-expel": {"id": "window-consume-or-expel", "cls": "converging", "auth": "l1", "params": [{"name": "direction", "kind": "direction", "required": True}]},
    "window-list": {"id": "window-list", "cls": "read", "auth": "l1", "params": [{"name": "filter", "kind": "str", "required": False}]},
    "window-get": {"id": "window-get", "cls": "read", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "window-pick": {"id": "window-pick", "cls": "read", "auth": "l1", "params": [{"name": "prompt", "kind": "str", "required": True}]},
    "window-to-scratchpad": {"id": "window-to-scratchpad", "cls": "converging", "auth": "l1", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "name", "kind": "str", "required": False}]},
    "scratchpad-show": {"id": "scratchpad-show", "cls": "converging", "auth": "l1", "params": [{"name": "name", "kind": "str", "required": False}]},
    "scratchpad-hide": {"id": "scratchpad-hide", "cls": "converging", "auth": "l1", "params": [{"name": "name", "kind": "str", "required": False}]},
    "scratchpad-cycle": {"id": "scratchpad-cycle", "cls": "converging", "auth": "l1", "params": [{"name": "direction", "kind": "direction", "required": True}]},
    "scratchpad-list": {"id": "scratchpad-list", "cls": "read", "auth": "l1", "params": []},
    "workspace-focus": {"id": "workspace-focus", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": False}]},
    "workspace-cycle": {"id": "workspace-cycle", "cls": "converging", "auth": "l1", "params": [{"name": "direction", "kind": "direction", "required": True}, {"name": "wrap", "kind": "bool", "required": False}, {"name": "scope", "kind": "str", "required": False}]},
    "workspace-create": {"id": "workspace-create", "cls": "converging", "auth": "l1", "params": [{"name": "name", "kind": "str", "required": False}, {"name": "output", "kind": "selector", "required": False}]},
    "workspace-destroy": {"id": "workspace-destroy", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": False}, {"name": "on_nonempty", "kind": "str", "required": False}]},
    "workspace-rename": {"id": "workspace-rename", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": False}, {"name": "name", "kind": "str", "required": False}]},
    "workspace-move-to-output": {"id": "workspace-move-to-output", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": False}, {"name": "output", "kind": "selector", "required": False}]},
    "workspace-reorder": {"id": "workspace-reorder", "cls": "converging", "auth": "l1", "params": [{"name": "direction", "kind": "direction", "required": True}, {"name": "workspace", "kind": "selector", "required": False}]},
    "workspace-set-urgent": {"id": "workspace-set-urgent", "cls": "converging", "auth": "l1", "params": [{"name": "urgent", "kind": "str", "required": True}, {"name": "workspace", "kind": "selector", "required": False}]},
    "workspace-list": {"id": "workspace-list", "cls": "read", "auth": "l1", "params": []},
    "layout-set": {"id": "layout-set", "cls": "converging", "auth": "l1", "params": [{"name": "layout", "kind": "str", "required": True}, {"name": "accordion", "kind": "str", "required": True}, {"name": "floating", "kind": "str", "required": True}, {"name": "auto", "kind": "str", "required": True}, {"name": "workspace", "kind": "selector", "required": False}]},
    "layout-set-orientation": {"id": "layout-set-orientation", "cls": "converging", "auth": "l1", "params": [{"name": "orientation", "kind": "str", "required": True}, {"name": "workspace", "kind": "selector", "required": False}]},
    "layout-flatten-tree": {"id": "layout-flatten-tree", "cls": "converging", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": False}]},
    "layout-set-gaps": {"id": "layout-set-gaps", "cls": "converging", "auth": "l1", "params": [{"name": "inner_h", "kind": "str", "required": True}, {"name": "inner_v", "kind": "str", "required": True}, {"name": "outer_l", "kind": "str", "required": True}, {"name": "outer_r", "kind": "str", "required": True}, {"name": "outer_t", "kind": "str", "required": True}, {"name": "outer_b", "kind": "int", "required": True}]},
    "layout-set-default-root": {"id": "layout-set-default-root", "cls": "converging", "auth": "l1", "params": [{"name": "layout", "kind": "str", "required": True}, {"name": "orientation", "kind": "str", "required": True}]},
    "layout-get": {"id": "layout-get", "cls": "read", "auth": "l1", "params": [{"name": "workspace", "kind": "selector", "required": False}]},
    "output-set-enabled": {"id": "output-set-enabled", "cls": "converging", "auth": "l2", "params": [{"name": "enabled", "kind": "bool", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "output-set-mode": {"id": "output-set-mode", "cls": "converging", "auth": "l2", "params": [{"name": "output", "kind": "selector", "required": False}, {"name": "mode", "kind": "str", "required": False}]},
    "output-set-scale": {"id": "output-set-scale", "cls": "converging", "auth": "l2", "params": [{"name": "scale", "kind": "int", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "output-set-transform": {"id": "output-set-transform", "cls": "converging", "auth": "l2", "params": [{"name": "transform", "kind": "str", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "output-set-position": {"id": "output-set-position", "cls": "converging", "auth": "l2", "params": [{"name": "position", "kind": "str", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "output-set-adaptive-sync": {"id": "output-set-adaptive-sync", "cls": "converging", "auth": "l2", "params": [{"name": "output", "kind": "selector", "required": False}, {"name": "mode", "kind": "str", "required": False}]},
    "output-set-power": {"id": "output-set-power", "cls": "converging", "auth": "l2", "params": [{"name": "power", "kind": "str", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "output-set-gamma": {"id": "output-set-gamma", "cls": "blind", "auth": "l2", "params": [{"name": "correction", "kind": "str", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "output-apply-transaction": {"id": "output-apply-transaction", "cls": "converging", "auth": "l2", "params": [{"name": "changes", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "output-list": {"id": "output-list", "cls": "read", "auth": "l0", "params": []},
    "input-set-keyboard-repeat": {"id": "input-set-keyboard-repeat", "cls": "blind", "auth": "l1", "params": [{"name": "rate_hz", "kind": "str", "required": True}, {"name": "delay_ms", "kind": "str", "required": True}]},
    "input-set-keyboard-layout": {"id": "input-set-keyboard-layout", "cls": "converging", "auth": "l1", "params": [{"name": "layouts", "kind": "str", "required": True}, {"name": "options", "kind": "str", "required": True}, {"name": "model", "kind": "str", "required": True}, {"name": "variant", "kind": "str", "required": False}]},
    "input-switch-keyboard-layout": {"id": "input-switch-keyboard-layout", "cls": "converging", "auth": "l1", "params": [{"name": "selector", "kind": "selector", "required": True}]},
    "input-set-pointer-accel": {"id": "input-set-pointer-accel", "cls": "blind", "auth": "l1", "params": [{"name": "device", "kind": "selector", "required": True}, {"name": "profile", "kind": "str", "required": True}, {"name": "speed", "kind": "str", "required": True}]},
    "input-set-natural-scroll": {"id": "input-set-natural-scroll", "cls": "blind", "auth": "l1", "params": [{"name": "device", "kind": "str", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "input-set-tap-to-click": {"id": "input-set-tap-to-click", "cls": "blind", "auth": "l1", "params": [{"name": "device", "kind": "str", "required": True}, {"name": "on", "kind": "bool", "required": True}, {"name": "drag_lock", "kind": "str", "required": True}]},
    "input-set-cursor": {"id": "input-set-cursor", "cls": "blind", "auth": "l1", "params": [{"name": "theme", "kind": "str", "required": True}, {"name": "size", "kind": "str", "required": True}]},
    "input-list-devices": {"id": "input-list-devices", "cls": "read", "auth": "l1", "params": []},
    "input-get-state": {"id": "input-get-state", "cls": "read", "auth": "l1", "params": []},
    "input-bind": {"id": "input-bind", "cls": "converging", "auth": "l1", "params": [{"name": "chord", "kind": "str", "required": True}, {"name": "action", "kind": "str", "required": True}, {"name": "condition", "kind": "str", "required": True}, {"name": "rank", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "input-unbind": {"id": "input-unbind", "cls": "converging", "auth": "l1", "params": [{"name": "chord", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "input-set-mode": {"id": "input-set-mode", "cls": "converging", "auth": "l1", "params": [{"name": "mode", "kind": "str", "required": False}]},
    "input-remap": {"id": "input-remap", "cls": "converging", "auth": "l2", "params": [{"name": "source", "kind": "str", "required": True}, {"name": "to", "kind": "str", "required": True}, {"name": "condition", "kind": "str", "required": True}]},
    "input-unremap": {"id": "input-unremap", "cls": "converging", "auth": "l2", "params": [{"name": "source", "kind": "str", "required": True}]},
    "input-bind-sequence": {"id": "input-bind-sequence", "cls": "converging", "auth": "l1", "params": [{"name": "chords", "kind": "str", "required": True}, {"name": "action", "kind": "str", "required": True}, {"name": "timeout_ms", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "input-chord-cancel": {"id": "input-chord-cancel", "cls": "converging", "auth": "l1", "params": []},
    "input-set-leader-timeout": {"id": "input-set-leader-timeout", "cls": "converging", "auth": "l1", "params": [{"name": "timeout_ms", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "input-grab-keyboard": {"id": "input-grab-keyboard", "cls": "converging", "auth": "l1", "params": [{"name": "exclusive", "kind": "str", "required": True}, {"name": "scope", "kind": "str", "required": False}]},
    "input-release-keyboard": {"id": "input-release-keyboard", "cls": "converging", "auth": "l1", "params": [{"name": "scope", "kind": "str", "required": False}]},
    "bindings-list": {"id": "bindings-list", "cls": "read", "auth": "l0", "params": [{"name": "mode", "kind": "str", "required": False}]},
    "bindings-check-conflicts": {"id": "bindings-check-conflicts", "cls": "read", "auth": "l0", "params": [{"name": "scope", "kind": "str", "required": False}]},
    "input-inject-key": {"id": "input-inject-key", "cls": "blind", "auth": "l3", "params": [{"name": "key", "kind": "str", "required": True}, {"name": "state", "kind": "str", "required": True}, {"name": "modifiers", "kind": "str", "required": True}]},
    "input-inject-chord": {"id": "input-inject-chord", "cls": "blind", "auth": "l3", "params": [{"name": "chord", "kind": "str", "required": True}]},
    "input-inject-text": {"id": "input-inject-text", "cls": "blind", "auth": "l3", "params": [{"name": "text", "kind": "str", "required": True}, {"name": "method", "kind": "str", "required": True}]},
    "input-inject-pointer": {"id": "input-inject-pointer", "cls": "blind", "auth": "l3", "params": [{"name": "motion", "kind": "str", "required": True}, {"name": "button", "kind": "str", "required": True}, {"name": "axis", "kind": "str", "required": True}]},
    "gesture-bind": {"id": "gesture-bind", "cls": "converging", "auth": "l1", "params": [{"name": "gesture", "kind": "str", "required": True}, {"name": "action", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "gesture-unbind": {"id": "gesture-unbind", "cls": "converging", "auth": "l1", "params": [{"name": "gesture", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "gesture-set-suppression": {"id": "gesture-set-suppression", "cls": "converging", "auth": "l1", "params": [{"name": "kind", "kind": "str", "required": True}, {"name": "five_finger_pinch", "kind": "str", "required": True}, {"name": "five_finger_spread", "kind": "str", "required": True}, {"name": "on", "kind": "bool", "required": True}]},
    "gesture-list": {"id": "gesture-list", "cls": "read", "auth": "l0", "params": []},
    "focus-set-follows-mouse": {"id": "focus-set-follows-mouse", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "focus-set-mouse-follows-focus": {"id": "focus-set-mouse-follows-focus", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "focus-set-auto-center": {"id": "focus-set-auto-center", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "focus-set-skip-reshuffle": {"id": "focus-set-skip-reshuffle", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "focus-set-manage-toggle-enabled": {"id": "focus-set-manage-toggle-enabled", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "edge-snap-set-left": {"id": "edge-snap-set-left", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "edge-snap-set-right": {"id": "edge-snap-set-right", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "edge-snap-set-preview": {"id": "edge-snap-set-preview", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "edge-snap-set-sticky-dwell": {"id": "edge-snap-set-sticky-dwell", "cls": "converging", "auth": "l1", "params": [{"name": "ms", "kind": "str", "required": True}]},
    "focus-policy-get": {"id": "focus-policy-get", "cls": "read", "auth": "l1", "params": []},
    "pointer-warp-to": {"id": "pointer-warp-to", "cls": "blind", "auth": "l1", "params": [{"name": "anchor", "kind": "str", "required": True}, {"name": "monitor_center", "kind": "str", "required": True}, {"name": "window_center", "kind": "str", "required": True}]},
    "rule-add": {"id": "rule-add", "cls": "converging", "auth": "l1", "params": [{"name": "criteria", "kind": "selector", "required": True}, {"name": "trigger", "kind": "str", "required": True}, {"name": "effects", "kind": "str", "required": True}, {"name": "assertiveness", "kind": "str", "required": True}]},
    "rule-remove": {"id": "rule-remove", "cls": "converging", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}]},
    "rule-list": {"id": "rule-list", "cls": "read", "auth": "l0", "params": []},
    "hook-set": {"id": "hook-set", "cls": "converging", "auth": "l1", "params": [{"name": "trigger", "kind": "str", "required": True}, {"name": "argv", "kind": "str", "required": True}]},
    "hook-unset": {"id": "hook-unset", "cls": "converging", "auth": "l1", "params": [{"name": "trigger", "kind": "str", "required": True}]},
    "hook-list": {"id": "hook-list", "cls": "read", "auth": "l0", "params": []},
    "decoration-set-border": {"id": "decoration-set-border", "cls": "converging", "auth": "l1", "params": [{"name": "active", "kind": "str", "required": True}, {"name": "inactive", "kind": "str", "required": True}, {"name": "width", "kind": "int", "required": True}]},
    "decoration-get": {"id": "decoration-get", "cls": "read", "auth": "l1", "params": []},
    "session-lock": {"id": "session-lock", "cls": "converging", "auth": "l1", "params": [{"name": "locker", "kind": "str", "required": True}, {"name": "grace_ms", "kind": "str", "required": True}]},
    "session-unlock": {"id": "session-unlock", "cls": "converging", "auth": "l1", "params": [{"name": "proof", "kind": "str", "required": True}]},
    "session-logout": {"id": "session-logout", "cls": "converging", "auth": "l2", "params": [{"name": "session", "kind": "str", "required": True}, {"name": "teardown", "kind": "str", "required": True}]},
    "session-suspend": {"id": "session-suspend", "cls": "converging", "auth": "l2", "params": [{"name": "force", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "session-reboot": {"id": "session-reboot", "cls": "blind", "auth": "l3", "params": [{"name": "delay", "kind": "int", "required": True}, {"name": "confirm", "kind": "str", "required": True}]},
    "session-poweroff": {"id": "session-poweroff", "cls": "blind", "auth": "l3", "params": [{"name": "delay", "kind": "int", "required": True}, {"name": "confirm", "kind": "str", "required": True}]},
    "session-switch-user": {"id": "session-switch-user", "cls": "converging", "auth": "l2", "params": [{"name": "to", "kind": "str", "required": True}]},
    "session-switch-vt": {"id": "session-switch-vt", "cls": "converging", "auth": "l2", "params": [{"name": "vt", "kind": "int", "required": True}, {"name": "witness", "kind": "str", "required": True}]},
    "session-set-idle-inhibit": {"id": "session-set-idle-inhibit", "cls": "converging", "auth": "l0", "params": [{"name": "on", "kind": "bool", "required": True}, {"name": "reason", "kind": "str", "required": False}, {"name": "scope", "kind": "str", "required": False}]},
    "session-set-idle-policy": {"id": "session-set-idle-policy", "cls": "blind", "auth": "l1", "params": [{"name": "rungs", "kind": "str", "required": True}, {"name": "action", "kind": "str", "required": True}]},
    "session-observe-idle": {"id": "session-observe-idle", "cls": "read", "auth": "l0", "params": [{"name": "seat", "kind": "str", "required": True}, {"name": "timeout", "kind": "int", "required": False}]},
    "session-list": {"id": "session-list", "cls": "read", "auth": "l0", "params": []},
    "session-get-state": {"id": "session-get-state", "cls": "read", "auth": "l0", "params": [{"name": "session", "kind": "str", "required": True}]},
    "login-enumerate-principals": {"id": "login-enumerate-principals", "cls": "read", "auth": "l2", "params": [{"name": "seat_answer_vec_publicprofile", "kind": "str", "required": True}]},
    "login-resolve-principal": {"id": "login-resolve-principal", "cls": "read", "auth": "l2", "params": [{"name": "name_answer_principal", "kind": "str", "required": True}]},
    "login-read-public-profile": {"id": "login-read-public-profile", "cls": "read", "auth": "l2", "params": [{"name": "principal_answer_publicprofile", "kind": "str", "required": True}]},
    "login-auth-begin": {"id": "login-auth-begin", "cls": "converging", "auth": "l2", "params": [{"name": "service", "kind": "str", "required": True}, {"name": "principal", "kind": "str", "required": True}, {"name": "tty", "kind": "str", "required": True}]},
    "login-auth-next": {"id": "login-auth-next", "cls": "converging", "auth": "l2", "params": [{"name": "handle_pamstep", "kind": "str", "required": True}]},
    "login-auth-answer": {"id": "login-auth-answer", "cls": "converging", "auth": "l2", "params": [{"name": "handle", "kind": "str", "required": True}, {"name": "response", "kind": "str", "required": True}]},
    "login-auth-account-check": {"id": "login-auth-account-check", "cls": "converging", "auth": "l2", "params": [{"name": "handle_acctverdict", "kind": "str", "required": True}]},
    "login-auth-change-token": {"id": "login-auth-change-token", "cls": "converging", "auth": "l2", "params": [{"name": "handle", "kind": "str", "required": True}]},
    "login-set-credentials": {"id": "login-set-credentials", "cls": "blind", "auth": "l2", "params": [{"name": "handle", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "login-put-env": {"id": "login-put-env", "cls": "converging", "auth": "l2", "params": [{"name": "handle", "kind": "str", "required": True}, {"name": "key", "kind": "str", "required": True}, {"name": "value", "kind": "str", "required": True}]},
    "login-get-env": {"id": "login-get-env", "cls": "read", "auth": "l2", "params": [{"name": "handle", "kind": "str", "required": True}]},
    "login-open-session": {"id": "login-open-session", "cls": "converging", "auth": "l2", "params": [{"name": "handle", "kind": "str", "required": True}]},
    "login-close-session": {"id": "login-close-session", "cls": "converging", "auth": "l2", "params": [{"name": "handle", "kind": "str", "required": True}]},
    "login-auth-end": {"id": "login-auth-end", "cls": "blind", "auth": "l2", "params": [{"name": "handle", "kind": "str", "required": True}, {"name": "status", "kind": "str", "required": True}]},
    "login-mint-capability": {"id": "login-mint-capability", "cls": "converging", "auth": "l2", "params": [{"name": "proof", "kind": "str", "required": True}, {"name": "seat", "kind": "str", "required": True}, {"name": "handle_seatcapability_authenticated", "kind": "str", "required": True}]},
    "login-start-session": {"id": "login-start-session", "cls": "converging", "auth": "l2", "params": [{"name": "cap", "kind": "str", "required": True}, {"name": "session", "kind": "selector", "required": True}]},
    "login-autologin": {"id": "login-autologin", "cls": "converging", "auth": "l2", "params": [{"name": "user", "kind": "str", "required": True}, {"name": "session", "kind": "str", "required": True}, {"name": "runfile", "kind": "str", "required": True}, {"name": "budget", "kind": "str", "required": True}, {"name": "on_exhausted", "kind": "str", "required": True}]},
    "login-fork-session": {"id": "login-fork-session", "cls": "converging", "auth": "l2", "params": [{"name": "argv", "kind": "str", "required": True}, {"name": "env", "kind": "str", "required": True}, {"name": "uid", "kind": "str", "required": True}, {"name": "gid", "kind": "str", "required": True}, {"name": "loginuid", "kind": "str", "required": True}]},
    "login-signal-session": {"id": "login-signal-session", "cls": "converging", "auth": "l2", "params": [{"name": "pid", "kind": "str", "required": True}, {"name": "signal", "kind": "str", "required": True}]},
    "login-reap-session": {"id": "login-reap-session", "cls": "read", "auth": "l2", "params": [{"name": "pid_exitstatus", "kind": "str", "required": True}]},
    "login-handoff": {"id": "login-handoff", "cls": "converging", "auth": "l2", "params": [{"name": "facts", "kind": "str", "required": True}, {"name": "value", "kind": "str", "required": True}, {"name": "epoch", "kind": "str", "required": True}, {"name": "volatility", "kind": "str", "required": True}, {"name": "scope", "kind": "str", "required": False}]},
    "seat-open": {"id": "seat-open", "cls": "converging", "auth": "l2", "params": [{"name": "seat", "kind": "str", "required": True}]},
    "seat-take-control": {"id": "seat-take-control", "cls": "converging", "auth": "l2", "params": [{"name": "seat_uncontrolled_controlled", "kind": "str", "required": True}]},
    "seat-open-device": {"id": "seat-open-device", "cls": "converging", "auth": "l2", "params": [{"name": "controlled", "kind": "str", "required": True}, {"name": "path_devicefd", "kind": "str", "required": True}]},
    "seat-close-device": {"id": "seat-close-device", "cls": "converging", "auth": "l2", "params": [{"name": "controlled", "kind": "str", "required": True}, {"name": "fd", "kind": "str", "required": True}]},
    "seat-poll": {"id": "seat-poll", "cls": "read", "auth": "l2", "params": [{"name": "controlled", "kind": "str", "required": True}, {"name": "deadline_seattransition", "kind": "str", "required": True}]},
    "seat-ack-disable": {"id": "seat-ack-disable", "cls": "converging", "auth": "l2", "params": [{"name": "disabling_disabled", "kind": "str", "required": True}]},
    "seat-reacquire": {"id": "seat-reacquire", "cls": "converging", "auth": "l2", "params": [{"name": "disabled_controlled", "kind": "str", "required": True}]},
    "vt-query-free": {"id": "vt-query-free", "cls": "read", "auth": "l2", "params": [{"name": "seat0witness_vtnumber", "kind": "str", "required": True}]},
    "vt-set-kd-mode": {"id": "vt-set-kd-mode", "cls": "converging", "auth": "l2", "params": [{"name": "witness", "kind": "str", "required": True}, {"name": "vt", "kind": "int", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "vt-set-kb-mode": {"id": "vt-set-kb-mode", "cls": "converging", "auth": "l2", "params": [{"name": "witness", "kind": "str", "required": True}, {"name": "vt", "kind": "int", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "launch-spawn": {"id": "launch-spawn", "cls": "blind", "auth": "l0", "params": [{"name": "argv", "kind": "str", "required": True}, {"name": "env", "kind": "str", "required": True}, {"name": "cwd", "kind": "str", "required": True}]},
    "launch-activate": {"id": "launch-activate", "cls": "blind", "auth": "l0", "params": [{"name": "app_id", "kind": "str", "required": True}, {"name": "token", "kind": "str", "required": True}]},
    "launch-desktop-entry": {"id": "launch-desktop-entry", "cls": "converging", "auth": "l0", "params": [{"name": "entry", "kind": "str", "required": True}, {"name": "action", "kind": "str", "required": True}, {"name": "args", "kind": "str", "required": True}]},
    "launch-open-url": {"id": "launch-open-url", "cls": "blind", "auth": "l0", "params": [{"name": "url", "kind": "str", "required": True}]},
    "launch-open-path": {"id": "launch-open-path", "cls": "blind", "auth": "l0", "params": [{"name": "using", "kind": "str", "required": True}, {"name": "path", "kind": "str", "required": False}]},
    "launch-focus-or-spawn": {"id": "launch-focus-or-spawn", "cls": "converging", "auth": "l1", "params": [{"name": "criteria", "kind": "selector", "required": True}, {"name": "argv", "kind": "str", "required": True}, {"name": "timeout_ms", "kind": "str", "required": True}]},
    "launcher-toggle": {"id": "launcher-toggle", "cls": "converging", "auth": "l0", "params": []},
    "launcher-show": {"id": "launcher-show", "cls": "converging", "auth": "l0", "params": []},
    "launcher-hide": {"id": "launcher-hide", "cls": "converging", "auth": "l0", "params": []},
    "launcher-set-query": {"id": "launcher-set-query", "cls": "converging", "auth": "l0", "params": [{"name": "query", "kind": "str", "required": True}]},
    "launcher-get-state": {"id": "launcher-get-state", "cls": "read", "auth": "l0", "params": []},
    "launcher-run-command": {"id": "launcher-run-command", "cls": "blind", "auth": "l1", "params": [{"name": "argv", "kind": "str", "required": True}]},
    "clipboard-get": {"id": "clipboard-get", "cls": "read", "auth": "l2", "params": [{"name": "mime_answer_bytes", "kind": "str", "required": True}, {"name": "selection", "kind": "str", "required": False}]},
    "clipboard-put": {"id": "clipboard-put", "cls": "converging", "auth": "l2", "params": [{"name": "mime", "kind": "str", "required": True}, {"name": "data", "kind": "str", "required": True}, {"name": "sensitive", "kind": "bool", "required": True}, {"name": "selection", "kind": "str", "required": False}]},
    "clipboard-clear": {"id": "clipboard-clear", "cls": "converging", "auth": "l2", "params": [{"name": "selection", "kind": "str", "required": False}]},
    "clipboard-history-list": {"id": "clipboard-history-list", "cls": "read", "auth": "l1", "params": [{"name": "limit", "kind": "str", "required": True}]},
    "clipboard-history-clear": {"id": "clipboard-history-clear", "cls": "converging", "auth": "l1", "params": []},
    "screenshot-capture": {"id": "screenshot-capture", "cls": "converging", "auth": "l2", "params": [{"name": "source", "kind": "str", "required": True}, {"name": "sink", "kind": "str", "required": True}, {"name": "include_cursor", "kind": "str", "required": True}]},
    "screenshot-pick-region": {"id": "screenshot-pick-region", "cls": "read", "auth": "l1", "params": [{"name": "prompt", "kind": "str", "required": True}]},
    "color-pick": {"id": "color-pick", "cls": "read", "auth": "l1", "params": []},
    "screencast-start": {"id": "screencast-start", "cls": "converging", "auth": "l2", "params": [{"name": "source", "kind": "str", "required": True}, {"name": "sink", "kind": "str", "required": True}, {"name": "fps", "kind": "str", "required": True}, {"name": "include_cursor_castid", "kind": "str", "required": True}]},
    "screencast-stop": {"id": "screencast-stop", "cls": "converging", "auth": "l2", "params": [{"name": "cast", "kind": "str", "required": True}]},
    "screencast-list": {"id": "screencast-list", "cls": "read", "auth": "l1", "params": []},
    "notify-send": {"id": "notify-send", "cls": "converging", "auth": "l0", "params": [{"name": "summary", "kind": "str", "required": True}, {"name": "app_id", "kind": "str", "required": True}, {"name": "timeout_ms", "kind": "str", "required": True}, {"name": "actions", "kind": "str", "required": True}, {"name": "icon_notificationid", "kind": "str", "required": True}, {"name": "body", "kind": "str", "required": False}, {"name": "urgency", "kind": "str", "required": False}]},
    "notify-invoke-action": {"id": "notify-invoke-action", "cls": "converging", "auth": "l0", "params": [{"name": "id", "kind": "str", "required": True}, {"name": "action_id", "kind": "str", "required": True}]},
    "notify-dismiss": {"id": "notify-dismiss", "cls": "converging", "auth": "l0", "params": [{"name": "id", "kind": "str", "required": True}]},
    "notify-dismiss-all": {"id": "notify-dismiss-all", "cls": "converging", "auth": "l0", "params": [{"name": "filter", "kind": "str", "required": False}]},
    "notify-mark-read": {"id": "notify-mark-read", "cls": "converging", "auth": "l0", "params": [{"name": "target", "kind": "selector", "required": True}]},
    "notify-set-dnd": {"id": "notify-set-dnd", "cls": "converging", "auth": "l0", "params": [{"name": "on", "kind": "bool", "required": True}, {"name": "until", "kind": "str", "required": True}]},
    "notify-list": {"id": "notify-list", "cls": "read", "auth": "l0", "params": [{"name": "include_history", "kind": "str", "required": True}, {"name": "filter", "kind": "str", "required": False}]},
    "notify-history-clear": {"id": "notify-history-clear", "cls": "converging", "auth": "l0", "params": []},
    "notify-history-delete-one": {"id": "notify-history-delete-one", "cls": "converging", "auth": "l0", "params": [{"name": "entry_id", "kind": "str", "required": True}]},
    "notify-toggle-expand": {"id": "notify-toggle-expand", "cls": "converging", "auth": "l0", "params": [{"name": "id", "kind": "str", "required": True}]},
    "notify-toggle-view": {"id": "notify-toggle-view", "cls": "converging", "auth": "l0", "params": []},
    "notify-search": {"id": "notify-search", "cls": "converging", "auth": "l0", "params": [{"name": "query", "kind": "str", "required": True}]},
    "notify-filter-set": {"id": "notify-filter-set", "cls": "converging", "auth": "l0", "params": [{"name": "by", "kind": "str", "required": True}, {"name": "value", "kind": "str", "required": True}, {"name": "urgency", "kind": "str", "required": False}]},
    "layer-spawn": {"id": "layer-spawn", "cls": "converging", "auth": "l1", "params": [{"name": "client", "kind": "str", "required": True}, {"name": "layer", "kind": "str", "required": True}, {"name": "anchor", "kind": "str", "required": True}, {"name": "exclusive_zone", "kind": "str", "required": True}, {"name": "keyboard", "kind": "str", "required": True}, {"name": "output", "kind": "selector", "required": False}]},
    "layer-kill": {"id": "layer-kill", "cls": "converging", "auth": "l1", "params": [{"name": "client", "kind": "str", "required": True}, {"name": "teardown", "kind": "str", "required": True}]},
    "layer-list": {"id": "layer-list", "cls": "read", "auth": "l1", "params": []},
    "pane-session-new": {"id": "pane-session-new", "cls": "converging", "auth": "l1", "params": [{"name": "name_panesessionid", "kind": "str", "required": True}]},
    "pane-session-kill": {"id": "pane-session-kill", "cls": "converging", "auth": "l1", "params": [{"name": "session", "kind": "str", "required": True}]},
    "pane-session-list": {"id": "pane-session-list", "cls": "read", "auth": "l0", "params": []},
    "pane-session-detail": {"id": "pane-session-detail", "cls": "read", "auth": "l0", "params": [{"name": "session", "kind": "str", "required": True}]},
    "pane-list": {"id": "pane-list", "cls": "read", "auth": "l0", "params": [{"name": "session", "kind": "str", "required": True}]},
    "pane-snapshot": {"id": "pane-snapshot", "cls": "read", "auth": "l0", "params": [{"name": "pane", "kind": "str", "required": True}]},
    "pane-send-keys": {"id": "pane-send-keys", "cls": "blind", "auth": "l1", "params": [{"name": "pane", "kind": "str", "required": True}, {"name": "keys", "kind": "str", "required": True}]},
    "pane-set-input-policy": {"id": "pane-set-input-policy", "cls": "converging", "auth": "l1", "params": [{"name": "pane", "kind": "str", "required": True}, {"name": "policy", "kind": "str", "required": True}]},
    "pane-subscriber-count": {"id": "pane-subscriber-count", "cls": "read", "auth": "l0", "params": [{"name": "pane", "kind": "str", "required": True}]},
    "pane-record-start": {"id": "pane-record-start", "cls": "converging", "auth": "l1", "params": [{"name": "pane", "kind": "str", "required": True}]},
    "pane-record-stop": {"id": "pane-record-stop", "cls": "converging", "auth": "l1", "params": [{"name": "pane", "kind": "str", "required": True}]},
    "pane-record-export": {"id": "pane-record-export", "cls": "converging", "auth": "l1", "params": [{"name": "pane", "kind": "str", "required": True}, {"name": "path", "kind": "str", "required": False}]},
    "pane-record-status": {"id": "pane-record-status", "cls": "read", "auth": "l0", "params": [{"name": "pane", "kind": "str", "required": True}]},
    "pane-blocks-list": {"id": "pane-blocks-list", "cls": "read", "auth": "l0", "params": [{"name": "pane", "kind": "str", "required": True}]},
    "pane-block-at": {"id": "pane-block-at", "cls": "read", "auth": "l0", "params": [{"name": "pane", "kind": "str", "required": True}, {"name": "index", "kind": "int", "required": False}]},
    "pane-blocks-status": {"id": "pane-blocks-status", "cls": "read", "auth": "l0", "params": [{"name": "pane", "kind": "str", "required": True}]},
    "pane-stats": {"id": "pane-stats", "cls": "read", "auth": "l0", "params": [{"name": "pane", "kind": "str", "required": True}]},
    "pane-top": {"id": "pane-top", "cls": "read", "auth": "l0", "params": [{"name": "limit", "kind": "str", "required": True}]},
    "pane-daemon-status": {"id": "pane-daemon-status", "cls": "read", "auth": "l0", "params": []},
    "pane-system-resources": {"id": "pane-system-resources", "cls": "read", "auth": "l0", "params": []},
    "pane-socket-info": {"id": "pane-socket-info", "cls": "read", "auth": "l0", "params": []},
    "pane-config-get": {"id": "pane-config-get", "cls": "read", "auth": "l0", "params": []},
    "pane-config-set": {"id": "pane-config-set", "cls": "converging", "auth": "l1", "params": [{"name": "yaml", "kind": "str", "required": True}]},
    "pane-reload-config": {"id": "pane-reload-config", "cls": "converging", "auth": "l1", "params": []},
    "browser-open": {"id": "browser-open", "cls": "converging", "auth": "l1", "params": [{"name": "url_browserid", "kind": "str", "required": True}]},
    "browser-close": {"id": "browser-close", "cls": "converging", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}]},
    "browser-focus": {"id": "browser-focus", "cls": "converging", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}]},
    "browser-list": {"id": "browser-list", "cls": "read", "auth": "l0", "params": []},
    "browser-move": {"id": "browser-move", "cls": "converging", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}, {"name": "position", "kind": "str", "required": True}]},
    "browser-resize": {"id": "browser-resize", "cls": "converging", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}, {"name": "size", "kind": "str", "required": True}]},
    "browser-navigate": {"id": "browser-navigate", "cls": "converging", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}, {"name": "url", "kind": "str", "required": True}]},
    "browser-snap": {"id": "browser-snap", "cls": "converging", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}, {"name": "zone", "kind": "str", "required": True}]},
    "browser-snapshot": {"id": "browser-snapshot", "cls": "converging", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}]},
    "browser-snapshot-get": {"id": "browser-snapshot-get", "cls": "read", "auth": "l0", "params": [{"name": "id", "kind": "str", "required": True}]},
    "browser-set-dom": {"id": "browser-set-dom", "cls": "blind", "auth": "l1", "params": [{"name": "id", "kind": "str", "required": True}, {"name": "dom", "kind": "str", "required": True}]},
    "theme-select": {"id": "theme-select", "cls": "converging", "auth": "l0", "params": [{"name": "theme", "kind": "str", "required": True}]},
    "theme-set-appearance": {"id": "theme-set-appearance", "cls": "converging", "auth": "l0", "params": [{"name": "appearance", "kind": "str", "required": True}, {"name": "dark", "kind": "str", "required": True}, {"name": "auto", "kind": "str", "required": True}]},
    "theme-set-font-scale": {"id": "theme-set-font-scale", "cls": "converging", "auth": "l0", "params": [{"name": "scale", "kind": "int", "required": True}]},
    "theme-reload": {"id": "theme-reload", "cls": "converging", "auth": "l0", "params": []},
    "theme-get": {"id": "theme-get", "cls": "read", "auth": "l0", "params": [{"name": "theme_per_leaf_provenance", "kind": "str", "required": True}]},
    "screen-transition-run": {"id": "screen-transition-run", "cls": "blind", "auth": "l1", "params": [{"name": "delay_ms", "kind": "str", "required": True}]},
    "audio-set-volume": {"id": "audio-set-volume", "cls": "converging", "auth": "l0", "params": [{"name": "target", "kind": "selector", "required": True}, {"name": "sink", "kind": "str", "required": True}]},
    "audio-set-mute": {"id": "audio-set-mute", "cls": "converging", "auth": "l0", "params": [{"name": "on", "kind": "bool", "required": True}, {"name": "sink", "kind": "str", "required": True}]},
    "audio-set-default-sink": {"id": "audio-set-default-sink", "cls": "converging", "auth": "l0", "params": [{"name": "sink", "kind": "str", "required": True}]},
    "audio-list-sinks": {"id": "audio-list-sinks", "cls": "read", "auth": "l0", "params": []},
    "screensaver-start": {"id": "screensaver-start", "cls": "converging", "auth": "l0", "params": []},
    "trash-empty": {"id": "trash-empty", "cls": "converging", "auth": "l3", "params": [{"name": "confirm", "kind": "str", "required": True}]},
    "volume-eject-all": {"id": "volume-eject-all", "cls": "converging", "auth": "l1", "params": []},
    "overview-set": {"id": "overview-set", "cls": "converging", "auth": "l1", "params": [{"name": "on", "kind": "bool", "required": True}]},
    "config-reload": {"id": "config-reload", "cls": "converging", "auth": "l1", "params": [{"name": "path", "kind": "str", "required": False}]},
    "config-get": {"id": "config-get", "cls": "read", "auth": "l0", "params": [{"name": "key", "kind": "str", "required": True}, {"name": "include_provenance", "kind": "str", "required": True}]},
    "config-set": {"id": "config-set", "cls": "converging", "auth": "l1", "params": [{"name": "key", "kind": "str", "required": True}, {"name": "value", "kind": "str", "required": True}, {"name": "apply", "kind": "str", "required": True}, {"name": "live", "kind": "str", "required": True}]},
    "state-query": {"id": "state-query", "cls": "read", "auth": "l1", "params": [{"name": "domain", "kind": "str", "required": True}]},
    "events-subscribe": {"id": "events-subscribe", "cls": "read", "auth": "l1", "params": [{"name": "since", "kind": "str", "required": True}, {"name": "filter", "kind": "str", "required": False}]},
    "compositor-quit": {"id": "compositor-quit", "cls": "blind", "auth": "l3", "params": [{"name": "confirm", "kind": "str", "required": True}, {"name": "teardown", "kind": "str", "required": True}]},
    "desktop-plan": {"id": "desktop-plan", "cls": "read", "auth": "l1", "params": [{"name": "spec", "kind": "str", "required": True}]},
    "desktop-apply": {"id": "desktop-apply", "cls": "converging", "auth": "l1", "params": [{"name": "spec", "kind": "str", "required": True}, {"name": "policy", "kind": "str", "required": True}, {"name": "mode", "kind": "str", "required": False}]},
    "desktop-tick": {"id": "desktop-tick", "cls": "converging", "auth": "l1", "params": [{"name": "tickoutcome", "kind": "str", "required": True}]},
    "desktop-attest": {"id": "desktop-attest", "cls": "read", "auth": "l0", "params": [{"name": "receipt_desktoppayload", "kind": "str", "required": True}]},
    "desktop-health": {"id": "desktop-health", "cls": "read", "auth": "l0", "params": []},
    "desktop-version": {"id": "desktop-version", "cls": "read", "auth": "l0", "params": []},
}

def window_focus(target: str):
    """Window focus"""
    return {"action": "window-focus", "args": {"target": target}}

def window_focus_direction(direction: str, wrap: bool | None = None):
    """Window focus direction"""
    return {"action": "window-focus-direction", "args": {"direction": direction, "wrap": wrap}}

def window_move(target: str, position: str):
    """Window move"""
    return {"action": "window-move", "args": {"target": target, "position": position}}

def window_move_direction(direction: str):
    """Window move direction"""
    return {"action": "window-move-direction", "args": {"direction": direction}}

def window_resize(target: str, size: str):
    """Window resize"""
    return {"action": "window-resize", "args": {"target": target, "size": size}}

def window_resize_delta(target: str, axis: str, amount: int):
    """Window resize delta"""
    return {"action": "window-resize-delta", "args": {"target": target, "axis": axis, "amount": amount}}

def window_close(target: str):
    """Window close"""
    return {"action": "window-close", "args": {"target": target}}

def window_set_fullscreen(target: str, on: bool, output: str | None = None):
    """Window set fullscreen"""
    return {"action": "window-set-fullscreen", "args": {"target": target, "on": on, "output": output}}

def window_set_maximized(target: str, on: bool):
    """Window set maximized"""
    return {"action": "window-set-maximized", "args": {"target": target, "on": on}}

def window_set_minimized(target: str, on: bool):
    """Window set minimized"""
    return {"action": "window-set-minimized", "args": {"target": target, "on": on}}

def window_set_floating(target: str, on: bool):
    """Window set floating"""
    return {"action": "window-set-floating", "args": {"target": target, "on": on}}

def window_swap(a: str, b: str):
    """Window swap"""
    return {"action": "window-swap", "args": {"a": a, "b": b}}

def window_raise(target: str):
    """Window raise"""
    return {"action": "window-raise", "args": {"target": target}}

def window_lower(target: str):
    """Window lower"""
    return {"action": "window-lower", "args": {"target": target}}

def window_center(target: str, scope: str | None = None):
    """Window center"""
    return {"action": "window-center", "args": {"target": target, "scope": scope}}

def window_full_width(target: str):
    """Window full width"""
    return {"action": "window-full-width", "args": {"target": target}}

def window_equalize(scope: str | None = None):
    """Window equalize"""
    return {"action": "window-equalize", "args": {"scope": scope}}

def window_set_managed(target: str, managed: bool):
    """Window set managed"""
    return {"action": "window-set-managed", "args": {"target": target, "managed": managed}}

def window_set_stacked(target: str, on: bool):
    """Window set stacked"""
    return {"action": "window-set-stacked", "args": {"target": target, "on": on}}

def window_set_always_on_top(target: str, on: bool):
    """Window set always on top"""
    return {"action": "window-set-always-on-top", "args": {"target": target, "on": on}}

def window_to_output(target: str, output: str | None = None):
    """Window to output"""
    return {"action": "window-to-output", "args": {"target": target, "output": output}}

def window_to_workspace(target: str, workspace: str | None = None, follow: bool | None = None):
    """Window to workspace"""
    return {"action": "window-to-workspace", "args": {"target": target, "workspace": workspace, "follow": follow}}

def window_consume_or_expel(direction: str):
    """Window consume or expel"""
    return {"action": "window-consume-or-expel", "args": {"direction": direction}}

def window_list(filter: str | None = None):
    """Window list"""
    return {"action": "window-list", "args": {"filter": filter}}

def window_get(target: str):
    """Window get"""
    return {"action": "window-get", "args": {"target": target}}

def window_pick(prompt: str):
    """Window pick"""
    return {"action": "window-pick", "args": {"prompt": prompt}}

def window_to_scratchpad(target: str, name: str | None = None):
    """Window to scratchpad"""
    return {"action": "window-to-scratchpad", "args": {"target": target, "name": name}}

def scratchpad_show(name: str | None = None):
    """Scratchpad show"""
    return {"action": "scratchpad-show", "args": {"name": name}}

def scratchpad_hide(name: str | None = None):
    """Scratchpad hide"""
    return {"action": "scratchpad-hide", "args": {"name": name}}

def scratchpad_cycle(direction: str):
    """Scratchpad cycle"""
    return {"action": "scratchpad-cycle", "args": {"direction": direction}}

def scratchpad_list():
    """Scratchpad list"""
    return {"action": "scratchpad-list", "args": {}}

def workspace_focus(workspace: str | None = None):
    """Workspace focus"""
    return {"action": "workspace-focus", "args": {"workspace": workspace}}

def workspace_cycle(direction: str, wrap: bool | None = None, scope: str | None = None):
    """Workspace cycle"""
    return {"action": "workspace-cycle", "args": {"direction": direction, "wrap": wrap, "scope": scope}}

def workspace_create(name: str | None = None, output: str | None = None):
    """Workspace create"""
    return {"action": "workspace-create", "args": {"name": name, "output": output}}

def workspace_destroy(workspace: str | None = None, on_nonempty: str | None = None):
    """Workspace destroy"""
    return {"action": "workspace-destroy", "args": {"workspace": workspace, "on_nonempty": on_nonempty}}

def workspace_rename(workspace: str | None = None, name: str | None = None):
    """Workspace rename"""
    return {"action": "workspace-rename", "args": {"workspace": workspace, "name": name}}

def workspace_move_to_output(workspace: str | None = None, output: str | None = None):
    """Workspace move to output"""
    return {"action": "workspace-move-to-output", "args": {"workspace": workspace, "output": output}}

def workspace_reorder(direction: str, workspace: str | None = None):
    """Workspace reorder"""
    return {"action": "workspace-reorder", "args": {"direction": direction, "workspace": workspace}}

def workspace_set_urgent(urgent: str, workspace: str | None = None):
    """Workspace set urgent"""
    return {"action": "workspace-set-urgent", "args": {"urgent": urgent, "workspace": workspace}}

def workspace_list():
    """Workspace list"""
    return {"action": "workspace-list", "args": {}}

def layout_set(layout: str, accordion: str, floating: str, auto: str, workspace: str | None = None):
    """Layout set"""
    return {"action": "layout-set", "args": {"layout": layout, "accordion": accordion, "floating": floating, "auto": auto, "workspace": workspace}}

def layout_set_orientation(orientation: str, workspace: str | None = None):
    """Layout set orientation"""
    return {"action": "layout-set-orientation", "args": {"orientation": orientation, "workspace": workspace}}

def layout_flatten_tree(workspace: str | None = None):
    """Layout flatten tree"""
    return {"action": "layout-flatten-tree", "args": {"workspace": workspace}}

def layout_set_gaps(inner_h: str, inner_v: str, outer_l: str, outer_r: str, outer_t: str, outer_b: int):
    """Layout set gaps"""
    return {"action": "layout-set-gaps", "args": {"inner_h": inner_h, "inner_v": inner_v, "outer_l": outer_l, "outer_r": outer_r, "outer_t": outer_t, "outer_b": outer_b}}

def layout_set_default_root(layout: str, orientation: str):
    """Layout set default root"""
    return {"action": "layout-set-default-root", "args": {"layout": layout, "orientation": orientation}}

def layout_get(workspace: str | None = None):
    """Layout get"""
    return {"action": "layout-get", "args": {"workspace": workspace}}

def output_set_enabled(enabled: bool, output: str | None = None):
    """Output set enabled"""
    return {"action": "output-set-enabled", "args": {"enabled": enabled, "output": output}}

def output_set_mode(output: str | None = None, mode: str | None = None):
    """Output set mode"""
    return {"action": "output-set-mode", "args": {"output": output, "mode": mode}}

def output_set_scale(scale: int, output: str | None = None):
    """Output set scale"""
    return {"action": "output-set-scale", "args": {"scale": scale, "output": output}}

def output_set_transform(transform: str, output: str | None = None):
    """Output set transform"""
    return {"action": "output-set-transform", "args": {"transform": transform, "output": output}}

def output_set_position(position: str, output: str | None = None):
    """Output set position"""
    return {"action": "output-set-position", "args": {"position": position, "output": output}}

def output_set_adaptive_sync(output: str | None = None, mode: str | None = None):
    """Output set adaptive sync"""
    return {"action": "output-set-adaptive-sync", "args": {"output": output, "mode": mode}}

def output_set_power(power: str, output: str | None = None):
    """Output set power"""
    return {"action": "output-set-power", "args": {"power": power, "output": output}}

def output_set_gamma(correction: str, output: str | None = None):
    """Output set gamma"""
    return {"action": "output-set-gamma", "args": {"correction": correction, "output": output}}

def output_apply_transaction(changes: str, mode: str | None = None):
    """Output apply transaction"""
    return {"action": "output-apply-transaction", "args": {"changes": changes, "mode": mode}}

def output_list():
    """Output list"""
    return {"action": "output-list", "args": {}}

def input_set_keyboard_repeat(rate_hz: str, delay_ms: str):
    """Input set keyboard repeat"""
    return {"action": "input-set-keyboard-repeat", "args": {"rate_hz": rate_hz, "delay_ms": delay_ms}}

def input_set_keyboard_layout(layouts: str, options: str, model: str, variant: str | None = None):
    """Input set keyboard layout"""
    return {"action": "input-set-keyboard-layout", "args": {"layouts": layouts, "options": options, "model": model, "variant": variant}}

def input_switch_keyboard_layout(selector: str):
    """Input switch keyboard layout"""
    return {"action": "input-switch-keyboard-layout", "args": {"selector": selector}}

def input_set_pointer_accel(device: str, profile: str, speed: str):
    """Input set pointer accel"""
    return {"action": "input-set-pointer-accel", "args": {"device": device, "profile": profile, "speed": speed}}

def input_set_natural_scroll(device: str, on: bool):
    """Input set natural scroll"""
    return {"action": "input-set-natural-scroll", "args": {"device": device, "on": on}}

def input_set_tap_to_click(device: str, on: bool, drag_lock: str):
    """Input set tap to click"""
    return {"action": "input-set-tap-to-click", "args": {"device": device, "on": on, "drag_lock": drag_lock}}

def input_set_cursor(theme: str, size: str):
    """Input set cursor"""
    return {"action": "input-set-cursor", "args": {"theme": theme, "size": size}}

def input_list_devices():
    """Input list devices"""
    return {"action": "input-list-devices", "args": {}}

def input_get_state():
    """Input get state"""
    return {"action": "input-get-state", "args": {}}

def input_bind(chord: str, action: str, condition: str, rank: str, mode: str | None = None):
    """Input bind"""
    return {"action": "input-bind", "args": {"chord": chord, "action": action, "condition": condition, "rank": rank, "mode": mode}}

def input_unbind(chord: str, mode: str | None = None):
    """Input unbind"""
    return {"action": "input-unbind", "args": {"chord": chord, "mode": mode}}

def input_set_mode(mode: str | None = None):
    """Input set mode"""
    return {"action": "input-set-mode", "args": {"mode": mode}}

def input_remap(source: str, to: str, condition: str):
    """Input remap"""
    return {"action": "input-remap", "args": {"source": source, "to": to, "condition": condition}}

def input_unremap(source: str):
    """Input unremap"""
    return {"action": "input-unremap", "args": {"source": source}}

def input_bind_sequence(chords: str, action: str, timeout_ms: str, mode: str | None = None):
    """Input bind sequence"""
    return {"action": "input-bind-sequence", "args": {"chords": chords, "action": action, "timeout_ms": timeout_ms, "mode": mode}}

def input_chord_cancel():
    """Input chord cancel"""
    return {"action": "input-chord-cancel", "args": {}}

def input_set_leader_timeout(timeout_ms: str, mode: str | None = None):
    """Input set leader timeout"""
    return {"action": "input-set-leader-timeout", "args": {"timeout_ms": timeout_ms, "mode": mode}}

def input_grab_keyboard(exclusive: str, scope: str | None = None):
    """Input grab keyboard"""
    return {"action": "input-grab-keyboard", "args": {"exclusive": exclusive, "scope": scope}}

def input_release_keyboard(scope: str | None = None):
    """Input release keyboard"""
    return {"action": "input-release-keyboard", "args": {"scope": scope}}

def bindings_list(mode: str | None = None):
    """Bindings list"""
    return {"action": "bindings-list", "args": {"mode": mode}}

def bindings_check_conflicts(scope: str | None = None):
    """Bindings check conflicts"""
    return {"action": "bindings-check-conflicts", "args": {"scope": scope}}

def input_inject_key(key: str, state: str, modifiers: str):
    """Input inject key"""
    return {"action": "input-inject-key", "args": {"key": key, "state": state, "modifiers": modifiers}}

def input_inject_chord(chord: str):
    """Input inject chord"""
    return {"action": "input-inject-chord", "args": {"chord": chord}}

def input_inject_text(text: str, method: str):
    """Input inject text"""
    return {"action": "input-inject-text", "args": {"text": text, "method": method}}

def input_inject_pointer(motion: str, button: str, axis: str):
    """Input inject pointer"""
    return {"action": "input-inject-pointer", "args": {"motion": motion, "button": button, "axis": axis}}

def gesture_bind(gesture: str, action: str, mode: str | None = None):
    """Gesture bind"""
    return {"action": "gesture-bind", "args": {"gesture": gesture, "action": action, "mode": mode}}

def gesture_unbind(gesture: str, mode: str | None = None):
    """Gesture unbind"""
    return {"action": "gesture-unbind", "args": {"gesture": gesture, "mode": mode}}

def gesture_set_suppression(kind: str, five_finger_pinch: str, five_finger_spread: str, on: bool):
    """Gesture set suppression"""
    return {"action": "gesture-set-suppression", "args": {"kind": kind, "five_finger_pinch": five_finger_pinch, "five_finger_spread": five_finger_spread, "on": on}}

def gesture_list():
    """Gesture list"""
    return {"action": "gesture-list", "args": {}}

def focus_set_follows_mouse(on: bool):
    """Focus set follows mouse"""
    return {"action": "focus-set-follows-mouse", "args": {"on": on}}

def focus_set_mouse_follows_focus(on: bool):
    """Focus set mouse follows focus"""
    return {"action": "focus-set-mouse-follows-focus", "args": {"on": on}}

def focus_set_auto_center(on: bool):
    """Focus set auto center"""
    return {"action": "focus-set-auto-center", "args": {"on": on}}

def focus_set_skip_reshuffle(on: bool):
    """Focus set skip reshuffle"""
    return {"action": "focus-set-skip-reshuffle", "args": {"on": on}}

def focus_set_manage_toggle_enabled(on: bool):
    """Focus set manage toggle enabled"""
    return {"action": "focus-set-manage-toggle-enabled", "args": {"on": on}}

def edge_snap_set_left(on: bool):
    """Edge snap set left"""
    return {"action": "edge-snap-set-left", "args": {"on": on}}

def edge_snap_set_right(on: bool):
    """Edge snap set right"""
    return {"action": "edge-snap-set-right", "args": {"on": on}}

def edge_snap_set_preview(on: bool):
    """Edge snap set preview"""
    return {"action": "edge-snap-set-preview", "args": {"on": on}}

def edge_snap_set_sticky_dwell(ms: str):
    """Edge snap set sticky dwell"""
    return {"action": "edge-snap-set-sticky-dwell", "args": {"ms": ms}}

def focus_policy_get():
    """Focus policy get"""
    return {"action": "focus-policy-get", "args": {}}

def pointer_warp_to(anchor: str, monitor_center: str, window_center: str):
    """Pointer warp to"""
    return {"action": "pointer-warp-to", "args": {"anchor": anchor, "monitor_center": monitor_center, "window_center": window_center}}

def rule_add(criteria: str, trigger: str, effects: str, assertiveness: str):
    """Rule add"""
    return {"action": "rule-add", "args": {"criteria": criteria, "trigger": trigger, "effects": effects, "assertiveness": assertiveness}}

def rule_remove(id: str):
    """Rule remove"""
    return {"action": "rule-remove", "args": {"id": id}}

def rule_list():
    """Rule list"""
    return {"action": "rule-list", "args": {}}

def hook_set(trigger: str, argv: str):
    """Hook set"""
    return {"action": "hook-set", "args": {"trigger": trigger, "argv": argv}}

def hook_unset(trigger: str):
    """Hook unset"""
    return {"action": "hook-unset", "args": {"trigger": trigger}}

def hook_list():
    """Hook list"""
    return {"action": "hook-list", "args": {}}

def decoration_set_border(active: str, inactive: str, width: int):
    """Decoration set border"""
    return {"action": "decoration-set-border", "args": {"active": active, "inactive": inactive, "width": width}}

def decoration_get():
    """Decoration get"""
    return {"action": "decoration-get", "args": {}}

def session_lock(locker: str, grace_ms: str):
    """Session lock"""
    return {"action": "session-lock", "args": {"locker": locker, "grace_ms": grace_ms}}

def session_unlock(proof: str):
    """Session unlock"""
    return {"action": "session-unlock", "args": {"proof": proof}}

def session_logout(session: str, teardown: str):
    """Session logout"""
    return {"action": "session-logout", "args": {"session": session, "teardown": teardown}}

def session_suspend(force: str, mode: str | None = None):
    """Session suspend"""
    return {"action": "session-suspend", "args": {"force": force, "mode": mode}}

def session_reboot(delay: int, confirm: str):
    """Session reboot"""
    return {"action": "session-reboot", "args": {"delay": delay, "confirm": confirm}}

def session_poweroff(delay: int, confirm: str):
    """Session poweroff"""
    return {"action": "session-poweroff", "args": {"delay": delay, "confirm": confirm}}

def session_switch_user(to: str):
    """Session switch user"""
    return {"action": "session-switch-user", "args": {"to": to}}

def session_switch_vt(vt: int, witness: str):
    """Session switch vt"""
    return {"action": "session-switch-vt", "args": {"vt": vt, "witness": witness}}

def session_set_idle_inhibit(on: bool, reason: str | None = None, scope: str | None = None):
    """Session set idle inhibit"""
    return {"action": "session-set-idle-inhibit", "args": {"on": on, "reason": reason, "scope": scope}}

def session_set_idle_policy(rungs: str, action: str):
    """Session set idle policy"""
    return {"action": "session-set-idle-policy", "args": {"rungs": rungs, "action": action}}

def session_observe_idle(seat: str, timeout: int | None = None):
    """Session observe idle"""
    return {"action": "session-observe-idle", "args": {"seat": seat, "timeout": timeout}}

def session_list():
    """Session list"""
    return {"action": "session-list", "args": {}}

def session_get_state(session: str):
    """Session get state"""
    return {"action": "session-get-state", "args": {"session": session}}

def login_enumerate_principals(seat_answer_vec_publicprofile: str):
    """Login enumerate principals"""
    return {"action": "login-enumerate-principals", "args": {"seat_answer_vec_publicprofile": seat_answer_vec_publicprofile}}

def login_resolve_principal(name_answer_principal: str):
    """Login resolve principal"""
    return {"action": "login-resolve-principal", "args": {"name_answer_principal": name_answer_principal}}

def login_read_public_profile(principal_answer_publicprofile: str):
    """Login read public profile"""
    return {"action": "login-read-public-profile", "args": {"principal_answer_publicprofile": principal_answer_publicprofile}}

def login_auth_begin(service: str, principal: str, tty: str):
    """Login auth begin"""
    return {"action": "login-auth-begin", "args": {"service": service, "principal": principal, "tty": tty}}

def login_auth_next(handle_pamstep: str):
    """Login auth next"""
    return {"action": "login-auth-next", "args": {"handle_pamstep": handle_pamstep}}

def login_auth_answer(handle: str, response: str):
    """Login auth answer"""
    return {"action": "login-auth-answer", "args": {"handle": handle, "response": response}}

def login_auth_account_check(handle_acctverdict: str):
    """Login auth account check"""
    return {"action": "login-auth-account-check", "args": {"handle_acctverdict": handle_acctverdict}}

def login_auth_change_token(handle: str):
    """Login auth change token"""
    return {"action": "login-auth-change-token", "args": {"handle": handle}}

def login_set_credentials(handle: str, mode: str | None = None):
    """Login set credentials"""
    return {"action": "login-set-credentials", "args": {"handle": handle, "mode": mode}}

def login_put_env(handle: str, key: str, value: str):
    """Login put env"""
    return {"action": "login-put-env", "args": {"handle": handle, "key": key, "value": value}}

def login_get_env(handle: str):
    """Login get env"""
    return {"action": "login-get-env", "args": {"handle": handle}}

def login_open_session(handle: str):
    """Login open session"""
    return {"action": "login-open-session", "args": {"handle": handle}}

def login_close_session(handle: str):
    """Login close session"""
    return {"action": "login-close-session", "args": {"handle": handle}}

def login_auth_end(handle: str, status: str):
    """Login auth end"""
    return {"action": "login-auth-end", "args": {"handle": handle, "status": status}}

def login_mint_capability(proof: str, seat: str, handle_seatcapability_authenticated: str):
    """Login mint capability"""
    return {"action": "login-mint-capability", "args": {"proof": proof, "seat": seat, "handle_seatcapability_authenticated": handle_seatcapability_authenticated}}

def login_start_session(cap: str, session: str):
    """Login start session"""
    return {"action": "login-start-session", "args": {"cap": cap, "session": session}}

def login_autologin(user: str, session: str, runfile: str, budget: str, on_exhausted: str):
    """Login autologin"""
    return {"action": "login-autologin", "args": {"user": user, "session": session, "runfile": runfile, "budget": budget, "on_exhausted": on_exhausted}}

def login_fork_session(argv: str, env: str, uid: str, gid: str, loginuid: str):
    """Login fork session"""
    return {"action": "login-fork-session", "args": {"argv": argv, "env": env, "uid": uid, "gid": gid, "loginuid": loginuid}}

def login_signal_session(pid: str, signal: str):
    """Login signal session"""
    return {"action": "login-signal-session", "args": {"pid": pid, "signal": signal}}

def login_reap_session(pid_exitstatus: str):
    """Login reap session"""
    return {"action": "login-reap-session", "args": {"pid_exitstatus": pid_exitstatus}}

def login_handoff(facts: str, value: str, epoch: str, volatility: str, scope: str | None = None):
    """Login handoff"""
    return {"action": "login-handoff", "args": {"facts": facts, "value": value, "epoch": epoch, "volatility": volatility, "scope": scope}}

def seat_open(seat: str):
    """Seat open"""
    return {"action": "seat-open", "args": {"seat": seat}}

def seat_take_control(seat_uncontrolled_controlled: str):
    """Seat take control"""
    return {"action": "seat-take-control", "args": {"seat_uncontrolled_controlled": seat_uncontrolled_controlled}}

def seat_open_device(controlled: str, path_devicefd: str):
    """Seat open device"""
    return {"action": "seat-open-device", "args": {"controlled": controlled, "path_devicefd": path_devicefd}}

def seat_close_device(controlled: str, fd: str):
    """Seat close device"""
    return {"action": "seat-close-device", "args": {"controlled": controlled, "fd": fd}}

def seat_poll(controlled: str, deadline_seattransition: str):
    """Seat poll"""
    return {"action": "seat-poll", "args": {"controlled": controlled, "deadline_seattransition": deadline_seattransition}}

def seat_ack_disable(disabling_disabled: str):
    """Seat ack disable"""
    return {"action": "seat-ack-disable", "args": {"disabling_disabled": disabling_disabled}}

def seat_reacquire(disabled_controlled: str):
    """Seat reacquire"""
    return {"action": "seat-reacquire", "args": {"disabled_controlled": disabled_controlled}}

def vt_query_free(seat0witness_vtnumber: str):
    """Vt query free"""
    return {"action": "vt-query-free", "args": {"seat0witness_vtnumber": seat0witness_vtnumber}}

def vt_set_kd_mode(witness: str, vt: int, mode: str | None = None):
    """Vt set kd mode"""
    return {"action": "vt-set-kd-mode", "args": {"witness": witness, "vt": vt, "mode": mode}}

def vt_set_kb_mode(witness: str, vt: int, mode: str | None = None):
    """Vt set kb mode"""
    return {"action": "vt-set-kb-mode", "args": {"witness": witness, "vt": vt, "mode": mode}}

def launch_spawn(argv: str, env: str, cwd: str):
    """Launch spawn"""
    return {"action": "launch-spawn", "args": {"argv": argv, "env": env, "cwd": cwd}}

def launch_activate(app_id: str, token: str):
    """Launch activate"""
    return {"action": "launch-activate", "args": {"app_id": app_id, "token": token}}

def launch_desktop_entry(entry: str, action: str, args: str):
    """Launch desktop entry"""
    return {"action": "launch-desktop-entry", "args": {"entry": entry, "action": action, "args": args}}

def launch_open_url(url: str):
    """Launch open url"""
    return {"action": "launch-open-url", "args": {"url": url}}

def launch_open_path(using: str, path: str | None = None):
    """Launch open path"""
    return {"action": "launch-open-path", "args": {"using": using, "path": path}}

def launch_focus_or_spawn(criteria: str, argv: str, timeout_ms: str):
    """Launch focus or spawn"""
    return {"action": "launch-focus-or-spawn", "args": {"criteria": criteria, "argv": argv, "timeout_ms": timeout_ms}}

def launcher_toggle():
    """Launcher toggle"""
    return {"action": "launcher-toggle", "args": {}}

def launcher_show():
    """Launcher show"""
    return {"action": "launcher-show", "args": {}}

def launcher_hide():
    """Launcher hide"""
    return {"action": "launcher-hide", "args": {}}

def launcher_set_query(query: str):
    """Launcher set query"""
    return {"action": "launcher-set-query", "args": {"query": query}}

def launcher_get_state():
    """Launcher get state"""
    return {"action": "launcher-get-state", "args": {}}

def launcher_run_command(argv: str):
    """Launcher run command"""
    return {"action": "launcher-run-command", "args": {"argv": argv}}

def clipboard_get(mime_answer_bytes: str, selection: str | None = None):
    """Clipboard get"""
    return {"action": "clipboard-get", "args": {"mime_answer_bytes": mime_answer_bytes, "selection": selection}}

def clipboard_put(mime: str, data: str, sensitive: bool, selection: str | None = None):
    """Clipboard put"""
    return {"action": "clipboard-put", "args": {"mime": mime, "data": data, "sensitive": sensitive, "selection": selection}}

def clipboard_clear(selection: str | None = None):
    """Clipboard clear"""
    return {"action": "clipboard-clear", "args": {"selection": selection}}

def clipboard_history_list(limit: str):
    """Clipboard history list"""
    return {"action": "clipboard-history-list", "args": {"limit": limit}}

def clipboard_history_clear():
    """Clipboard history clear"""
    return {"action": "clipboard-history-clear", "args": {}}

def screenshot_capture(source: str, sink: str, include_cursor: str):
    """Screenshot capture"""
    return {"action": "screenshot-capture", "args": {"source": source, "sink": sink, "include_cursor": include_cursor}}

def screenshot_pick_region(prompt: str):
    """Screenshot pick region"""
    return {"action": "screenshot-pick-region", "args": {"prompt": prompt}}

def color_pick():
    """Color pick"""
    return {"action": "color-pick", "args": {}}

def screencast_start(source: str, sink: str, fps: str, include_cursor_castid: str):
    """Screencast start"""
    return {"action": "screencast-start", "args": {"source": source, "sink": sink, "fps": fps, "include_cursor_castid": include_cursor_castid}}

def screencast_stop(cast: str):
    """Screencast stop"""
    return {"action": "screencast-stop", "args": {"cast": cast}}

def screencast_list():
    """Screencast list"""
    return {"action": "screencast-list", "args": {}}

def notify_send(summary: str, app_id: str, timeout_ms: str, actions: str, icon_notificationid: str, body: str | None = None, urgency: str | None = None):
    """Notify send"""
    return {"action": "notify-send", "args": {"summary": summary, "app_id": app_id, "timeout_ms": timeout_ms, "actions": actions, "icon_notificationid": icon_notificationid, "body": body, "urgency": urgency}}

def notify_invoke_action(id: str, action_id: str):
    """Notify invoke action"""
    return {"action": "notify-invoke-action", "args": {"id": id, "action_id": action_id}}

def notify_dismiss(id: str):
    """Notify dismiss"""
    return {"action": "notify-dismiss", "args": {"id": id}}

def notify_dismiss_all(filter: str | None = None):
    """Notify dismiss all"""
    return {"action": "notify-dismiss-all", "args": {"filter": filter}}

def notify_mark_read(target: str):
    """Notify mark read"""
    return {"action": "notify-mark-read", "args": {"target": target}}

def notify_set_dnd(on: bool, until: str):
    """Notify set dnd"""
    return {"action": "notify-set-dnd", "args": {"on": on, "until": until}}

def notify_list(include_history: str, filter: str | None = None):
    """Notify list"""
    return {"action": "notify-list", "args": {"include_history": include_history, "filter": filter}}

def notify_history_clear():
    """Notify history clear"""
    return {"action": "notify-history-clear", "args": {}}

def notify_history_delete_one(entry_id: str):
    """Notify history delete one"""
    return {"action": "notify-history-delete-one", "args": {"entry_id": entry_id}}

def notify_toggle_expand(id: str):
    """Notify toggle expand"""
    return {"action": "notify-toggle-expand", "args": {"id": id}}

def notify_toggle_view():
    """Notify toggle view"""
    return {"action": "notify-toggle-view", "args": {}}

def notify_search(query: str):
    """Notify search"""
    return {"action": "notify-search", "args": {"query": query}}

def notify_filter_set(by: str, value: str, urgency: str | None = None):
    """Notify filter set"""
    return {"action": "notify-filter-set", "args": {"by": by, "value": value, "urgency": urgency}}

def layer_spawn(client: str, layer: str, anchor: str, exclusive_zone: str, keyboard: str, output: str | None = None):
    """Layer spawn"""
    return {"action": "layer-spawn", "args": {"client": client, "layer": layer, "anchor": anchor, "exclusive_zone": exclusive_zone, "keyboard": keyboard, "output": output}}

def layer_kill(client: str, teardown: str):
    """Layer kill"""
    return {"action": "layer-kill", "args": {"client": client, "teardown": teardown}}

def layer_list():
    """Layer list"""
    return {"action": "layer-list", "args": {}}

def pane_session_new(name_panesessionid: str):
    """Pane session new"""
    return {"action": "pane-session-new", "args": {"name_panesessionid": name_panesessionid}}

def pane_session_kill(session: str):
    """Pane session kill"""
    return {"action": "pane-session-kill", "args": {"session": session}}

def pane_session_list():
    """Pane session list"""
    return {"action": "pane-session-list", "args": {}}

def pane_session_detail(session: str):
    """Pane session detail"""
    return {"action": "pane-session-detail", "args": {"session": session}}

def pane_list(session: str):
    """Pane list"""
    return {"action": "pane-list", "args": {"session": session}}

def pane_snapshot(pane: str):
    """Pane snapshot"""
    return {"action": "pane-snapshot", "args": {"pane": pane}}

def pane_send_keys(pane: str, keys: str):
    """Pane send keys"""
    return {"action": "pane-send-keys", "args": {"pane": pane, "keys": keys}}

def pane_set_input_policy(pane: str, policy: str):
    """Pane set input policy"""
    return {"action": "pane-set-input-policy", "args": {"pane": pane, "policy": policy}}

def pane_subscriber_count(pane: str):
    """Pane subscriber count"""
    return {"action": "pane-subscriber-count", "args": {"pane": pane}}

def pane_record_start(pane: str):
    """Pane record start"""
    return {"action": "pane-record-start", "args": {"pane": pane}}

def pane_record_stop(pane: str):
    """Pane record stop"""
    return {"action": "pane-record-stop", "args": {"pane": pane}}

def pane_record_export(pane: str, path: str | None = None):
    """Pane record export"""
    return {"action": "pane-record-export", "args": {"pane": pane, "path": path}}

def pane_record_status(pane: str):
    """Pane record status"""
    return {"action": "pane-record-status", "args": {"pane": pane}}

def pane_blocks_list(pane: str):
    """Pane blocks list"""
    return {"action": "pane-blocks-list", "args": {"pane": pane}}

def pane_block_at(pane: str, index: int | None = None):
    """Pane block at"""
    return {"action": "pane-block-at", "args": {"pane": pane, "index": index}}

def pane_blocks_status(pane: str):
    """Pane blocks status"""
    return {"action": "pane-blocks-status", "args": {"pane": pane}}

def pane_stats(pane: str):
    """Pane stats"""
    return {"action": "pane-stats", "args": {"pane": pane}}

def pane_top(limit: str):
    """Pane top"""
    return {"action": "pane-top", "args": {"limit": limit}}

def pane_daemon_status():
    """Pane daemon status"""
    return {"action": "pane-daemon-status", "args": {}}

def pane_system_resources():
    """Pane system resources"""
    return {"action": "pane-system-resources", "args": {}}

def pane_socket_info():
    """Pane socket info"""
    return {"action": "pane-socket-info", "args": {}}

def pane_config_get():
    """Pane config get"""
    return {"action": "pane-config-get", "args": {}}

def pane_config_set(yaml: str):
    """Pane config set"""
    return {"action": "pane-config-set", "args": {"yaml": yaml}}

def pane_reload_config():
    """Pane reload config"""
    return {"action": "pane-reload-config", "args": {}}

def browser_open(url_browserid: str):
    """Browser open"""
    return {"action": "browser-open", "args": {"url_browserid": url_browserid}}

def browser_close(id: str):
    """Browser close"""
    return {"action": "browser-close", "args": {"id": id}}

def browser_focus(id: str):
    """Browser focus"""
    return {"action": "browser-focus", "args": {"id": id}}

def browser_list():
    """Browser list"""
    return {"action": "browser-list", "args": {}}

def browser_move(id: str, position: str):
    """Browser move"""
    return {"action": "browser-move", "args": {"id": id, "position": position}}

def browser_resize(id: str, size: str):
    """Browser resize"""
    return {"action": "browser-resize", "args": {"id": id, "size": size}}

def browser_navigate(id: str, url: str):
    """Browser navigate"""
    return {"action": "browser-navigate", "args": {"id": id, "url": url}}

def browser_snap(id: str, zone: str):
    """Browser snap"""
    return {"action": "browser-snap", "args": {"id": id, "zone": zone}}

def browser_snapshot(id: str):
    """Browser snapshot"""
    return {"action": "browser-snapshot", "args": {"id": id}}

def browser_snapshot_get(id: str):
    """Browser snapshot get"""
    return {"action": "browser-snapshot-get", "args": {"id": id}}

def browser_set_dom(id: str, dom: str):
    """Browser set dom"""
    return {"action": "browser-set-dom", "args": {"id": id, "dom": dom}}

def theme_select(theme: str):
    """Theme select"""
    return {"action": "theme-select", "args": {"theme": theme}}

def theme_set_appearance(appearance: str, dark: str, auto: str):
    """Theme set appearance"""
    return {"action": "theme-set-appearance", "args": {"appearance": appearance, "dark": dark, "auto": auto}}

def theme_set_font_scale(scale: int):
    """Theme set font scale"""
    return {"action": "theme-set-font-scale", "args": {"scale": scale}}

def theme_reload():
    """Theme reload"""
    return {"action": "theme-reload", "args": {}}

def theme_get(theme_per_leaf_provenance: str):
    """Theme get"""
    return {"action": "theme-get", "args": {"theme_per_leaf_provenance": theme_per_leaf_provenance}}

def screen_transition_run(delay_ms: str):
    """Screen transition run"""
    return {"action": "screen-transition-run", "args": {"delay_ms": delay_ms}}

def audio_set_volume(target: str, sink: str):
    """Audio set volume"""
    return {"action": "audio-set-volume", "args": {"target": target, "sink": sink}}

def audio_set_mute(on: bool, sink: str):
    """Audio set mute"""
    return {"action": "audio-set-mute", "args": {"on": on, "sink": sink}}

def audio_set_default_sink(sink: str):
    """Audio set default sink"""
    return {"action": "audio-set-default-sink", "args": {"sink": sink}}

def audio_list_sinks():
    """Audio list sinks"""
    return {"action": "audio-list-sinks", "args": {}}

def screensaver_start():
    """Screensaver start"""
    return {"action": "screensaver-start", "args": {}}

def trash_empty(confirm: str):
    """Trash empty"""
    return {"action": "trash-empty", "args": {"confirm": confirm}}

def volume_eject_all():
    """Volume eject all"""
    return {"action": "volume-eject-all", "args": {}}

def overview_set(on: bool):
    """Overview set"""
    return {"action": "overview-set", "args": {"on": on}}

def config_reload(path: str | None = None):
    """Config reload"""
    return {"action": "config-reload", "args": {"path": path}}

def config_get(key: str, include_provenance: str):
    """Config get"""
    return {"action": "config-get", "args": {"key": key, "include_provenance": include_provenance}}

def config_set(key: str, value: str, apply: str, live: str):
    """Config set"""
    return {"action": "config-set", "args": {"key": key, "value": value, "apply": apply, "live": live}}

def state_query(domain: str):
    """State query"""
    return {"action": "state-query", "args": {"domain": domain}}

def events_subscribe(since: str, filter: str | None = None):
    """Events subscribe"""
    return {"action": "events-subscribe", "args": {"since": since, "filter": filter}}

def compositor_quit(confirm: str, teardown: str):
    """Compositor quit"""
    return {"action": "compositor-quit", "args": {"confirm": confirm, "teardown": teardown}}

def desktop_plan(spec: str):
    """Desktop plan"""
    return {"action": "desktop-plan", "args": {"spec": spec}}

def desktop_apply(spec: str, policy: str, mode: str | None = None):
    """Desktop apply"""
    return {"action": "desktop-apply", "args": {"spec": spec, "policy": policy, "mode": mode}}

def desktop_tick(tickoutcome: str):
    """Desktop tick"""
    return {"action": "desktop-tick", "args": {"tickoutcome": tickoutcome}}

def desktop_attest(receipt_desktoppayload: str):
    """Desktop attest"""
    return {"action": "desktop-attest", "args": {"receipt_desktoppayload": receipt_desktoppayload}}

def desktop_health():
    """Desktop health"""
    return {"action": "desktop-health", "args": {}}

def desktop_version():
    """Desktop version"""
    return {"action": "desktop-version", "args": {}}

