# Generated by saihai-forge (python conformance) — DO NOT EDIT
#
# Compares this client against corpus.json, emitted from the Rust
# reference. Different code paths, so an emitter bug is detectable.

import json
import pathlib
import pytest
from client import ACTIONS

CORPUS = json.loads((pathlib.Path(__file__).parent / "corpus.json").read_text())


def test_exposes_exactly_the_catalogs_actions():
    assert len(ACTIONS) == CORPUS["count"]


@pytest.mark.parametrize("a", CORPUS["actions"], ids=lambda a: a["id"])
def test_action_matches_corpus(a):
    m = ACTIONS[a["id"]]
    assert m["cls"] == a["class"]
    assert m["auth"] == a["auth"]
    assert len(m["params"]) == len(a["params"])
    for got, want in zip(m["params"], a["params"]):
        assert got["name"] == want["name"]
        assert got["required"] == want["required"]


@pytest.mark.parametrize("a", CORPUS["actions"], ids=lambda a: a["id"])
def test_blind_iff_observes_nothing(a):
    assert (a["class"] == "blind") == (a["kind"] == "mutate" and a["observed"] == 0)
