// Generated by saihai-forge (typescript) — DO NOT EDIT
// Source of truth: saihai/catalog/desktop.saihai.lisp
// Verify: saihai-forge check   (fails on any drift)

export type Class = "read" | "converging" | "blind";
export type Rung = "l0" | "l1" | "l2" | "l3";

export interface ActionMeta {
  readonly id: string;
  readonly cls: Class;
  readonly auth: Rung;
  readonly params: readonly { name: string; kind: string; required: boolean }[];
}

/** Every action, with the facts a caller must respect. */
export const ACTIONS: Record<string, ActionMeta> = {
  "window-focus": { id: "window-focus", cls: "converging", auth: "l1", params: [{ name: "target", kind: "selector", required: true }] },
  "window-focus-direction": { id: "window-focus-direction", cls: "converging", auth: "l1", params: [{ name: "direction", kind: "direction", required: true }, { name: "wrap", kind: "bool", required: false }] },
  "window-move": { id: "window-move", cls: "converging", auth: "l2", params: [{ name: "target", kind: "selector", required: true }, { name: "x", kind: "int", required: true }, { name: "y", kind: "int", required: true }] },
  "window-resize": { id: "window-resize", cls: "converging", auth: "l2", params: [{ name: "target", kind: "selector", required: true }, { name: "width", kind: "int", required: true }, { name: "height", kind: "int", required: true }] },
  "window-close": { id: "window-close", cls: "converging", auth: "l1", params: [{ name: "target", kind: "selector", required: true }] },
  "window-set-fullscreen": { id: "window-set-fullscreen", cls: "converging", auth: "l1", params: [{ name: "target", kind: "selector", required: true }, { name: "on", kind: "bool", required: true }] },
  "window-set-maximized": { id: "window-set-maximized", cls: "converging", auth: "l1", params: [{ name: "target", kind: "selector", required: true }, { name: "on", kind: "bool", required: true }] },
  "window-set-floating": { id: "window-set-floating", cls: "converging", auth: "l1", params: [{ name: "target", kind: "selector", required: true }, { name: "on", kind: "bool", required: true }] },
  "window-raise": { id: "window-raise", cls: "blind", auth: "l1", params: [{ name: "target", kind: "selector", required: true }] },
  "window-lower": { id: "window-lower", cls: "blind", auth: "l1", params: [{ name: "target", kind: "selector", required: true }] },
  "window-to-workspace": { id: "window-to-workspace", cls: "converging", auth: "l1", params: [{ name: "target", kind: "selector", required: true }, { name: "workspace", kind: "selector", required: true }, { name: "follow", kind: "bool", required: false }] },
  "window-to-output": { id: "window-to-output", cls: "converging", auth: "l1", params: [{ name: "target", kind: "selector", required: true }, { name: "output", kind: "selector", required: true }] },
  "window-swap": { id: "window-swap", cls: "converging", auth: "l1", params: [{ name: "target", kind: "selector", required: true }, { name: "other", kind: "selector", required: true }] },
  "window-list": { id: "window-list", cls: "read", auth: "l0", params: [{ name: "filter", kind: "str", required: false }] },
  "window-get": { id: "window-get", cls: "read", auth: "l0", params: [{ name: "target", kind: "selector", required: true }] },
  "workspace-focus": { id: "workspace-focus", cls: "converging", auth: "l1", params: [{ name: "workspace", kind: "selector", required: true }] },
  "workspace-cycle": { id: "workspace-cycle", cls: "converging", auth: "l1", params: [{ name: "direction", kind: "direction", required: true }, { name: "wrap", kind: "bool", required: false }] },
  "workspace-create": { id: "workspace-create", cls: "converging", auth: "l1", params: [{ name: "name", kind: "str", required: true }, { name: "output", kind: "selector", required: false }] },
  "workspace-destroy": { id: "workspace-destroy", cls: "converging", auth: "l1", params: [{ name: "workspace", kind: "selector", required: true }] },
  "workspace-rename": { id: "workspace-rename", cls: "converging", auth: "l1", params: [{ name: "workspace", kind: "selector", required: true }, { name: "name", kind: "str", required: true }] },
  "workspace-move-to-output": { id: "workspace-move-to-output", cls: "converging", auth: "l1", params: [{ name: "workspace", kind: "selector", required: true }, { name: "output", kind: "selector", required: true }] },
  "workspace-list": { id: "workspace-list", cls: "read", auth: "l0", params: [] },
  "layout-set": { id: "layout-set", cls: "converging", auth: "l1", params: [{ name: "workspace", kind: "selector", required: true }, { name: "layout", kind: "str", required: true }] },
  "layout-set-orientation": { id: "layout-set-orientation", cls: "converging", auth: "l1", params: [{ name: "workspace", kind: "selector", required: true }, { name: "orientation", kind: "str", required: true }] },
  "layout-set-gaps": { id: "layout-set-gaps", cls: "converging", auth: "l1", params: [{ name: "inner", kind: "int", required: true }, { name: "outer", kind: "int", required: true }] },
  "layout-equalize": { id: "layout-equalize", cls: "converging", auth: "l1", params: [{ name: "workspace", kind: "selector", required: false }] },
  "layout-get": { id: "layout-get", cls: "read", auth: "l0", params: [{ name: "workspace", kind: "selector", required: true }] },
  "output-set-enabled": { id: "output-set-enabled", cls: "converging", auth: "l2", params: [{ name: "output", kind: "selector", required: true }, { name: "on", kind: "bool", required: true }] },
  "output-set-mode": { id: "output-set-mode", cls: "converging", auth: "l2", params: [{ name: "output", kind: "selector", required: true }, { name: "width", kind: "int", required: true }, { name: "height", kind: "int", required: true }, { name: "refresh", kind: "int", required: false }] },
  "output-set-scale": { id: "output-set-scale", cls: "converging", auth: "l2", params: [{ name: "output", kind: "selector", required: true }, { name: "scale", kind: "int", required: true }] },
  "output-set-transform": { id: "output-set-transform", cls: "converging", auth: "l2", params: [{ name: "output", kind: "selector", required: true }, { name: "transform", kind: "str", required: true }] },
  "output-set-position": { id: "output-set-position", cls: "converging", auth: "l2", params: [{ name: "output", kind: "selector", required: true }, { name: "x", kind: "int", required: true }, { name: "y", kind: "int", required: true }] },
  "output-list": { id: "output-list", cls: "read", auth: "l0", params: [] },
  "input-set-repeat": { id: "input-set-repeat", cls: "converging", auth: "l1", params: [{ name: "rate", kind: "int", required: true }, { name: "delay", kind: "int", required: true }] },
  "input-set-layout": { id: "input-set-layout", cls: "converging", auth: "l1", params: [{ name: "layout", kind: "str", required: true }, { name: "variant", kind: "str", required: false }] },
  "input-bind": { id: "input-bind", cls: "converging", auth: "l1", params: [{ name: "chord", kind: "str", required: true }, { name: "action", kind: "str", required: true }, { name: "mode", kind: "str", required: false }] },
  "input-unbind": { id: "input-unbind", cls: "converging", auth: "l1", params: [{ name: "chord", kind: "str", required: true }, { name: "mode", kind: "str", required: false }] },
  "input-set-mode": { id: "input-set-mode", cls: "converging", auth: "l1", params: [{ name: "mode", kind: "str", required: true }] },
  "input-send-keys": { id: "input-send-keys", cls: "blind", auth: "l3", params: [{ name: "keys", kind: "str", required: true }, { name: "target", kind: "selector", required: false }] },
  "input-list-bindings": { id: "input-list-bindings", cls: "read", auth: "l0", params: [{ name: "mode", kind: "str", required: false }] },
  "focus-set-policy": { id: "focus-set-policy", cls: "converging", auth: "l1", params: [{ name: "policy", kind: "str", required: true }] },
  "focus-get": { id: "focus-get", cls: "read", auth: "l0", params: [] },
  "session-lock": { id: "session-lock", cls: "converging", auth: "l1", params: [] },
  "session-unlock": { id: "session-unlock", cls: "converging", auth: "l1", params: [] },
  "session-logout": { id: "session-logout", cls: "converging", auth: "l1", params: [] },
  "session-suspend": { id: "session-suspend", cls: "blind", auth: "l2", params: [] },
  "session-reboot": { id: "session-reboot", cls: "blind", auth: "l2", params: [] },
  "session-poweroff": { id: "session-poweroff", cls: "blind", auth: "l2", params: [] },
  "session-switch-vt": { id: "session-switch-vt", cls: "converging", auth: "l2", params: [{ name: "vt", kind: "int", required: true }] },
  "session-get": { id: "session-get", cls: "read", auth: "l0", params: [] },
  "login-authenticate": { id: "login-authenticate", cls: "converging", auth: "l2", params: [{ name: "user", kind: "str", required: true }] },
  "login-start-session": { id: "login-start-session", cls: "converging", auth: "l2", params: [{ name: "user", kind: "str", required: true }, { name: "session", kind: "str", required: false }] },
  "login-end-session": { id: "login-end-session", cls: "converging", auth: "l2", params: [{ name: "user", kind: "str", required: true }] },
  "login-switch-user": { id: "login-switch-user", cls: "converging", auth: "l2", params: [{ name: "user", kind: "str", required: true }] },
  "login-list-sessions": { id: "login-list-sessions", cls: "read", auth: "l0", params: [] },
  "seat-get": { id: "seat-get", cls: "read", auth: "l0", params: [] },
  "launch-spawn": { id: "launch-spawn", cls: "converging", auth: "l1", params: [{ name: "command", kind: "str", required: true }, { name: "workspace", kind: "selector", required: false }] },
  "launch-focus-or-spawn": { id: "launch-focus-or-spawn", cls: "converging", auth: "l1", params: [{ name: "criteria", kind: "selector", required: true }, { name: "command", kind: "str", required: true }] },
  "clipboard-get": { id: "clipboard-get", cls: "read", auth: "l1", params: [{ name: "selection", kind: "str", required: false }] },
  "clipboard-put": { id: "clipboard-put", cls: "converging", auth: "l1", params: [{ name: "content", kind: "str", required: true }, { name: "selection", kind: "str", required: false }] },
  "clipboard-clear": { id: "clipboard-clear", cls: "converging", auth: "l1", params: [{ name: "selection", kind: "str", required: false }] },
  "capture-screenshot": { id: "capture-screenshot", cls: "blind", auth: "l2", params: [{ name: "target", kind: "selector", required: false }, { name: "path", kind: "str", required: false }] },
  "capture-screencast-start": { id: "capture-screencast-start", cls: "blind", auth: "l2", params: [{ name: "target", kind: "selector", required: false }] },
  "capture-screencast-stop": { id: "capture-screencast-stop", cls: "blind", auth: "l2", params: [] },
  "notify-send": { id: "notify-send", cls: "blind", auth: "l0", params: [{ name: "summary", kind: "str", required: true }, { name: "body", kind: "str", required: false }, { name: "urgency", kind: "str", required: false }] },
  "notify-dismiss": { id: "notify-dismiss", cls: "blind", auth: "l0", params: [{ name: "target", kind: "selector", required: true }] },
  "theme-select": { id: "theme-select", cls: "converging", auth: "l1", params: [{ name: "name", kind: "str", required: true }] },
  "theme-reload": { id: "theme-reload", cls: "converging", auth: "l1", params: [] },
  "theme-get": { id: "theme-get", cls: "read", auth: "l0", params: [] },
  "system-reload-config": { id: "system-reload-config", cls: "converging", auth: "l1", params: [] },
  "system-get-state": { id: "system-get-state", cls: "read", auth: "l0", params: [] },
  "system-version": { id: "system-version", cls: "read", auth: "l0", params: [] },
};

/** Give a window keyboard focus */
export function windowFocus(target: string): { action: string; args: Record<string, unknown> } {
  return { action: "window-focus", args: { target: target } };
}

/** Move focus spatially */
export function windowFocusDirection(direction: string, wrap?: boolean): { action: string; args: Record<string, unknown> } {
  return { action: "window-focus-direction", args: { direction: direction, wrap: wrap } };
}

/** Move a window to a position */
export function windowMove(target: string, x: number, y: number): { action: string; args: Record<string, unknown> } {
  return { action: "window-move", args: { target: target, x: x, y: y } };
}

/** Resize a window */
export function windowResize(target: string, width: number, height: number): { action: string; args: Record<string, unknown> } {
  return { action: "window-resize", args: { target: target, width: width, height: height } };
}

/** Ask a window to close */
export function windowClose(target: string): { action: string; args: Record<string, unknown> } {
  return { action: "window-close", args: { target: target } };
}

/** Set or clear fullscreen */
export function windowSetFullscreen(target: string, on: boolean): { action: string; args: Record<string, unknown> } {
  return { action: "window-set-fullscreen", args: { target: target, on: on } };
}

/** Set or clear maximized */
export function windowSetMaximized(target: string, on: boolean): { action: string; args: Record<string, unknown> } {
  return { action: "window-set-maximized", args: { target: target, on: on } };
}

/** Float or tile a window */
export function windowSetFloating(target: string, on: boolean): { action: string; args: Record<string, unknown> } {
  return { action: "window-set-floating", args: { target: target, on: on } };
}

/** Raise a window in the stacking order */
export function windowRaise(target: string): { action: string; args: Record<string, unknown> } {
  return { action: "window-raise", args: { target: target } };
}

/** Lower a window in the stacking order */
export function windowLower(target: string): { action: string; args: Record<string, unknown> } {
  return { action: "window-lower", args: { target: target } };
}

/** Send a window to a workspace */
export function windowToWorkspace(target: string, workspace: string, follow?: boolean): { action: string; args: Record<string, unknown> } {
  return { action: "window-to-workspace", args: { target: target, workspace: workspace, follow: follow } };
}

/** Send a window to another output */
export function windowToOutput(target: string, output: string): { action: string; args: Record<string, unknown> } {
  return { action: "window-to-output", args: { target: target, output: output } };
}

/** Swap two windows in the layout */
export function windowSwap(target: string, other: string): { action: string; args: Record<string, unknown> } {
  return { action: "window-swap", args: { target: target, other: other } };
}

/** List managed windows */
export function windowList(filter?: string): { action: string; args: Record<string, unknown> } {
  return { action: "window-list", args: { filter: filter } };
}

/** Read one window's full state */
export function windowGet(target: string): { action: string; args: Record<string, unknown> } {
  return { action: "window-get", args: { target: target } };
}

/** Switch to a workspace */
export function workspaceFocus(workspace: string): { action: string; args: Record<string, unknown> } {
  return { action: "workspace-focus", args: { workspace: workspace } };
}

/** Move to the next or previous workspace */
export function workspaceCycle(direction: string, wrap?: boolean): { action: string; args: Record<string, unknown> } {
  return { action: "workspace-cycle", args: { direction: direction, wrap: wrap } };
}

/** Create a workspace */
export function workspaceCreate(name: string, output?: string): { action: string; args: Record<string, unknown> } {
  return { action: "workspace-create", args: { name: name, output: output } };
}

/** Destroy a workspace */
export function workspaceDestroy(workspace: string): { action: string; args: Record<string, unknown> } {
  return { action: "workspace-destroy", args: { workspace: workspace } };
}

/** Rename a workspace */
export function workspaceRename(workspace: string, name: string): { action: string; args: Record<string, unknown> } {
  return { action: "workspace-rename", args: { workspace: workspace, name: name } };
}

/** Move a workspace to an output */
export function workspaceMoveToOutput(workspace: string, output: string): { action: string; args: Record<string, unknown> } {
  return { action: "workspace-move-to-output", args: { workspace: workspace, output: output } };
}

/** List workspaces */
export function workspaceList(): { action: string; args: Record<string, unknown> } {
  return { action: "workspace-list", args: {  } };
}

/** Set a workspace's layout */
export function layoutSet(workspace: string, layout: string): { action: string; args: Record<string, unknown> } {
  return { action: "layout-set", args: { workspace: workspace, layout: layout } };
}

/** Set the split orientation */
export function layoutSetOrientation(workspace: string, orientation: string): { action: string; args: Record<string, unknown> } {
  return { action: "layout-set-orientation", args: { workspace: workspace, orientation: orientation } };
}

/** Set inner and outer gaps */
export function layoutSetGaps(inner: number, outer: number): { action: string; args: Record<string, unknown> } {
  return { action: "layout-set-gaps", args: { inner: inner, outer: outer } };
}

/** Equalize sibling sizes */
export function layoutEqualize(workspace?: string): { action: string; args: Record<string, unknown> } {
  return { action: "layout-equalize", args: { workspace: workspace } };
}

/** Read a workspace's layout */
export function layoutGet(workspace: string): { action: string; args: Record<string, unknown> } {
  return { action: "layout-get", args: { workspace: workspace } };
}

/** Enable or disable an output */
export function outputSetEnabled(output: string, on: boolean): { action: string; args: Record<string, unknown> } {
  return { action: "output-set-enabled", args: { output: output, on: on } };
}

/** Set an output's resolution and refresh */
export function outputSetMode(output: string, width: number, height: number, refresh?: number): { action: string; args: Record<string, unknown> } {
  return { action: "output-set-mode", args: { output: output, width: width, height: height, refresh: refresh } };
}

/** Set an output's scale factor */
export function outputSetScale(output: string, scale: number): { action: string; args: Record<string, unknown> } {
  return { action: "output-set-scale", args: { output: output, scale: scale } };
}

/** Rotate or flip an output */
export function outputSetTransform(output: string, transform: string): { action: string; args: Record<string, unknown> } {
  return { action: "output-set-transform", args: { output: output, transform: transform } };
}

/** Place an output in the layout */
export function outputSetPosition(output: string, x: number, y: number): { action: string; args: Record<string, unknown> } {
  return { action: "output-set-position", args: { output: output, x: x, y: y } };
}

/** List outputs and their modes */
export function outputList(): { action: string; args: Record<string, unknown> } {
  return { action: "output-list", args: {  } };
}

/** Set key repeat rate and delay */
export function inputSetRepeat(rate: number, delay: number): { action: string; args: Record<string, unknown> } {
  return { action: "input-set-repeat", args: { rate: rate, delay: delay } };
}

/** Set the keyboard layout */
export function inputSetLayout(layout: string, variant?: string): { action: string; args: Record<string, unknown> } {
  return { action: "input-set-layout", args: { layout: layout, variant: variant } };
}

/** Bind a key chord to an action */
export function inputBind(chord: string, action: string, mode?: string): { action: string; args: Record<string, unknown> } {
  return { action: "input-bind", args: { chord: chord, action: action, mode: mode } };
}

/** Remove a key binding */
export function inputUnbind(chord: string, mode?: string): { action: string; args: Record<string, unknown> } {
  return { action: "input-unbind", args: { chord: chord, mode: mode } };
}

/** Switch the active keymap mode */
export function inputSetMode(mode: string): { action: string; args: Record<string, unknown> } {
  return { action: "input-set-mode", args: { mode: mode } };
}

/** Inject a synthetic key sequence */
export function inputSendKeys(keys: string, target?: string): { action: string; args: Record<string, unknown> } {
  return { action: "input-send-keys", args: { keys: keys, target: target } };
}

/** List active key bindings */
export function inputListBindings(mode?: string): { action: string; args: Record<string, unknown> } {
  return { action: "input-list-bindings", args: { mode: mode } };
}

/** Set the focus-follows-mouse policy */
export function focusSetPolicy(policy: string): { action: string; args: Record<string, unknown> } {
  return { action: "focus-set-policy", args: { policy: policy } };
}

/** Read what currently has focus */
export function focusGet(): { action: string; args: Record<string, unknown> } {
  return { action: "focus-get", args: {  } };
}

/** Lock the session */
export function sessionLock(): { action: string; args: Record<string, unknown> } {
  return { action: "session-lock", args: {  } };
}

/** Unlock the session after authentication */
export function sessionUnlock(): { action: string; args: Record<string, unknown> } {
  return { action: "session-unlock", args: {  } };
}

/** End the session */
export function sessionLogout(): { action: string; args: Record<string, unknown> } {
  return { action: "session-logout", args: {  } };
}

/** Suspend the machine */
export function sessionSuspend(): { action: string; args: Record<string, unknown> } {
  return { action: "session-suspend", args: {  } };
}

/** Reboot the machine */
export function sessionReboot(): { action: string; args: Record<string, unknown> } {
  return { action: "session-reboot", args: {  } };
}

/** Power the machine off */
export function sessionPoweroff(): { action: string; args: Record<string, unknown> } {
  return { action: "session-poweroff", args: {  } };
}

/** Switch to another virtual terminal */
export function sessionSwitchVt(vt: number): { action: string; args: Record<string, unknown> } {
  return { action: "session-switch-vt", args: { vt: vt } };
}

/** Read session state */
export function sessionGet(): { action: string; args: Record<string, unknown> } {
  return { action: "session-get", args: {  } };
}

/** Authenticate a user against PAM */
export function loginAuthenticate(user: string): { action: string; args: Record<string, unknown> } {
  return { action: "login-authenticate", args: { user: user } };
}

/** Start a session for an authenticated user */
export function loginStartSession(user: string, session?: string): { action: string; args: Record<string, unknown> } {
  return { action: "login-start-session", args: { user: user, session: session } };
}

/** End a session and close its PAM handle */
export function loginEndSession(user: string): { action: string; args: Record<string, unknown> } {
  return { action: "login-end-session", args: { user: user } };
}

/** Switch to another user's session */
export function loginSwitchUser(user: string): { action: string; args: Record<string, unknown> } {
  return { action: "login-switch-user", args: { user: user } };
}

/** List active sessions */
export function loginListSessions(): { action: string; args: Record<string, unknown> } {
  return { action: "login-list-sessions", args: {  } };
}

/** Read the seat's identity and devices */
export function seatGet(): { action: string; args: Record<string, unknown> } {
  return { action: "seat-get", args: {  } };
}

/** Spawn a program */
export function launchSpawn(command: string, workspace?: string): { action: string; args: Record<string, unknown> } {
  return { action: "launch-spawn", args: { command: command, workspace: workspace } };
}

/** Focus a program's window, or spawn it */
export function launchFocusOrSpawn(criteria: string, command: string): { action: string; args: Record<string, unknown> } {
  return { action: "launch-focus-or-spawn", args: { criteria: criteria, command: command } };
}

/** Read the clipboard */
export function clipboardGet(selection?: string): { action: string; args: Record<string, unknown> } {
  return { action: "clipboard-get", args: { selection: selection } };
}

/** Write the clipboard */
export function clipboardPut(content: string, selection?: string): { action: string; args: Record<string, unknown> } {
  return { action: "clipboard-put", args: { content: content, selection: selection } };
}

/** Clear the clipboard */
export function clipboardClear(selection?: string): { action: string; args: Record<string, unknown> } {
  return { action: "clipboard-clear", args: { selection: selection } };
}

/** Capture a screenshot */
export function captureScreenshot(target?: string, path?: string): { action: string; args: Record<string, unknown> } {
  return { action: "capture-screenshot", args: { target: target, path: path } };
}

/** Start a screencast */
export function captureScreencastStart(target?: string): { action: string; args: Record<string, unknown> } {
  return { action: "capture-screencast-start", args: { target: target } };
}

/** Stop a screencast */
export function captureScreencastStop(): { action: string; args: Record<string, unknown> } {
  return { action: "capture-screencast-stop", args: {  } };
}

/** Post a notification */
export function notifySend(summary: string, body?: string, urgency?: string): { action: string; args: Record<string, unknown> } {
  return { action: "notify-send", args: { summary: summary, body: body, urgency: urgency } };
}

/** Dismiss a notification */
export function notifyDismiss(target: string): { action: string; args: Record<string, unknown> } {
  return { action: "notify-dismiss", args: { target: target } };
}

/** Select the active theme */
export function themeSelect(name: string): { action: string; args: Record<string, unknown> } {
  return { action: "theme-select", args: { name: name } };
}

/** Re-read the active theme's artifacts */
export function themeReload(): { action: string; args: Record<string, unknown> } {
  return { action: "theme-reload", args: {  } };
}

/** Read the active theme */
export function themeGet(): { action: string; args: Record<string, unknown> } {
  return { action: "theme-get", args: {  } };
}

/** Re-read the desktop configuration */
export function systemReloadConfig(): { action: string; args: Record<string, unknown> } {
  return { action: "system-reload-config", args: {  } };
}

/** Read the whole observable desktop state */
export function systemGetState(): { action: string; args: Record<string, unknown> } {
  return { action: "system-get-state", args: {  } };
}

/** Read the desktop's version and backend */
export function systemVersion(): { action: string; args: Record<string, unknown> } {
  return { action: "system-version", args: {  } };
}

