// Generated by saihai-forge (typescript conformance) — DO NOT EDIT
//
// Compares this client against corpus.json, emitted from the Rust
// reference. Different code paths, so an emitter bug is detectable.

import { describe, it, expect } from "vitest";
import corpus from "./corpus.json";
import { ACTIONS } from "./client";

describe("saihai conformance", () => {
  it("exposes exactly the catalog's actions", () => {
    expect(Object.keys(ACTIONS).length).toBe(corpus.count);
  });
  for (const a of corpus.actions as any[]) {
    it(`${a.id} matches the corpus`, () => {
      const m = ACTIONS[a.id];
      expect(m).toBeDefined();
      expect(m.cls).toBe(a.class);
      expect(m.auth).toBe(a.auth);
      expect(m.params.length).toBe(a.params.length);
      a.params.forEach((p: any, i: number) => {
        expect(m.params[i].name).toBe(p.name);
        expect(m.params[i].required).toBe(p.required);
      });
    });
    it(`${a.id} is blind iff it observes nothing`, () => {
      const blind = a.class === "blind";
      expect(blind).toBe(a.kind === "mutate" && a.observed === 0);
    });
  }
});
